$ErrorActionPreference = "Stop"

$jsonFile = "C:\Users\Akobir\.gemini\antigravity\scratch\eco_law_bot\data\quiz.json"
$jsonStr = Get-Content -Raw -Path $jsonFile -Encoding UTF8
$jsonObj = ConvertFrom-Json -InputObject $jsonStr

$newQuizzesStr = @"
[
    { "id": "bq61", "question": "Yerning 'qattiq qobig'i' ilmiy tilda nima deb ataladi?", "options": ["Litosfera", "Gidrosfera", "Atmosfera", "Biosfera"], "answer_index": 0, "explanation": "To'g'ri! Litosfera (yunoncha 'lithos' - tosh) Yerning tashqi qattiq qatlamidir." },
    { "id": "bq62", "question": "O'zbekiston Qizil kitobi birinchi marta qachon nashr etilgan?", "options": ["1984 yil", "1991 yil", "2005 yil", "1960 yil"], "answer_index": 0, "explanation": "To'g'ri! O'zbekiston SSR Qizil kitobi ilk bor 1984 yilda chop etilgan." },
    { "id": "bq63", "question": "Tabiatdagi barcha oziq zanjirlarining oxirgi halqasida kimlar turadi?", "options": ["O'simliklar", "Yirtqichlar", "Redutsentlar (Parchalovchilar)", "Odamlar"], "answer_index": 2, "explanation": "To'g'ri! Redutsentlar (bakteriya va zamburug'lar) har qanday o'lik organikani parchalab beradi." },
    { "id": "bq64", "question": "Klimat o'zgarishi natijasida kelib chiquvchi 'El-Ninyo' hodisasi qaysi okeanda yuz beradi?", "options": ["Atlantika", "Tinch okeani", "Hind okeani", "Shimoliy Muz okeani"], "answer_index": 1, "explanation": "To'g'ri! El-Ninyo - Tinch okeanining ekvatorial qismida suvning g'ayritabiiy isishi." },
    { "id": "bq65", "question": "Yashil o'simliklar Quyosh energiyasining taxminan necha foizini o'zlashtiradi?", "options": ["100%", "50%", "1-2%", "10%"], "answer_index": 2, "explanation": "To'g'ri! O'simliklar Yerga tushayotgan quyosh nurining atigi 1-2 foizidangina fotosintez uchun foydalanadi." },
    { "id": "bq66", "question": "O'zbekistonda eng muhim strategik tabiiy resurs nima?", "options": ["Oltin", "Paxta", "Suv", "Ko'mir"], "answer_index": 2, "explanation": "To'g'ri! Iqlim sharoitimiz qurg'oqchil bo'lganligi uchun Suv eng bebaho va strategik resursdir." },
    { "id": "bq67", "question": "Atmosferaning qaysi qatlamida bulutlar hosil bo'ladi va ob-havo o'zgarishlari yuz beradi?", "options": ["Stratosfera", "Troposfera", "Mezosfera", "Ionosfera"], "answer_index": 1, "explanation": "To'g'ri! Troposfera eng quyi qatlam bo'lib, iqlim hodisalarining barchasi shu yerda ro'y beradi." },
    { "id": "bq68", "question": "O'zbekistonning eng chekka g'arbida qaysi tabiiy obyekt joylashgan?", "options": ["Orol dengizi", "Ustyurt platosi", "Tyan-Shan tog'lari", "Qizilqum"], "answer_index": 1, "explanation": "To'g'ri! Ustyurt platosi Qoraqalpog'istonning chekka g'arbiy hududida joylashgan." },
    { "id": "bq69", "question": "Odam tomonidan sun'iy ravishda yaratilgan barqaror ekotizim nima deb ataladi?", "options": ["Biotsenoz", "Agrotsenoz", "Noosfera", "Biotop"], "answer_index": 1, "explanation": "To'g'ri! Agrotsenoz (masalan, paxta dalasi, olma bog'i) inson yaratgan va boshqaradigan ekotizimdir." },
    { "id": "bq70", "question": "Yer yuzining necha foizi o'rmonlar bilan qoplangan?", "options": ["50%", "30%", "10%", "5%"], "answer_index": 1, "explanation": "To'g'ri! Hozirgi kunda Yer quruqlik qismining qariyb 30% i o'rmonlardan iborat." },
    { "id": "bq71", "question": "Qaysi qush turi dunyoda eng ko'p tarqalgan?", "options": ["Kabutar", "Uy tovug'i", "Chumchuq", "Burgut"], "answer_index": 1, "explanation": "To'g'ri! Uy parrandasi bo'lgan tovuqlar soni insonlar sonidan ham bir necha marta ko'p (qariyb 25 mlrd)." },
    { "id": "bq72", "question": "Atrof-muhitni ifloslantirganlik uchun 'Ifoslantiruvchi to'laydi' prinsipi qachon e'lon qilingan?", "options": ["1972 yil", "1992 yil Rio", "2015 yil", "1960 yil"], "answer_index": 1, "explanation": "To'g'ri! Rio-de-Janeyro deklaratsiyasida ekologik zararni qoplash qoidasi xalqaro darajada mustahkamlangan." },
    { "id": "bq73", "question": "Qaysi o'simlik 'Tirik qazilma' (Relikt) hisoblanadi?", "options": ["Eman (Dub)", "Ginkgo Biloba", "Qarag'ay", "Lola"], "answer_index": 1, "explanation": "To'g'ri! Ginkgo daraxti dinozavrlar davridan beri o'zgarmasdan saqlanib qolgan noyob turdir." },
    { "id": "bq74", "question": "Organizmning yashash muhiti haroratiga ko'ra turlarga ajratilishi:", "options": ["Gidrofil va Gidrofob", "Poykiloterm va Gomoyoterm", "Avtotrof va Geterotrof", "Biotik va Abiotik"], "answer_index": 1, "explanation": "To'g'ri! Poykiloterm (sovuqqonli) va Gomoyoterm (issiqqonli) hayvonlarga bo'linadi." },
    { "id": "bq75", "question": "Insonning ekologik huquqlari orasida eng muhimi qaysi?", "options": ["Istagan joyiga daraxt ekish huquqi", "Qulay atrof-muhitga va uning holati haqida ishonchli ma'lumot olish huquqi", "Tog'da yashash huquqi", "Mashina haydash huquqi"], "answer_index": 1, "explanation": "To'g'ri! Har bir inson toza havoda, xavfsiz muhitda yashash huquqiga ega." },
    { "id": "bq76", "question": "Birinchi marta 'Ekologiya' atamasini qachon ilmiy muomalaga kiritilgan?", "options": ["1866 yilda", "1910 yilda", "1950 yilda", "2000 yilda"], "answer_index": 0, "explanation": "To'g'ri! Ernst Gekkel 1866 yilda ushbu tushunchani yaratgan." },
    { "id": "bq77", "question": "Tabiatdagi suv hajmining eng kam qismini nima tashkil qiladi?", "options": ["Yer osti suvlari", "Daryo va ko'llar suvi", "Muzliklar", "Okeanlar"], "answer_index": 1, "explanation": "To'g'ri! Daryo va ko'llardagi ichishga yaroqli erkin suv umumiy suvning atigi 0.01% idan ham kamroq." },
    { "id": "bq78", "question": "O'zbekistonda yovvoyi hayvonlar hayotini o'rganuvchi fan qanday ataladi?", "options": ["Botanika", "Zoologiya", "Ekologiya", "Anatomiya"], "answer_index": 1, "explanation": "To'g'ri! Zoologiya fani hayvonot olamini va ularning yashash tarzi (jumladan O'zbekistondagi turlarni) o'rganadi." },
    { "id": "bq79", "question": "Atmosferada ozon qatlami qaysi balandlikda joylashgan?", "options": ["5-10 km", "20-30 km", "50-100 km", "Yerdan 1 km"], "answer_index": 1, "explanation": "To'g'ri! Ozon ekrani stratosfera qatlamida, Yerdan taxminan 20-30 km balandlikda joylashgan." },
    { "id": "bq80", "question": "Planktonlar nima?", "options": ["Okean tubidagi yirik hayvonlar", "Suvda erkin suzib yuruvchi va oqimga qarshi harakatlana olmaydigan mayda organizmlar", "Osmon jismlari", "Cho'l o'simliklari"], "answer_index": 1, "explanation": "To'g'ri! Planktonlar (fito va zooplankton) barcha dengiz oziq zanjirining asosi hisoblanadi." }
]
"@

$newPuzzlesStr = @"
[
    { "id": "bp61", "story": "Uzoq o'tmishda ovchilar o'rmondagi barcha bo'rilarni qirib tashlashdi. Keyingi yillari bug'ular shunchalik ko'payib ketdiki, o'rmondagi barcha yosh nihollarni yeb bitirishdi.", "question": "O'rmonni qanday qutqarish mumkin edi?", "options": ["Bug'ularni ham qirib tashlash", "Bo'rilarni ekotizimga qaytarish (Reintroduksiya)", "Daraxtlarni zaharli qilish"], "answer_index": 1, "explanation": "To'g'ri! Yirtqichlar populyatsiyani (kasal va qari hayvonlarni yeb) sog'lom va me'yorda ushlab turadi." },
    { "id": "bp62", "story": "Shahar meriyasi ko'cha chetidagi tabiiy (yovvoyi) o't-o'lanlarni yulib, o'rniga faqat bitta turdagi chet el gazonini ekdi.", "question": "Buning ekologiyaga qanday salbiy ta'siri bor?", "options": ["Faqat xarajat ko'paydi", "Mahalliy kapalaklar, asalarilar va qushlar ozuqasiz qoldi, bioxilma-xillik yo'qoldi", "Hech qanday ta'siri yo'q"], "answer_index": 1, "explanation": "To'g'ri! Tabiiy xilma-xil maysazorlar mahalliy hasharotlar uchun eng muhim yashash muhitidir." },
    { "id": "bp63", "story": "Odamlar ekinlarni sug'orish uchun daryo suvining 90 foizini to'sib, kanallarga burib yuborishdi.", "question": "Daryo quyiladigan hududlarda nima yuz beradi?", "options": ["Daryo tozalab qolinadi", "Daryo etagi quriydi, botqoqliklar yo'qoladi, yer sho'rlanib qurg'oqchilik kelib chiqadi (masalan, Orol dengizi fojeasi)", "Daryo tubi chuqurlashadi"], "answer_index": 1, "explanation": "To'g'ri! Daryo ekotizimining quyi qismi suvsizlikdan butunlay halokatga uchraydi." },
    { "id": "bp64", "story": "Fermer dala yonida katta miqdordagi go'ng va organik chiqindilarni yillar davomida ochiq holda to'plab qo'ydi.", "question": "Bu ochiq uyumning qanday zarari bor?", "options": ["Zarari yo'q, u o'g'it", "Chirish natijasida havoga ko'p miqdorda Metan gazi (issiqxona gazi) ajralib chiqadi va iqlimni isitadi", "Havo tozalanadi"], "answer_index": 1, "explanation": "To'g'ri! Organik qoldiqlar (ayniqsa chorvachilik) noto'g'ri saqlanganda juda kuchli issiqxona gazi bo'lgan metan tarqatadi." },
    { "id": "bp65", "story": "Tabiatni asrash maqsadida hamma qog'oz ishlatishni to'xtatib, faqat raqamli qurilmalardan (telefon, kompyuter) foydalana boshladi.", "question": "Bu haqiqatdan ham ekologiyani 100% qutqaradimi?", "options": ["Ha, daraxtlar kesilmaydi", "Yo'q, raqamli texnologiyalar ishlashi uchun zarur bo'lgan serverlar (Data markazlar) va elektr energiyasi katta miqdorda karbonat angidrid chiqaradi", "Faqat pul tejaladi"], "answer_index": 1, "explanation": "To'g'ri! Raqamli dunyo (internet, bulutli xotiralar) aslida ulkan elektr energiyasini talab qiluvchi juda yirik ifloslantiruvchi sohadir." },
    { "id": "bp66", "story": "Qishda yo'llar muzlamasligi uchun kommunal xizmatlar yerga millionlab tonna texnik tuz sepishdi.", "question": "Bahorda qor eriganda bu tuz tabiatga nima qiladi?", "options": ["Yer o'g'itlanadi", "Tuzlar erib tuproq va yer osti suvlariga singadi, daraxtlarni quritadi va suvlarni sho'rlatadi", "Hech narsa qilmaydi"], "answer_index": 1, "explanation": "To'g'ri! Muzga qarshi tuz sepish shahar tuprog'i va o'simliklarini quritib yuboruvchi o'ta zararli usuldir." },
    { "id": "bp67", "story": "Olimlar baliqlar oshqozonidan nafaqat plastik idish parchalarini, balki kiyim-kechak iplarini ham topishdi.", "question": "Kiyim iplari okeanga qanday tushgan bo'lishi mumkin?", "options": ["Kemadagi odamlar kiyimini tashlagan", "Uyda kir yuvish mashinasidan chiqqan sintetik (poliester) tolalar kanalizatsiya orqali daryo va okeanlarga yetib borgan", "Shamol uchirgan"], "answer_index": 1, "explanation": "To'g'ri! Sintetik kiyimlar har yuvilganda o'zidan minglab ko'zga ko'rinmas mikroplastik tolalarni ajratadi va bu okeanlarni ifloslantirmoqda." },
    { "id": "bp68", "story": "Odamlar o'rmondagi yovvoyi ayiqlarni qiziqish uchun har kuni ovqatlantira boshlashdi.", "question": "Ayiqlarga buning qanday yomon ta'siri bor?", "options": ["Faqat semirib ketadi", "Ayiklar mustaqil ov qilishni unutadi, odamdan qo'rqmay qo'yadi va bora-bora odamlar uylariga bostirib kirib xavf tug'diradi", "Yomon ta'siri yo'q"], "answer_index": 1, "explanation": "To'g'ri! Yovvoyi hayvonlarni inson ozuqasiga o'rgatish ularning tabiiy instinktlarini buzadi va oxir-oqibat hayvonning o'limiga sabab bo'ladi." },
    { "id": "bp69", "story": "Zavod yaqinidagi o'rmon daraxtlarida avval uchraydigan lishaynik (moxsimon o'simlik) lar butunlay yo'qolib ketdi. Ammo barglar joyida turibdi.", "question": "Buning sababi nima bo'lishi mumkin?", "options": ["Yomg'ir yog'magani", "Zavod tutunidan havo kuchli ifloslangani. Lishayniklar eng kuchli bioindikator bo'lib, faqat top-toza havoda yashaydi", "Qushlar yeb qo'ygani"], "answer_index": 1, "explanation": "To'g'ri! Lishayniklarning yo'qolishi havodagi oltingugurt dioksidi (SO2) kabi zaharlar ortganini bildiradi." },
    { "id": "bp70", "story": "Uy qurilishi munosabati bilan bog'dagi eski, ichi kovak daraxtni kesib tashlashdi. Tez orada bog'ni zararkunandalar bosdi.", "question": "Qanday aloqasi bor?", "options": ["Daraxtning kasali tarqaldi", "Eski kovak daraxtda boyo'g'li va ko'rshapalaklar yashardi. Ular kesilgach zararkunandalarni yeydigan jonzot qolmadi", "Hech qanday aloqasi yo'q"], "answer_index": 1, "explanation": "To'g'ri! Kovakli daraxtlar tunda ov qiluvchi foydali qushlar va ko'rshapalaklar uchun bebaho uydir." },
    { "id": "bp71", "story": "Baliqchilar ko'lga ov qilish uchun boshqa o'lkadan keltirilgan yangi, yirik va yirtqich baliq turini tashlashdi.", "question": "Ko'ldagi mahalliy mayda baliqlarga nima bo'ladi?", "options": ["Ular yirik baliqlar bilan do'stlashadi", "Yangi (invaziv) yirtqich mahalliy baliqlarni qirib tashlaydi, ko'lning butun ekotizimi izdan chiqadi", "Mayda baliqlar ham kattalashadi"], "answer_index": 1, "explanation": "To'g'ri! Begona yirtqich turlarni (invaziv turlar) yangi joyga kiritish mahalliy faunani butunlay qirilib ketishiga olib keluvchi ekologik xatodir." },
    { "id": "bp72", "story": "Shaharsozlar avtomobil tirbandligini kamaytirish uchun ko'chadagi daraxtlarni kesib, yo'lni kengaytirishdi.", "question": "Shahar mikroiqlimiga nima bo'ldi?", "options": ["Havo tozalandi", "Daraxtlar soyasi va chang tutish xususiyati yo'qolgani uchun ko'chalarda harorat keskin ko'tarilib (issiqlik oroli), havo qattiq ifloslandi", "Havo sovuq bo'lib qoldi"], "answer_index": 1, "explanation": "To'g'ri! Daraxtlarni kesib asfaltni ko'paytirish shaharlarni chidab bo'lmas darajada isitadi va beton changi ko'payadi." },
    { "id": "bp73", "story": "Dam oluvchilar o'rmonga turli shisha idishlarni (butulkalarni) tashlab ketishdi. Quyoshli kunlarning birida shu yerdan olov chiqdi.", "question": "Shisha qanday qilib yong'in chiqardi?", "options": ["Shisha qizib portladi", "Shisha parchasi linza vazifasini bajarib, quyosh nurlarini bitta nuqtaga (quruq o'tga) to'pladi va uni yondirib yubordi", "Shisha yonuvchi modda"], "answer_index": 1, "explanation": "To'g'ri! Tabiatda qoldirilgan oynalar va shisha butulkalar yozda quyosh nurini to'plab o'rmon yong'inlarini keltirib chiqaruvchi 'linza'ga aylanadi." },
    { "id": "bp74", "story": "Olimlar qutb ayiqlarining qonidan Antarktidada umuman ishlatilmaydigan pestisidlar (qishloq xo'jaligi zaharlari) qoldig'ini topishdi.", "question": "Qanday qilib zahar qutbga yetib bordi?", "options": ["Sayyohlar olib borgan", "Pestisidlar daryolar orqali okeanga tushib, planktonlarga, so'ngra baliqlarga, tyulenlarga, oxiri ularni yegan oq ayiqlarga (biologik yig'ilish) o'tgan", "Qutbda ham dehqonchilik qilingan"], "answer_index": 1, "explanation": "To'g'ri! Biomagnifikatsiya jarayoni orqali zaharlar oziq zanjirining eng cho'qqisida turgan hayvonlarga minglab barobar kuchliroq bo'lib yetib boradi." },
    { "id": "bp75", "story": "O'zbekistonda lalmi (suvsiz) tog' yonbag'irlariga ko'plab bodom va pista daraxtlari ekila boshlandi.", "question": "Bu ekologiya uchun qanday foyda beradi?", "options": ["Faqat hosil olinadi", "Qurg'oqchilikka chidamli daraxtlar tuproq eroziyasini (sel va ko'chkilar) oldini oladi, hamda tog'larni yashillashtiradi", "Zarar keltiradi"], "answer_index": 1, "explanation": "To'g'ri! Tog' yonbag'irlarida o'rmon (bog') barpo etish tuproq yemirilishining (eroziyasining) eng yaxshi tabiiy davosidir." },
    { "id": "bp76", "story": "Zavod tutunini tozalovchi filtrlarni faqat tekshiruvchilar kelganda yoqib, tunda esa o'chirib qo'yishni odat qildi.", "question": "Bunday holatning atrofga yashirin xavfi nimada?", "options": ["Pul tejaladi", "Zaharli gazlar ayniqsa tunda inyersiya (havo bosimi tushishi) sababli yerga yaqinroq cho'kadi va uxlab yotgan aholining qattiq zaharlanishiga sabab bo'ladi", "Tunda zarar qilmaydi"], "answer_index": 1, "explanation": "To'g'ri! Tunda shamol pasayib, harorat tushgani uchun zaharli gazlar osmonga ko'tarilmay, to'g'ridan-to'g'ri odamlar yashaydigan qatlamga yoyiladi." },
    { "id": "bp77", "story": "Dehqon dalasida ekinlarga kimyoviy dori sepdi, lekin shu kuni qattiq shamol turdi.", "question": "Bu vaziyat qanday fojia keltirib chiqaradi?", "options": ["Dori uchib ketib yo'qoladi", "Shamol zaharni qo'shni qishloqlarga, suv havzalariga va yaylovlarga uchirib, u yerdagi o'simliklar, asalarilar va odamlarni zaharlaydi", "Shamol dorini kuchaytiradi"], "answer_index": 1, "explanation": "To'g'ri! Shamolli havoda zahar sepish xavfsizlik qoidalarini qo'pol ravishda buzish hisoblanib, ulkan zararlar (drift) keltiradi." },
    { "id": "bp78", "story": "Uy hayvonlari sifatida ko'p boqiladigan sigirlarning oshqozon faoliyati (kavsh qaytarishi) ekologlar tomonidan muammo deb e'lon qilindi.", "question": "Sababi nima?", "options": ["Go'shti kamaygani", "Sigirlar hazm qilish jarayonida havoga millionlab tonna Metan gazi ajratadi. Metan CO2 dan 25 barobar kuchli issiqxona gazidir", "Ko'p o't yeyishi"], "answer_index": 1, "explanation": "To'g'ri! Global isishning qariyb 14.5% i aynan chorvachilik, xususan qoramollar ajratadigan metan hissasiga to'g'ri keladi." },
    { "id": "bp79", "story": "Qishloqdagi yagona katta ko'l yoz faslida butunlay qurib qoldi. Lekin yomg'ir suvi bilan emas, undagi suv buloqdan kelardi.", "question": "Buloq nega quridi?", "options": ["Quyosh juda isib ketdi", "Yaqin atrofdagi dehqonlar yer ostidan suv so'ruvchi artezian quduqlarini haddan tashqari ko'p qazishgani uchun sizot suvlari sathi tushib ketdi", "Buloq qariydi"], "answer_index": 1, "explanation": "To'g'ri! Yer osti suvlaridan nazoratsiz foydalanish yer ustidagi buloq va ko'llarning qurishining asosiy sababidir." },
    { "id": "bp80", "story": "Yoshlar tog'da dam olib, ketish oldidan barcha plastik va qog'oz chiqindilarni bir joyga to'plab chuqurga ko'mib ketishdi.", "question": "Ular tabiatga yaxshilik qildimi?", "options": ["Ha, joy toza bo'ldi", "Yo'q, plastiklar yer ostida yuzlab yillar chirimay yotadi va yomg'ir yordamida tuproq va yer osti suvlarini zaharlashda davom etadi. Ularni shahar axlatxonasiga olib ketish kerak edi", "Plastik o'g'it bo'ladi"], "answer_index": 1, "explanation": "To'g'ri! Tabiat qo'ynida hech qanday chiqindini (ayniqsa sun'iy) ko'mib qoldirish mumkin emas. Ular yig'ilib maxsus zavodga ketishi shart." }
]
"@

$newTermsStr = @"
[
    { "id": "bt61", "question": "Iqlim inqirozi nima?", "options": ["Ob-havoning yomonlashishi", "Global isish va tabiatning keskin o'zgarishi natijasida insoniyat va ekotizimlar hayotiga jiddiy xavf tug'dirayotgan favqulodda holat", "Tog'larning qulashi"], "answer_index": 1, "explanation": "To'g'ri! Iqlim inqirozi hozirgi kunda butun dunyo davlatlari tomonidan tan olingan eng katta global tahdiddir." },
    { "id": "bt62", "question": "Zero Waste (Nol chiqindi) harakati nimani anglatadi?", "options": ["Hech narsa yemaslikni", "Barcha resurslarni qayta ishlash, hech narsani axlatxonaga tashlamaslik orqali tabiatga chiqindi chiqarmaslik falsafasi", "Faqat qog'oz ishlatishni"], "answer_index": 1, "explanation": "To'g'ri! Nol chiqindi – tabiatni asrashning radikal va eng ongli usuli bo'lib, axlatni minimal darajaga tushirishni ko'zlaydi." },
    { "id": "bt63", "question": "Akvakultura nima?", "options": ["Suv sporti turi", "Baliqlar, qisqichbaqalar va suv o'simliklarini sun'iy hovuz yoki maxsus fermalarda yetishtirish va ko'paytirish (Suv xo'jaligi)", "Suvni tozalash"], "answer_index": 1, "explanation": "To'g'ri! Akvakultura yovvoyi okean baliqlarini ortiqcha ovlanishdan saqlab qolish imkonini beruvchi sohadir." },
    { "id": "bt64", "question": "Karbonat kvotasi nima?", "options": ["Zavodlar soni", "Har bir davlat yoki korxonaga atmosferaga chiqarishga ruxsat etilgan karbonat angidrid (CO2) ning qat'iy belgilangan miqdori", "Avtomobillar narxi"], "answer_index": 1, "explanation": "To'g'ri! Kvotadan oshib ketgan zavodlar jarima to'laydi yoki tabiatni tozalovchi loyihalarga homiylik qilishi shart bo'ladi." },
    { "id": "bt65", "question": "Nitratlar nima va ularning zarari nimada?", "options": ["Foydali vitaminlar", "Azotli o'g'itlar qoldig'i bo'lib, oziq-ovqat va suvda to'plansa, inson qoniga ta'sir qilib zaharli (kanserogen) birikmalarga aylanadi", "Suv tozalagich"], "answer_index": 1, "explanation": "To'g'ri! Qishloq xo'jaligida azotli o'g'itlarni noto'g'ri va me'yordan ortiq qo'llash hosil tarkibida zaharli nitratlarni qoldiradi." },
    { "id": "bt66", "question": "Deforestatsiya nima?", "options": ["Daraxt ekish", "O'rmonlarni keng ko'lamda va yoppasiga kesib yuborish (o'rmonsizlashtirish) jarayoni", "Gullarni parvarishlash"], "answer_index": 1, "explanation": "To'g'ri! Deforestatsiya bioxilma-xillikni yo'q qiluvchi va global isishni tezlashtiruvchi eng yomon ofatdir." },
    { "id": "bt67", "question": "Aerozol (Ozon qatlamiga ta'siri doirasida) qanday vositalarda uchraydi?", "options": ["Televizorlarda", "Sepiladigan (purkaladigan) dezodorantlar, soch laklari va bo'yoq idishlari tarkibida", "Velosipedda"], "answer_index": 1, "explanation": "To'g'ri! Hozirgi kunda bunday idishlarga ozonni yemiruvchi gazlarni emas, zararsiz gazlarni to'ldirish (Ozone friendly) talab etiladi." },
    { "id": "bt68", "question": "Ekologik piramida qoidasi (10% qoidasi) nimani anglatadi?", "options": ["10 ta hayvon ovlanishi mumkinligini", "Oziq zanjirida bir bosqichdan ikkinchisiga o'tilganda energiyaning atigi 10% i uzatiladi, qolgan 90% i issiqlik bo'lib sarflanadi", "O'simliklar o'sishini"], "answer_index": 1, "explanation": "To'g'ri! Shuning uchun ham tabiatda o'txo'rlar soni yirtqichlarga qaraganda hamisha ko'p bo'lishi kerak." },
    { "id": "bt69", "question": "Brakonyerlik (Noqonuniy ov) qanday xatti-harakat?", "options": ["O'rmonda sayr qilish", "Litsenziyasiz, taqiqlangan joyda, taqiqlangan muddatda yoki taqiqlangan qurol (elektr qarmoq, qopqon) yordamida hayvonlarni ovlash", "Ko'lga suzish"], "answer_index": 1, "explanation": "To'g'ri! Brakonyerlik tabiat resurslarini talon-toroj qilish va jinoiy xatti-harakat hisoblanadi." },
    { "id": "bt70", "question": "Bioxilma-xillikning 'Qaynoq nuqtalari' (Hotspots) nima?", "options": ["Issiq mamlakatlar", "Dunyodagi eng ko'p noyob (endemik) turlar yashaydigan, lekin inson ta'siri tufayli kuchli xavf ostida qolgan va darhol himoya qilinishi shart bo'lgan hududlar", "Vulqon kraterlari"], "answer_index": 1, "explanation": "To'g'ri! Bunday hududlarni saqlab qolish xalqaro ekologik tashkilotlarning birinchi darajali vazifasidir." },
    { "id": "bt71", "question": "Agroekologiya nimani o'rganadi?", "options": ["Faqat traktorlarni", "Qishloq xo'jaligini tabiatga va tuproqqa zarar yetkazmaydigan tarzda, ekologik qonuniyatlar asosida yuritishni o'rganuvchi fan", "Suv sportini"], "answer_index": 1, "explanation": "To'g'ri! Agroekologiya kimyoviy o'g'itlardan voz kechib, hosildorlikni tabiiy usullar bilan ko'tarishga o'rgatadi." },
    { "id": "bt72", "question": "Tyotyo (Kyoto) bayonnomasining vorisi bo'lgan kelishuv qaysi?", "options": ["Stokgolm konvensiyasi", "2015 yilgi Parij bitimi (Paris Agreement)", "Ramsar konvensiyasi"], "answer_index": 1, "explanation": "To'g'ri! Parij bitimi barcha davlatlarni iqlim o'zgarishiga qarshi birlashtiruvchi va karbonat tashlamalarini kamaytiruvchi zamonaviy kelishuvdir." },
    { "id": "bt73", "question": "Sinantrop hayvonlar kimlar?", "options": ["Dengizda yashovchi yirtqichlar", "Odamning yashash muhitiga (uy, shahar) moslashgan va odam yonida yashovchi hayvonlar (masalan sichqon, suvarak, mayna, it, mushuk)", "Faqat cho'l hayvonlari"], "answer_index": 1, "explanation": "To'g'ri! Sinantrop turlar urbanizatsiyaga shunchalik moslashganki, ular endi insonlarsiz yashay olmaydi (yoki yashashni xohlamaydi)." },
    { "id": "bt74", "question": "Bentos (Benthos) nimani anglatadi?", "options": ["Suv ustidagi gullar", "Suv havzalarining tubida, tuproqqa (loyga) yopishib yoki uning ichiga kirib yashovchi organizmlar majmuasi", "Havo shari"], "answer_index": 1, "explanation": "To'g'ri! Suv o'tlari, marjonlar, qisqichbaqalar, midiyalar bentos hisoblanadi va ular suv tubi ekotizimini tashkil qiladi." },
    { "id": "bt75", "question": "Atmosferada issiqxona effektini vujudga keltiradigan asosiy gaz qaysi?", "options": ["Azot (N2)", "Karbonat angidrid (CO2)", "Argon"], "answer_index": 1, "explanation": "To'g'ri! Undan tashqari metan (CH4), azot oksidi (N2O) va su'niy freon gazlari ham isishga sabab bo'ladi." },
    { "id": "bt76", "question": "Tabiiy yodgorliklar nima?", "options": ["Bino va haykallar", "Ilmiy, tarixiy va estetik jihatdan noyob bo'lgan, alohida olingan tabiat ob'yektlari (masalan qadimiy daraxt, g'or, noyob sharshara)", "Muzeylar"], "answer_index": 1, "explanation": "To'g'ri! Ular davlat himoyasiga olinadi va u yerda o'zgartirish kiritish taqiqlanadi (masalan Yakkabog'dagi qadimiy archa)." },
    { "id": "bt77", "question": "Bioyoqilg'i (Biofuel) nima?", "options": ["Neftdan olinadigan benzin", "O'simlik xomashyosidan (masalan, makkajo'xori, raps yog'i) yoki organik qoldiqlardan olinadigan va tabiatga zarari kam bo'lgan yonilg'i turi", "Ko'mirning bir turi"], "answer_index": 1, "explanation": "To'g'ri! Bioyoqilg'i yonish vaqtida avval o'simlik bo'lib yutgan karbonatigina chiqaradi (uglerod balansi nolgacha keladi)." },
    { "id": "bt78", "question": "Sanoat ekologiyasi nimani o'rganadi?", "options": ["Sanoatni butunlay yopishni", "Zavod va fabrikalarni tabiatga kam zarar keltiradigan usulda ishlashini, \"chiqindisiz\" texnologiyalar yaratishni o'rganuvchi amaliy fan", "Faqat daromadni"], "answer_index": 1, "explanation": "To'g'ri! Sanoat ekologiyasining maqsadi zavodlarni go'yoki tabiatdagi \"ekotizim\" kabi ishlashiga, ya'ni bir zavod chiqindisi ikkinchisi uchun xom-ashyo bo'lishiga erishishdir." },
    { "id": "bt79", "question": "Geosfera nima?", "options": ["Kosmos qatlami", "Yer sayyorasining o'zaro bog'langan va bir-biriga ta'sir etuvchi barcha qobiqlari (litosfera, gidrosfera, atmosfera, biosfera) umumiy nomi", "Faqat quyosh"], "answer_index": 1, "explanation": "To'g'ri! Geosfera butun Yer sayyorasining hayot va jonsiz materiyalaridan iborat yaxlit tizimidir." },
    { "id": "bt80", "question": "Ramsar konvensiyasi (1971) qanday ob'yektlarni himoya qiladi?", "options": ["Tog'larni", "Xalqaro ahamiyatga ega bo'lgan suvli-botqoq (ayniqsa suv qushlari yashaydigan) hududlarni", "Faqat o'rmonlarni"], "answer_index": 1, "explanation": "To'g'ri! O'zbekistondagi Aydar-Arnasoy ko'llar tizimi kabi hududlar millionlab ko'chmanchi qushlarni asrash uchun ushbu ro'yxatga kiritilgan." }
]
"@

$newPenaltiesStr = @"
[
    { "id": "bpn61", "question": "Tunda daryolarda qanday usulda baliq ovlash qonunan brakonyerlik sanaladi?", "options": ["Oddiy qarmoq bilan", "Projektor (kuchli yoritgich) va tok (elektr qarmoq) bilan baliqlarni ko'r qilib (shok holatiga tushirib) tutish jinoiy javobgarlikka tortiladi", "Qishda ovlash"], "answer_index": 1, "explanation": "To'g'ri! Yoritgich va tok ishlatish shafqatsiz usullar bo'lib, ular barcha suv hayvonlarini yoppasiga qiradi." },
    { "id": "bpn62", "question": "Milliy bog' yoki qo'riqxonaga tegishli bo'lgan tuproqni yoki unumdor yerni kavlab olib sotgan fuqaroga nima bo'ladi?", "options": ["Foyda ko'radi", "Tuproq unumdor qatlamiga qasddan ziyon yetkazgani uchun moddiy zarar belgilanadi va jinoiy / ma'muriy chora ko'riladi", "Faqat hayfsan"], "answer_index": 1, "explanation": "To'g'ri! Tuproqning unumdor qatlami milliy boylikdir, uni qonunsiz kavlab olish (ayniqsa muhofaza hududida) og'ir jinoyat." },
    { "id": "bpn63", "question": "Sanoat chiqindilarini davlat ro'yxatidan o'tmagan joyga (masalan, cho'lga) to'kib kelgan korxona qanday jazoga tortiladi?", "options": ["Yopib qo'yilmaydi", "Jarima solinadi, atrof-muhitni ifloslantirgani uchun kompensatsiya (zarar) to'laydi va chiqindini o'z hisobidan maxsus poligonga tozalab olib borishga majbur qilinadi", "Faqat pul to'laydi"], "answer_index": 1, "explanation": "To'g'ri! Qonunga ko'ra (Zarar yetkazuvchi to'laydi) korxona nafaqat jarima beradi, balki joyni asl holiga qaytarishga majburdir." },
    { "id": "bpn64", "question": "O'zbekistonda yosh, endi o'sib kelayotgan (kesish man etilgan) qimmatbaho daraxtni nobud qilgan qurilish kompaniyasiga qanday sanksiya qo'llaniladi?", "options": ["Hech qanday", "Qonun bo'yicha u jarima to'laydi va bitta kesilgan daraxt o'rniga 100 dona qimmatbaho daraxt ko'chatini ekib, ularni 3 yil davomida parvarish qilish majburiyati yuklanadi", "Arzon jarima"], "answer_index": 1, "explanation": "To'g'ri! Moratoriy davrida daraxt kesish eng og'ir tarzda, kompensatsion ekish bilan jazolanadi." },
    { "id": "bpn65", "question": "Hayvonlarni transportda (mashina yoki vagonlarda) qiynab, suvsiz, havosiz va o'ta tirband tarzda tashigan shaxslarga chora bormi?", "options": ["Yo'q, bu o'zining moli", "Ha, Hayvonlarga shafqatsiz munosabatda bo'lish moddasi bo'yicha (MJtK 111) javobgarlikka tortiladi", "Qonun bunga aralashmaydi"], "answer_index": 1, "explanation": "To'g'ri! Hatto uy va xo'jalik hayvonlarini tashish va saqlashda ham ularni qiynamaslik bo'yicha qat'iy veterinariya va ekologiya talablari mavjud." },
    { "id": "bpn66", "question": "Qizil kitobga kiritilgan yovvoyi ayiq yoki qoplon terisidan qilingan mo'ynali kiyim (shuba) ni xorijga sotmoqchi bo'lgan shaxs...", "options": ["Bojxona to'lovini to'laydi", "Kontrabanda (Noyob hayvonot qismlari savdosi) moddasi bo'yicha Jinoiy javobgarlikka tortiladi va tovar musodara qilinadi", "Sotaveradi"], "answer_index": 1, "explanation": "To'g'ri! Xalqaro SITES konvensiyasiga ko'ra Qizil kitobdagi hayvonlarning o'zini, terisini yoki tishlarini oldi-sotdi qilish og'ir jinoyatdir." },
    { "id": "bpn67", "question": "Shaharlarda tungi vaqtda uy atrofi va ko'chalarda qurilish qilib yoxud musiqa baland qilib odamlar tinchini buzish (Akustik ifloslanish) necha so'm jarimaga sabab bo'ladi?", "options": ["Jarima yo'q", "MJtK 192-moddasiga asosan BHMning 1 dan 3 baravarigacha, agar takrorlansa ko'proq", "Faqat kechirim so'raydi"], "answer_index": 1, "explanation": "To'g'ri! Tungi vaqtlarda (23:00 dan 06:00 gacha) shovqin ifloslanishini keltirib chiqarish ma'muriy huquqbuzarlik hisoblanadi." },
    { "id": "bpn68", "question": "Ko'cha bo'yidagi daraxtning soyasi va ko'rinishini 'to'g'irlash' uchun ruxsatsiz, o'zboshimchalik bilan daraxt shoxlarini shafqatsiz butash (Toping usulida kesish) jazolanadimi?", "options": ["Yo'q, chiroyli qildi", "Ha, daraxtga qasddan shikast yetkazish (kesish bilan tenglashtirilgan) darajasida jarima solinadi", "Faqat tushuntirish beriladi"], "answer_index": 1, "explanation": "To'g'ri! Daraxtlarni mutaxassislarsiz, yalang'och tanasini qoldirib noto'g'ri butash daraxtning tezda qurib qolishiga olib keladi va bu jinoyatdir." },
    { "id": "bpn69", "question": "Avtomobil moylari va akkumulyator kislotalarini maxsus joyga emas, oddiy axlatxonaga yoxud ko'chaga to'kkan avtoservis ishchisi nega javobgar bo'ladi?", "options": ["Bu zarar qilmaydi", "Bular I-II darajali O'ta xavfli chiqindilar sirasiga kirib, tuproqni kuchli zaharlagani uchun yirik jarima (MJtK 83) solinadi", "Ruxsat etilgan"], "answer_index": 1, "explanation": "To'g'ri! Sanoat va mashina moylari oddiy chiqindi emas, ular alohida yig'ilib qayta ishlanishi qonun bilan belgilangan." },
    { "id": "bp70", "question": "O'zbekistonda yovvoyi piyoz yoki lola (Qizil kitobdagi turlar) ni olib kelib ko'chada sotayotgan fuqaroga qanday chora ko'riladi?", "options": ["Unga tegilmaydi", "Sotilayotgan noyob o'simliklar davlat foydasiga musodara qilinadi va tabiatga yetkazilgan millionlab so'mlik zarar undirilib (MJtK 79, Jk 202), javobgarlikka tortiladi", "Soliq to'laydi"], "answer_index": 1, "explanation": "To'g'ri! Qizil kitobga kirgan o'simliklarni nafaqat yulish, balki sotib olish va sotish ham qat'iyan man qilinadi." },
    { "id": "bpn71", "question": "O'rmon fondiga tegishli (masalan milliy bog') maydonlarga o'zboshimchalik bilan bostirib kirib u yerda dehqonchilik yoki qurilish qilgan shaxs...", "options": ["Yerni sotib olsa bo'ladi", "Binosi (ekinlari) o'z hisobidan buzib tashlanadi va yerni asl holatiga qaytarish bo'yicha ma'muriy (yoki jinoiy) javobgarlikka tortiladi", "Jazo yo'q"], "answer_index": 1, "explanation": "To'g'ri! Davlat o'rmon va qo'riqxona yerlari daxlsizdir, ularni egallab olish yer qonunchiligining o'ta qo'pol buzilishidir." },
    { "id": "bpn72", "question": "Hayvon kasalligi tarqalishining oldini olish bo'yicha veterinariya qoidalarini buzish oqibatida kasallik tarqalsa nima bo'ladi?", "options": ["Dori sepiladi", "Epidemiya va epizootiyaga sabab bo'lgan shaxs Jinoyat kodeksiga (257-1) muvofiq qamoqqa olinishi mumkin", "Jarima to'lanmaydi"], "answer_index": 1, "explanation": "To'g'ri! Hayvonlar kasalliklari (masalan qush grippi, quturish) tarqalishiga beparvolik jiddiy biologik xavf sanalib og'ir jazolanadi." },
    { "id": "bpn73", "question": "Tog'li hududlarda sayyohlar uchun osma yo'llar yoki mehmonxona qurishdan oldin majburiy hisoblanadigan hujjat nima?", "options": ["Qurilish litsenziyasi yetarli", "Davlat Ekologik Ekspertizasi xulosasi majburiydir (Ushbu loyiha atrof-muhitga zarar qilmasligini isbotlashi shart)", "Hech qanday hujjat"], "answer_index": 1, "explanation": "To'g'ri! \"Ekologik ekspertizasi to'g'risida\"gi qonunga muvofiq barcha qurilish loyihalari ekologlarning ruxsatisiz boshlanishi mumkin emas." },
    { "id": "bpn74", "question": "Avtomobil yuvish shahobchasi (Moyka) iflos suvni tozalovchi filtrlarsiz to'g'ridan-to'g'ri kanalizatsiyaga oqizsa nima bo'ladi?", "options": ["Suv tozalovchi joyga boradi-ku", "Korxona faoliyati darhol to'xtatilib, ekologiyaga yetkazilgan zarar (moy, kimyoviy ko'pik) uchun kompensatsiya undiriladi", "Jarima yo'q"], "answer_index": 1, "explanation": "To'g'ri! Barcha korxonalar o'zining chiqindi suvlari uchun lokal (mahalliy) tozalash inshootiga ega bo'lishi qat'iy talabdir." },
    { "id": "bpn75", "question": "O'zbekistonda shahar daraxtlarini reklama banerlari ilish, mix qoqish yoki sim bilan bog'lash orqali shikastlash (MJtK 79)...", "options": ["Ruxsat etilgan", "Daraxtni shikastlantirish sifatida baholanib, jarimaga tortiladi va reklamalar qonuniy tartibda uzib tashlanadi", "Faqat ko'rinishni buzadi"], "answer_index": 1, "explanation": "To'g'ri! Tirik tabiat ob'yektlarini (daraxtlarni) reklama stendi sifatida ishlatish tabiatga shafqatsizlik va noqonuniydir." },
    { "id": "bpn76", "question": "Oqova suvlarni (kanalizatsiyani) tozalamasdan daryoga to'kkan zavodning rahbari ma'muriy jarima bilan qutulib qoladimi?", "options": ["Ha, jarima arzon", "Yo'q, agar daryodagi baliqlarning ommaviy qirilishiga yoki odamlar kasallanishiga (og'ir oqibat) sabab bo'lsa u to'g'ridan-to'g'ri Jinoiy javobgarlikka (Jk 193) tortiladi", "Suddan qochib ketadi"], "answer_index": 1, "explanation": "To'g'ri! Ma'muriy jarima faqat kichik qoidabuzarlikda ishlaydi, tabiatga yetkazilgan o'ta yirik zarar darhol Jinoyat kodeksi bo'yicha jazolanadi." },
    { "id": "bpn77", "question": "Chiqindilarni yoqish (masalan ochiq havoda plastik va xinikatlarni yoqish) orqali havoni qasddan qattiq zaharlagan zavod egasi qanday turdagi jinoyat qilgan bo'ladi?", "options": ["Mayda xatogi", "Ekologik jinoyat (Atmosfera havosini ifloslantirish) sanaladi, bu nafaqat moddiy, balki ekotizimga o'ta katta zarar sifatida og'ir jazoga loyiq topiladi", "Soliq jinoyati"], "answer_index": 1, "explanation": "To'g'ri! Havoni zaharli tutun bilan zaharlash minglab aholining sog'ligiga tajovuz sanaladi." },
    { "id": "bpn78", "question": "Davlat inspektori ekologik holatni tekshirish maqsadida korxonaga borganida korxona uni kiritmaslikka va monitoring o'tkazishga qarshilik qilsa (MJtK 197-6)...", "options": ["Korxona haqli", "Mansabdor shaxslarga Ekologiya organlarining qonuniy faoliyatiga to'sqinlik qilgani uchun yirik jarima solinadi", "Prokurorga aytadi"], "answer_index": 1, "explanation": "To'g'ri! Davlat ekologiya nazorati idoralari xodimlari o'z vazifasini bajarayotgan vaqtda to'liq huquqiy himoya ostida bo'ladi." },
    { "id": "bpn79", "question": "O'zbekistonga yovvoyi hayvonlar (masalan arslon, sher) ni xususiy sirklarga yoki shaxsiy uylarda boqish uchun olib kirish shartlari qanday?", "options": ["Ruxsat yo'q", "Faqat Xalqaro SITES ruxsatnomasi va Davlat ekologiya vazirligining maxsus kvotasi, xavfsizlik shartlari asosidagina qat'iy nazoratda mumkin. Aks holda u kontrabanda hisoblanadi", "Istalgan payt mumkin"], "answer_index": 1, "explanation": "To'g'ri! Xavfli va yovvoyi hayvonlarni olib kirish, saqlash va ko'paytirish hukumatning maxsus va qat'iy qarorlari bilan tartibga olinadi." },
    { "id": "bpn80", "question": "Baliqlarni ko'paytirish maqsadida hovuzlarga suvning tartibsiz (me'yorsiz) olinishi natijasida tabiiy daryo qurib qolsa, hovuz egasiga chora ko'riladimi?", "options": ["Yo'q, u tadbirkor-ku", "Ha, suvdan maxsus foydalanish (suv olish limiti) qoidalarini buzgani uchun unga nisbatan ma'muriy chora ko'riladi va ortiqcha suv daryoga qaytariladi", "Suv hammaga tekin"], "answer_index": 1, "explanation": "To'g'ri! Suv resurslari davlat tasarrufida va faqat belgilangan kvota (limit) va ruxsatnoma asosida ishlatilishi qat'iy talabdir." }
]
"@

$newTrueFalseStr = @"
[
    { "id": "btf61", "question": "Eko-qopchiqlar (Mato yoki qog'oz xaltalar) har doim, har qanday holatda ham plastik paketlardan ko'ra tabiat uchun ming barobar bezarar va foydalidir.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Bitta mato qopchiqni ishlab chiqarish uchun sarflanadigan suv va energiya yuzlab plastik paketlar energiyasidan ko'p. Mato qopchiq ekologik toza bo'lishi uchun uni yillar davomida (kamida yuz marta) qayta ishlatish kerak." },
    { "id": "btf62", "question": "Qushlarning tuxum qo'yadigan vaqtida (bahorda) o'rmonda baland ovozda musiqa qo'yish ularning ko'payishiga salbiy ta'sir ko'rsatmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Akustik (shovqin) ifloslanish qushlarning urchish va jo'jalarini oziqlantirish ritmini buzadi, ular uyalarini tashlab qochishiga sabab bo'ladi." },
    { "id": "btf63", "question": "Elektromobillarning ekologiyaga foydasi bo'lishi uchun ularning akkumulyatorlari eskirganda qayta ishlanishi (utilizatsiya qilinishi) mutlaqo shart.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Litiy-ionli akkumulyatorlar zaharli elementlarga boy. Agar ular axlatga tashlansa, benzinli mashinadan ham yomonroq ekologik halokat keltirib chiqaradi." },
    { "id": "btf64", "question": "Barcha qo'ziqorinlar (zamburug'lar) faqat o'simlik hisoblanadi va ular fotosintez qila oladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Zamburug'lar butunlay alohida podshohlik bo'lib, ularda xlorofill yo'q (fotosintez qilmaydi). Ular tabiatdagi eng kuchli parchalovchilardir." },
    { "id": "btf65", "question": "Suv sathi tushib ketgan dengiz (masalan, Orol) o'rniga yuz minglab gektar saksovulzorlar ekilishi sho'r qum bo'ronlarining oldini olishdagi yagona amaliy choradir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Saksovullar va qandim kabi cho'l o'simliklari kuchli ildiz tizimi orqali millionlab tonna zaharli changni yerda ushlab turadi." },
    { "id": "btf66", "question": "Zamonaviy issiqlik elektr stansiyalari (IES) osmonga chiqaradigan oq rangli \"tutun\" aslida tutun emas, asosan suv bug'idir va u zaharli emas.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Agar IES zamonaviy gaz turbinalarida ishlasa va tozalash tizimi joyida bo'lsa, sovuq havoda ko'rinadigan oppoq bug' ko'pincha sovutish minoralaridan chiquvchi zararsiz suv bug'idir (ammo umuman zararsiz deyish xato, CO2 bo'ladi)." },
    { "id": "btf67", "question": "O'zbekistonda fuqarolar tomonidan ko'chalarda yoki bog'larda o'zboshimchalik bilan daraxt ko'chatlari ekish qonun bilan taqiqlangan.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Aksincha, \"Yashil makon\" umummilliy harakati va qonunchilik fuqarolarning ko'kalamzorlashtirish ishlaridagi ixtiyoriy ishtirokini qo'llab-quvvatlaydi." },
    { "id": "btf68", "question": "Baliq ovida to'rdan ko'zlari juda mayda (kichik) bo'lganidan foydalanish ekologiya uchun foydalidir, chunki faqat mayda baliqlar ushlanadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Mayda ko'zli to'r yosh baliqchalar va chavoqlarni tutib olib, ularning ko'payib ulg'ayishiga yo'l qo'ymaydi va populyatsiyani qirib yuboradi." },
    { "id": "btf69", "question": "Uyda ovqat qoldiqlaridan (masalan, kartoshka po'stlog'i, tuxum po'chog'i) kompost (tabiiy o'g'it) tayyorlash chiqindilarni kamaytirishning eng oqilona usullaridan biridir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Organik qoldiqlarni axlatxonaga yubormay kompost qilish tuproqni boyitadi va metan gazi chiqishini oldini oladi." },
    { "id": "btf70", "question": "Dunyo okeani suvlari o'ziga katta miqdorda karbonat angidrid (CO2) ni yutib olganligi sababli, uning kislotalilik darajasi oshib bormoqda (Ocean acidification).", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Karbonat suv bilan birikib kislota hosil qilmoqda. Bu narsa okeandagi mollyuskalar va marjon qoyalarining qisqich va chig'anoqlarini yemirib yubormoqda." },
    { "id": "btf71", "question": "To'qayzorlar (daryo bo'yidagi chakalakzor o'rmonlar) cho'l hududlarida daryo suvi bug'lanib ketmasligini ta'minlovchi tabiiy 'soyabon' vazifasini bajaradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! To'qaylar nafaqat hayvonlar makoni, balki daryoning namligini va suv muvozanatini saqlab turuvchi eng muhim ekotizimdir." },
    { "id": "btf72", "question": "Dunyodagi eng ko'p energiya tejamkor texnologiyalar asosan qashshoq va rivojlanmagan davlatlarda ishlab chiqariladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Eng kuchli energiya tejamkor va yashil (Green) texnologiyalar aksincha eng rivojlangan (masalan Yaponiya, Yevropa) davlatlarda ixtiro qilinib qo'llanilmoqda." },
    { "id": "btf73", "question": "Tunda chiroqlarni ortiqcha yorqin qilib yoqib qo'yish (Yorug'lik ifloslanishi - Light pollution) qushlarning migratsiyasini va hasharotlarning ritmini mutlaqo buzib yuboradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Sun'iy yorug'lik tungi hayvonlarni yo'ldan adashtiradi, ularning ko'payish va ov qilish tizimini ishdan chiqaradi." },
    { "id": "btf74", "question": "Tuproqqa sepilgan har qanday kimyoviy o'g'it yomg'ir suvi orqali yuvilib, oxir oqibat yer osti (sizot) suvlari va daryolarga yetib boradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Shuning uchun qishloq xo'jaligida zaharlarni me'yoridan ortiq ishlatish ko'rinmas ekologik zanjir bo'ylab ichimlik suvlarini ham ifloslantiradi." },
    { "id": "btf75", "question": "Qurilish materiallari orasida asbest va uning qoldiqlari tabiat va inson salomatligi uchun mutlaqo zararsiz hisoblanadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Asbest (ayniqsa, shifer changi) xalqaro sog'liqni saqlash tashkilotlari tomonidan saraton (rak) keltirib chiqaruvchi o'ta xavfli materiallar qatoriga kiritilgan." },
    { "id": "btf76", "question": "Tog' yonbag'irlaridagi yaylovlarda qo'y va echkilarni me'yoridan ortiq boqish (haddan ortiq o'tlatish) sel va yer ko'chkilarining xavfini keskin oshiradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Hayvonlar tuproqni ushlab turuvchi ildizlarni yeb yuboradi va tuyoqlari bilan yerni qazib yuboradi, oqibatda tuproq yuvilib ketishga oson bo'lib qoladi." },
    { "id": "btf77", "question": "Yer sharining magnit maydoni (Magnitosfera) bo'lmaganda edi, sayyoradagi barcha tiriklik Quyosh radiatsiyasi (Quyosh shamollari) tomonidan yo'q qilingan bo'lar edi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Magnit qutblari Yerni kosmik radiatsiyadan qutqarib turadigan eng muhim jismoniy 'qalqon' hisoblanadi." },
    { "id": "btf78", "question": "Biror mintaqada bir necha kun davomida yomg'ir yog'may qurg'oqchilik bo'lishini iqlim o'zgarishi deb atash to'g'ri bo'ladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Bir necha kunlik o'zgarish bu oddiy ob-havo o'zgarishi. Iqlim o'zgarishi deganda kamida 30 yillik o'rtacha ko'rsatkichlarning keskin burilishi tushuniladi." },
    { "id": "btf79", "question": "Agar dunyo okeanidagi butun muzliklar erib ketsa, bu hodisa nafaqat suv sathini ko'taradi, balki Dunyo okeani oqimlarini (masalan Golfstrimni) o'zgartirib, ayrim qit'alarda dahshatli sovuqqa sabab bo'lishi mumkin.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Chuchuk muz suvlarining okeanga qo'shilishi iliq oqimlarni to'xtatib qo'yishi va Yevropada xuddi 'Kichik muzlik davri'ni keltirib chiqarishi ilmiy tasdiqlangan ssenariydir." },
    { "id": "btf80", "question": "Hozirgi kunda O'zbekistonda ekologiya, tabiatni muhofaza qilish, hayvonot va o'simlik dunyosiga zarar yetkazganlik uchun jinoiy va ma'muriy jazolar umuman mavjud emas va hech kim jazolanmayapti.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Hozirgi kunda O'zbekiston qonunchiligida ekologik qoidabuzarliklarga (brakonyerlik, daraxt kesish) qarshi jazolar va jarimalar keskin kuchaytirilgan (karratiga oshirilgan) va doimiy qo'llanilmoqda." }
]
"@

$newQ = ConvertFrom-Json -InputObject $newQuizzesStr
$newP = ConvertFrom-Json -InputObject $newPuzzlesStr
$newT = ConvertFrom-Json -InputObject $newTermsStr
$newPn = ConvertFrom-Json -InputObject $newPenaltiesStr
$newTf = ConvertFrom-Json -InputObject $newTrueFalseStr

$jsonObj.quizzes += $newQ
$jsonObj.puzzles += $newP
$jsonObj.terms += $newT
$jsonObj.penalties += $newPn
$jsonObj.truefalse += $newTf

$jsonObj | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonFile -Encoding UTF8
