import json
import os

file_path = './data/quiz.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

new_quizzes = [
    { 'id': 'bq1', 'question': '«Ekologiya» atamasini fanga birinchi bo\\'lib kim kiritgan?', 'options': ['V.I. Vernadskiy', 'Ernst Gekkel', 'Eduard Zyuss', 'Charlz Darvin'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Nemis olimi E. Gekkel 1866 yilda «Organizmlarning umumiy morfologiyasi» asarida bu atamani fanga kiritgan.' },
    { 'id': 'bq2', 'question': '«Biosfera» (hayot qobig\\'i) atamasini ilk bor qaysi olim ishlatgan?', 'options': ['A. Tensli', 'V.N. Sukachev', 'Eduard Zyuss', 'J.B. Lamark'], 'answer_index': 2, 'explanation': 'To\\'g\\'ri! Avstriyalik geolog E. Zyuss 1875 yilda bu atamani fanga kiritgan.' },
    { 'id': 'bq3', 'question': 'Namlikka ehtiyoji bo\\'yicha qurg\\'oqchil sharoitda yashashga moslashgan organizmlar qanday ataladi?', 'options': ['Gidrofillar', 'Kserofillar', 'Mezofillar', 'Termofillar'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Kserofillar namligi kam yoki juda kam bo\\'lgan qurg\\'oqchil sharoitga moslashgan.' },
    { 'id': 'bq4', 'question': 'Issiqsevar organizmlar ekologiyada qanday nomlanadi?', 'options': ['Kriofillar', 'Fotofillar', 'Termofillar', 'Gidrobiontlar'], 'answer_index': 2, 'explanation': 'To\\'g\\'ri! Termofillar - issiqsevar organizmlar hisoblanadi.' },
    { 'id': 'bq5', 'question': 'BMTning atrof-muhit bo\\'yicha dasturi (YUNEP) qachon va qayerda tashkil etilgan?', 'options': ['1972 yil, Stokgolm', '1992 yil, Rio-de-Janeyro', '1948 yil, Parij', '1997 yil, Kioto'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! YUNEP 1972 yilda Stokgolm anjumanida tashkil qilingan.' },
    { 'id': 'bq6', 'question': 'O\\'zbekistondagi eng yirik tog\\'-o\\'rmon davlat qo\\'riqxonasi qaysi?', 'options': ['Nurota qo\\'riqxonasi', 'Hisor qo\\'riqxonasi', 'Zarafshon qo\\'riqxonasi', 'Chotqol qo\\'riqxonasi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Hisor qo\\'riqxonasi (80986 gektar) respublikadagi eng yirik qo\\'riqxona hisoblanadi.' },
    { 'id': 'bq7', 'question': 'Ekologik piramida qoidasini kim ishlab chiqqan?', 'options': ['R. Lindeman', 'Ch. Elton', 'V. Dokuchayev', 'K. Myobius'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Ingliz zoologi Ch. Elton 1927 yilda ekologik piramida modelini ishlab chiqqan.' },
    { 'id': 'bq8', 'question': 'Qaysi xalqaro tashkilot Qizil kitobni yaratish tashabbuskori bo\\'lgan?', 'options': ['YUNESKO', 'GRINPISS', 'MSOP (Tabiatni muhofaza qilish xalqaro ittifoqi)', 'VOZ'], 'answer_index': 2, 'explanation': 'To\\'g\\'ri! Qizil kitobni yaratish MSOP (IUCN) tomonidan ilgari surilgan.' },
    { 'id': 'bq9', 'question': 'Ozon (O3) gazini 1839-yilda kashf qilgan nemis kimyogari kim?', 'options': ['Shenbeyn', 'Gartli', 'Fur\\'e', 'Arrhenius'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Shenbeyn ozon gazini kashf qilgan.' },
    { 'id': 'bq10', 'question': 'Insoniyat tarixidagi ekologik tangliklardan biri «konsumentlar tangligi» nimadan kelib chiqqan?', 'options': ['Zavodlar qurilishidan', 'Hayvonlarning haddan ziyod ovlanishidan', 'O\\'rmon yong\\'inlaridan', 'Global isishdan'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Bundan 10-50 ming yil ilgari hayvonlarni haddan ziyod ovlash oqibatida ocharchilik kelib chiqqan.' }
]

new_puzzles = [
    { 'id': 'bp1', 'story': 'Zavod atrofidagi daraxtlarning barglari sarg\\'ayib, quriy boshladi. Shu bilan birga bu hududda kislotali yomg\\'ir yog\\'ishi kuzatildi.', 'question': 'Havoga qaysi gaz ko\\'p chiqarilmoqda?', 'options': ['Kislorod', 'Oltingugurt angidridi va azot oksidlari', 'Metan gazi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Sanoatdan chiqadigan oltingugurt va azot oksidlari havodagi namlik bilan birikib, kislotali yomg\\'irni hosil qiladi.' },
    { 'id': 'bp2', 'story': 'Chigirtkalar dalaga hujum qildi. Dehqon ularni yo\\'qotish uchun kuchli zahar (pestisid) sepdi. Chigirtkalar o\\'ldi, lekin ko\\'p o\\'tmay dalada sichqonlar ko\\'payib ketdi.', 'question': 'Nega sichqonlar ko\\'paydi?', 'options': ['Zahar sichqonlarni ko\\'payishiga olib keladi', 'Zahar sichqonlarni yeydigan yirtqich qushlarni ham o\\'ldirgan', 'Sichqonlar chigirtkani yeydi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Pestisidlar ozuqa zanjiri orqali yirtqich qushlarni halok qilgan, oqibatda ularning o\\'ljasi bo\\'lgan sichqonlar nazoratsiz ko\\'paygan.' },
    { 'id': 'bp3', 'story': 'Ko\\'lga sanoat korxonasi issiq suv (oqova) tashlamoqda. Suvda yashil suvo\\'tlar tez ko\\'payib, suv hidlandi va baliqlar o\\'la boshladi.', 'question': 'Bu ekologik hodisa nima deyiladi?', 'options': ['Suksessiya', 'Evtrofikatsiya', 'Degradatsiya'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Evtrofikatsiya - suv havzalarining biogen moddalar (yoki issiqlik) ta\\'sirida "gullashi" va kislorod yetishmay qolishi.' },
    { 'id': 'bp4', 'story': 'Odamlar chiroyli gul deb Qizil kitobga kiritilgan lolalarni (masalan, Butkov lolasi) tog\\'dan ko\\'plab uzib kela boshlashdi.', 'question': 'Buning ekologik oqibati nima bo\\'ladi?', 'options': ['Lola ko\\'payadi', 'Bu turning butunlay qirilib ketishiga va genofond yo\\'qolishiga olib keladi', 'Hech narsa o\\'zgarmaydi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Qizil kitobdagi o\\'simliklarni uzish ularning tabiiy zaxirasi tugashiga olib keladi.' },
    { 'id': 'bp5', 'story': 'Shaharda avtomobillar soni keskin ortdi. Issiq va shamolsiz kunda havoda qalin zaharli tuman hosil bo\\'ldi.', 'question': 'Bu holat fanda qanday ataladi?', 'options': ['Fotokimyoviy smog', 'Ozon tuynugi', 'Aerozol'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Avtomobil gazlari quyosh nuri ta\\'sirida fotokimyoviy smogni (zaharli tumanni) hosil qiladi.' },
    { 'id': 'bp6', 'story': 'Bir davlat qishloq xo\\'jaligida zaharli DDT moddasidan foydalanishni taqiqladi, ammo uzoq Antarktidadagi pingvinlar qonida shu modda topildi.', 'question': 'Bu qanday yuz bergan?', 'options': ['Pingvinlar o\\'sha davlatga borgan', 'Zaharli moddalar ozuqa zanjiri va gidrosfera orqali butun biosferaga tarqaladi', 'Olimlar adashgan'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Tabiatda hamma narsa o\\'zaro bog\\'liq. Ksenobiotiklar suv va havo orqali uzoq masofalarga ko\\'chadi.' },
    { 'id': 'bp7', 'story': 'Ovchilar o\\'rmondagi barcha bo\\'rilarni qirib tashlashdi. Boshida bug\\'ular soni ko\\'paydi, ammo keyin ular orasida kasallik tarqalib, ommaviy qirila boshladi.', 'question': 'Bo\\'rilarning ekotizimdagi o\\'rni nimada edi?', 'options': ['Ular tabiat sanitarlari bo\\'lib, asosan kasal hayvonlarni yegan', 'Ular bug\\'ularga ozuqa olib kelgan', 'Bo\\'rilar viruslarni o\\'ldirgan'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Yirtqichlar (bo\\'rilar) populyatsiyani zaif va kasal individlardan tozalab, yuqumli kasalliklar tarqalishining oldini oladi.' },
    { 'id': 'bp8', 'story': 'Dehqon yerni har yili bir xil chuqurlikda haydab, faqat paxta ekaverdi. Natijada tuproq unumdorligi pasayib ketdi.', 'question': 'U qanday ekologik qoidaga amal qilmadi?', 'options': ['Sun\\'iy o\\'g\\'it solmadi', 'Almashlab ekish (monokulturadan qochish) qoidasiga', 'Suvni tejash qoidasiga'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Faqat bitta ekinni (monokultura) ekaverish tuproqning ozuqa moddalarini so\\'rib oladi.' },
    { 'id': 'bp9', 'story': 'Qor Kaplanini (Ilvirs) terisi uchun ovlash ko\\'paydi va u kamayib ketdi.', 'question': 'Buning oqibatida tog\\'larda qaysi hayvonlar nazoratsiz ko\\'payib ketadi?', 'options': ['Tog\\' echkilari va yovvoyi tuyoqlilar', 'Burgutlar', 'Kemiruvchilar'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Yirtqich kamaysa, uning o\\'ljasi bo\\'lgan o\\'txo\\'rlar soni keskin ortib, o\\'simliklarni payhon qiladi.' },
    { 'id': 'bp10', 'story': 'Daryo bo\\'yidagi qalin to\\'qayzorlar kesib yuborildi. Natijada daryo suvi yozda tez qurib qoladigan bo\\'ldi.', 'question': 'Buning sababi nima?', 'options': ['Quyosh ko\\'proq isita boshladi', 'Daraxtlar namlikni saqlab, suv bug\\'lanishini kamaytirar va mikroiqlimni mo\\'tadillashtirar edi', 'Yomg\\'ir kam yog\\'di'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! To\\'qayzorlar daryo suvi bug\\'lanib ketishidan saqlovchi tabiiy qalqondir.' }
]

new_terms = [
    { 'id': 'bt1', 'question': 'Autekologiya nima?', 'options': ['Populyatsiyalar ekologiyasi', 'Alohida olingan organizmni atrof-muhit bilan aloqasini o\\'rganuvchi bo\\'lim', 'Faqat o\\'simliklarni o\\'rganadi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Autekologiya (yoki faktorial ekologiya) alohida organizmning muhitga moslashuvini o\\'rganadi.' },
    { 'id': 'bt2', 'question': 'Sinekologiya nima?', 'options': ['Populyatsiyalar ekologiyasi', 'Odam ekologiyasi', 'Biotsenozlar ekologiyasi'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Sinekologiya populyatsiyalarning shakllanishi va dinamikasini o\\'rganadi.' },
    { 'id': 'bt3', 'question': 'Abiotik omillar nimalar?', 'options': ['Tirik organizmlar', 'Jonsiz tabiat omillari (harorat, namlik, yorug\\'lik)', 'Odam faoliyati'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Abiotik omillarga iqlim, tuproq, suv va relief xususiyatlari kiradi.' },
    { 'id': 'bt4', 'question': 'Antropogen omil nima?', 'options': ['Hayvonlarning tabiatga ta\\'siri', 'Inson faoliyati bilan bog\\'liq ta\\'sirlar', 'Kosmik ta\\'sirlar'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Insonning xo\\'jalik faoliyati orqali tabiatga ko\\'rsatadigan ta\\'siri antropogen omil deyiladi.' },
    { 'id': 'bt5', 'question': 'Evribiontlar nima?', 'options': ['Faqat sovuqda yashovchilar', 'Muhit sharoitlarining katta o\\'zgarishlariga chiday oladigan organizmlar', 'Suv tubida yashovchilar'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Ekologik valentligi keng bo\\'lgan organizmlar evribiontlar deyiladi.' },
    { 'id': 'bt6', 'question': 'Stenobiontlar nima?', 'options': ['Ma\\'lum bir xil tor sharoitdagina yashay oladigan organizmlar', 'Qurg\\'oqchilikka chidamli o\\'simliklar', 'Barcha hududlarda tarqalgan hayvonlar'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Stenobiontlar muhitning o\\'zgarishiga juda ta\\'sirchan bo\\'ladi.' },
    { 'id': 'bt7', 'question': 'Nektonlar nima?', 'options': ['Suv oqimi bo\\'ylab suzuvchi o\\'simliklar', 'Suvda o\\'z muskullari yordamida faol va uzoqqa suzuvchi organizmlar (baliqlar, kitlar)', 'Suv tubi organizmlari'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Nektonlar suvda erkin harakatlanuvchi yirik organizmlardir.' },
    { 'id': 'bt8', 'question': 'Bentos nima?', 'options': ['Suv yuzasida qalqib yuruvchilar', 'Suv havzasi tubida, tuproqqa yopishib yoki o\\'rmalab yashovchi organizmlar', 'Havoda uchuvchilar'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Bental organizmlar daryo va okeanlarning tagida yashaydi.' },
    { 'id': 'bt9', 'question': 'Suksessiya nima?', 'options': ['Hayvonlarning migratsiyasi', 'Bir biotsenozning boshqasi bilan ma\\'lum tartibda birin-ketin almashinishi', 'Daraxtlarning qurishi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Masalan, qurib qolgan ko\\'l o\\'rnida botqoqlik, keyin esa o\\'rmon hosil bo\\'lishi suksessiyadir.' },
    { 'id': 'bt10', 'question': 'Endemik turlar nima?', 'options': ['Butun dunyoda tarqalgan turlar', 'Faqat ma\\'lum bir kichik geografik hududda yashab, boshqa joylarda uchramaydigan turlar', 'Qirilib ketgan turlar'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Masalan, O\\'zbekistondagi ayrim lolalar faqat aniq bir tog\\'da o\\'sadi.' }
]

new_penalties = [
    { 'id': 'bpn1', 'question': 'O\\'zbekiston Respublikasining "Chiqindilar to\\'g\\'risida"gi qonuni qachon qabul qilingan?', 'options': ['1992 yil', '2002 yil 5 aprel', '2010 yil'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Ushbu qonun chiqindilar bilan bog\\'liq munosabatlarni tartibga soladi.' },
    { 'id': 'bpn2', 'question': '"Ekologik ekspertiza to\\'g\\'risida"gi qonun qachon qabul qilingan?', 'options': ['2000 yil 25 may', '1995 yil', '2005 yil'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! Bu qonun loyihalarning ekologik xavfsizligini ta\\'minlashga qaratilgan.' },
    { 'id': 'bpn3', 'question': 'Ekologik ekspertizasiz (ruxsatsiz) boshlangan yirik qurilish obyekti qanday jazolanadi? (MJtK 96-modda)', 'options': ['Faqat ogohlantirish', 'Faoliyati to\\'xtatiladi va ma\\'muriy jarimaga tortiladi', 'Jarima to\\'lab, qurishni davom ettiradi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Ekologik xavfsizlikni ta\\'minlamagan qurilishlar to\\'xtatilishi shart.' },
    { 'id': 'bpn4', 'question': 'Yovvoyi hayvonlarni asrash maqsadida ov qoidalari buzilganda (MJtK 90-modda), ovchidan nima undiriladi?', 'options': ['Faqat jarima', 'Quroli musodara qilinadi va katta jarima solinadi', 'Ruxsatnomasi uzaytiriladi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Noqonuniy ov qurollari majburiy tartibda davlat foydasiga musodara qilinadi.' },
    { 'id': 'bpn5', 'question': 'Kanserogen va teratogen moddalar atrof muhitga tarqalganda qanday holat yuz beradi?', 'options': ['Daraxtlar ko\\'karmaydi', 'Insonlarda rak kasalliklari va naslning majruhligi (mutatsiya) yuzaga keladi', 'Ozon tuynugi kattalashadi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Bu zaharli moddalar bevosita inson genetikasiga salbiy ta\\'sir ko\\'rsatadi.' },
    { 'id': 'bpn6', 'question': 'Qizil kitobga kirgan noyob turlarni chet elga sotish qaysi xalqaro konvensiya bilan taqiqlangan?', 'options': ['SITES (Vashington Konvensiyasi)', 'Kioto bayonnomasi', 'Ramsar konvensiyasi'], 'answer_index': 0, 'explanation': 'To\\'g\\'ri! SITES konvensiyasi kamyob hayvon va o\\'simliklar bilan savdo qilishni cheklaydi.' },
    { 'id': 'bpn7', 'question': 'Freonlar (Xlorftoruglerodlar) ishlab chiqarish va ishlatish nima uchun xalqaro darajada cheklangan?', 'options': ['Ular zaharli hidga ega', 'Ular Ozon qatlamini yemirib, ultrabinafsha nurlar xavfini oshiradi', 'Ular qimmat turadi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Monreal bayonnomasi aynan ozonni emiruvchi moddalarni kamaytirishga qaratilgan.' },
    { 'id': 'bpn8', 'question': 'Atmosferani sanoat chiqindilaridan ifloslantirganlik uchun "ifloslantiruvchi to\\'laydi" prinsipi nima?', 'options': ['Davlat korxona zarariga pul to\\'laydi', 'Korxona tabiatga yetkazgan zarari uchun iqtisodiy soliq (jarima) to\\'laydi', 'Odamlar o\\'zi tozalaydi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Bu ekologiya iqtisodiyotining asosiy rag\\'batlantiruvchi va jazolovchi mexanizmidir.' },
    { 'id': 'bpn9', 'question': 'Ko\\'p qavatli uy hovlisida yoki ko\\'chada daraxtni o\\'zboshimchalik bilan kesgan fuqaro jazolanadimi?', 'options': ['Yo\\'q, o\\'zi ekkan bo\\'lsa kesishi mumkin', 'Ha, moratoriy va qonun talablari bo\\'yicha katta miqdorda jarima to\\'laydi', 'Faqat tushuntirish ishlari olib boriladi'], 'answer_index': 1, 'explanation': 'To\\'g\\'ri! Jamoat joylaridagi barcha daraxtlar davlat muhofazasidadir.' },
    { 'id': 'bpn10', 'question': 'Daryolarni o\\'zboshimchalik bilan to\\'sib, suv ob\\'ektlaridan noqonuniy foydalanganlik uchun kim javobgar?', 'options': ['Barcha aholi', 'Faqat Ekologiya vazirligi', 'Qoidabuzar fuqaro yoki mansabdor shaxs'], 'answer_index': 2, 'explanation': 'To\\'g\\'ri! Suv resurslaridan qonunga xilof foydalanish uchun shaxsan javobgarlik mavjud.' }
]

new_truefalse = [
    { 'id': 'btf1', 'question': 'O\\'zbekiston 1995 yildan Biologik xilma-xillik Konvensiyasining a\\'zosidir.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 0, 'explanation': 'Rost! O\\'zbekiston bioxilma-xillikni saqlash bo\\'yicha xalqaro majburiyatlarni olgan.' },
    { 'id': 'btf2', 'question': 'Tabiatda mutlaq foydali yoki mutlaq zararli hayvon mavjud.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 1, 'explanation': 'Yolg\\'on! Tabiatda mutlaq tushunchasi yo\\'q, har bir organizm ma\\'lum bir ekotizim uchun o\\'z o\\'rniga ega.' },
    { 'id': 'btf3', 'question': 'B. Kommonerning 1-qonuni "Barchasi o\\'zaro bog\\'liq" deb ataladi.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 0, 'explanation': 'Rost! Tabiatda yagona tarmoq shakllangan.' },
    { 'id': 'btf4', 'question': 'Biosfera faqatgina o\\'simliklar va hayvonlardan iborat, odam unga kirmaydi.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 1, 'explanation': 'Yolg\\'on! Inson ham biosferaning, aniqrog\\'i "Noosfera" (aql sferasi)ning ajralmas qismidir.' },
    { 'id': 'btf5', 'question': 'Litosfera - bu yerning qattiq qobig\\'i (tuproq va tog\\' jinslari) hisoblanadi.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 0, 'explanation': 'Rost! Hayot asosan litosferaning ustki qatlamida mujassamlashgan.' },
    { 'id': 'btf6', 'question': 'Gidrosfera (suv qobig\\'i) Yer yuzining atigi 30% ini egallaydi.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 1, 'explanation': 'Yolg\\'on! Gidrosfera Yer yuzining 71% ga yaqin qismini egallaydi.' },
    { 'id': 'btf7', 'question': 'Odam organizmining taxminan 60-70% i suvdan iborat.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 0, 'explanation': 'Rost! Shuning uchun ham inson hayotini suvsiz tasavvur qilib bo\\'lmaydi.' },
    { 'id': 'btf8', 'question': 'Ekologiya faniga "biosfera" atamasini rus olimi V.I. Vernadskiy birinchi bo\\'lib kiritgan.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 1, 'explanation': 'Yolg\\'on! Bu atamani ilk bor 1875-yilda avstriyalik Eduard Zyuss kiritgan. Vernadskiy esa uning ta\\'limotini yaratgan.' },
    { 'id': 'btf9', 'question': 'Ozon pardasi quyoshdan kelayotgan zararli ultrabinafsha nurlarni ushlab qoladi.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 0, 'explanation': 'Rost! Agar bu parda bo\\'lmasa, Yerdagi barcha tiriklik halok bo\\'lar edi.' },
    { 'id': 'btf10', 'question': 'Yashil o\\'simliklar fotosintez jarayonida havadan kislorod yutib, karbonat angidrid chiqaradi.', 'options': ['Rost', 'Yolg\\'on'], 'answer_index': 1, 'explanation': 'Yolg\\'on! Aksincha, ular karbonat angidridni yutib, biz nafas oladigan erkin kislorodni chiqaradi.' }
]

data['quizzes'].extend(new_quizzes)
data['puzzles'].extend(new_puzzles)
data['terms'].extend(new_terms)
data['penalties'].extend(new_penalties)
data['truefalse'].extend(new_truefalse)

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
