$ErrorActionPreference = "Stop"

$jsonFile = "C:\Users\Akobir\.gemini\antigravity\scratch\eco_law_bot\data\quiz.json"
$jsonStr = Get-Content -Raw -Path $jsonFile -Encoding UTF8
$jsonObj = ConvertFrom-Json -InputObject $jsonStr

$newQuizzesStr = @"
[
    { "id": "bq41", "question": "Gidrosferaning yerdagi iqlimni shakllantirishdagi asosiy roli nima?", "options": ["Faqat yomg'ir yog'diradi", "Quyosh issiqligini yutib va to'plab, haroratni mo'tadillashtiradi (Yerni haddan tashqari isib va sovib ketishdan asraydi)", "Shamollarni yo'q qiladi", "Faqat muzlaydi"], "answer_index": 1, "explanation": "To'g'ri! Dunyo okeani sayyoraning 'termoregulyatori' (harorat sozlagichi) hisoblanib, issiqlikni butun Yer shariga bir tekis tarqatadi." },
    { "id": "bq42", "question": "O'zbekistonda eng kam tarqalgan ekotizim qaysi?", "options": ["Cho'l", "Tog'", "To'qayzorlar", "Yaylovlar"], "answer_index": 2, "explanation": "To'g'ri! Daryo qirg'oqlaridagi to'qayzor o'rmonlar (To'qay ekotizimlari) inson ta'siri va suv kamayishi tufayli keskin qisqarib ketgan va eng kam tarqalgan." },
    { "id": "bq43", "question": "Qaysi qush turi O'zbekiston tog'larida uchrovchi eng yirik yirtqich qush (sanitar) hisoblanadi?", "options": ["Oqqush", "Qora tasqara", "Lochin", "Chug'urchiq"], "answer_index": 1, "explanation": "To'g'ri! Qora tasqara va boshqa yirik o'laksaxo'r qushlar tabiat sanitarlari bo'lib, ular Qizil kitobga kiritilgan." },
    { "id": "bq44", "question": "Fotosintez jarayonining teskarisi nima?", "options": ["Xemosintez", "Nafas olish", "Transpiratsiya", "Mutatsiya"], "answer_index": 1, "explanation": "To'g'ri! Nafas olish fotosintezning teskarisi bo'lib, unda kislorod yutiladi, organik modda parchalanib energiya va SO2 ajraladi." },
    { "id": "bq45", "question": "Insonlarning suvga munosabatidagi 'Suv izi' (Water footprint) nima?", "options": ["Suvdagi izlar", "Bir kishi yoki davlat tomonidan kundalik hayot va mahsulotlar yaratish uchun sarflanadigan chuchuk suvning umumiy hajmi", "Suvning to'lqinlanishi", "Suv sathi"], "answer_index": 1, "explanation": "To'g'ri! Masalan, 1 ta paxtali futbolka tayyorlash uchun 2500 litrdan ortiq (suv izi) suv sarflanadi." },
    { "id": "bq46", "question": "Tuproq tarkibida organik moddalar va gumus (chirindi) ko'p bo'lsa tuproq qanday nomlanadi?", "options": ["Sho'rxok", "Qoratuproq", "Qumli", "Toshloq"], "answer_index": 1, "explanation": "To'g'ri! Qoratuproqlar (chernozyom) eng unumdor va gumusga boy tuproqlar hisoblanadi." },
    { "id": "bq47", "question": "Suv tubidagi baliqlar nafas olishi uchun suvda qanday holat bo'lishi kerak?", "options": ["Suv issiq bo'lishi", "Suv sho'r bo'lishi", "Suvda erigan kislorod bo'lishi", "Suv tinch bo'lishi"], "answer_index": 2, "explanation": "To'g'ri! Suv hayvonlari suv molekulasidagi (H2O) kisloroddan emas, balki suvda erigan erkin kisloroddan nafas oladi." },
    { "id": "bq48", "question": "Biosferaning chegaralari qayerdan o'tadi?", "options": ["Faqat quruqlik", "Atmosferaning ozon qatlamigacha, gidrosferaning eng chuqur joyigacha va litosferaning bir necha kilometr chuqurligigacha", "Faqat suvda", "Olam bo'ylab"], "answer_index": 1, "explanation": "To'g'ri! Hayot ozon ekranidan tortib, okean tubi va yer ostigacha tarqalgan." },
    { "id": "bq49", "question": "Pestisidlar asosan nima uchun ishlatiladi?", "options": ["Havo tozalash uchun", "O'simlik zararkunandalari va kasalliklariga qarshi kurashish uchun", "Daraxt kesish uchun", "Qurilishda"], "answer_index": 1, "explanation": "To'g'ri! Lekin ulardan noto'g'ri foydalanish tuproq va suvlarni qattiq zaharlaydi." },
    { "id": "bq50", "question": "Bir gektar o'rmon bir yilda taxminan qancha karbonat angidridni yutib, kislorod chiqaradi?", "options": ["1 tonna", "10-20 tonna", "Hech qancha", "500 tonna"], "answer_index": 1, "explanation": "To'g'ri! O'rmonlar eng kuchli karbonat yutqichlardir." },
    { "id": "bq51", "question": "Atrof muhitga inson ta'siri kuchayishi qanday davr deb atalmoqda?", "options": ["Muzlik davri", "Antroposen", "Yura davri", "Kembriy"], "answer_index": 1, "explanation": "To'g'ri! Antroposen – inson faoliyati Yer sayyorasi geologiyasi va ekotizimiga hal qiluvchi ta'sir ko'rsatayotgan hozirgi davr." },
    { "id": "bq52", "question": "Chuchuk suv zahirasining qariyb uchdan bir qismi (suyuq holdagi) qayerda joylashgan?", "options": ["Ko'llarda", "Yer osti suvlarida (artezian, sizot)", "Daryolarda", "O'simliklarda"], "answer_index": 1, "explanation": "To'g'ri! Yer osti suvlari insoniyat uchun o'ta muhim bo'lgan toza ichimlik suvi zaxirasidir." },
    { "id": "bq53", "question": "Ekologik iz (Ecological footprint) nima?", "options": ["Hayvonning izi", "Insonlarning iste'moli va chiqindilarni yutish uchun zarur bo'lgan tabiat maydoni o'lchovi", "Karbonat angidrid izi", "O'rmondagi yo'l"], "answer_index": 1, "explanation": "To'g'ri! Ekologik iz inson tabiatning qancha qismini \"yeb bitirayotganini\" hisoblaydigan xalqaro o'lchovdir." },
    { "id": "bq54", "question": "Orol dengizini qutqarish xalqaro jamg'armasi qachon tashkil qilingan?", "options": ["1960 yil", "1993 yil", "2010 yil", "2020 yil"], "answer_index": 1, "explanation": "To'g'ri! Markaziy Osiyo davlatlari rahbarlari tomonidan 1993-yilda tashkil etilgan." },
    { "id": "bq55", "question": "Iqlim isishini qaysi o'rtacha ko'rsatkichdan oshirmaslik bo'yicha Parij bitimi imzolangan?", "options": ["5 gradus", "1.5 - 2 gradus Selsiy", "10 gradus", "0 gradus"], "answer_index": 1, "explanation": "To'g'ri! Yer sayyorasi o'rtacha harorati sanoat davridagidan 1.5 - 2 gradusdan oshib ketsa, qaytarib bo'lmas halokatli jarayonlar boshlanadi." },
    { "id": "bq56", "question": "Eng kam chiqindi chiqaruvchi energiya manbai qaysi?", "options": ["Ko'mir yoqish", "Neft yoqish", "Quyosh va shamol energiyasi (Muqobil energiya)", "O'tin yoqish"], "answer_index": 2, "explanation": "To'g'ri! Muqobil va qayta tiklanuvchi energiya manbalari atrof muhitga zaharli gazlar chiqarmaydi." },
    { "id": "bq57", "question": "Agar dunyo okeanidagi barcha muzliklar erisa, dengiz sathi taxminan qanchaga ko'tarilishi mumkin?", "options": ["1 metr", "5-10 metr", "60 metrdan ortiq", "Hech qancha"], "answer_index": 2, "explanation": "To'g'ri! Bu esa minglab qirg'oq shaharlarini suv ostida qoldiradi." },
    { "id": "bq58", "question": "Dunyodagi eng ko'p turdagi jonzotlarni o'z ichiga oluvchi hayvonot klassi qaysi?", "options": ["Sut emizuvchilar", "Qushlar", "Hasharotlar", "Baliqlar"], "answer_index": 2, "explanation": "To'g'ri! Yer yuzida aniqlangan jonzotlarning milliondan ortiq turini hasharotlar tashkil qiladi." },
    { "id": "bq59", "question": "Yomg'ir chuvalchanglari tuproqqa qanday ta'sir qiladi?", "options": ["Zarar yetkazadi", "Tuproqni yumshatib, havoga to'yintiradi va unumdorligini oshiradi", "Ekin ildizini yeydi", "Ta'siri yo'q"], "answer_index": 1, "explanation": "To'g'ri! Darvin ularni \"tabiat shudgorchilari\" deb atagan, ular tuproq sifatini yaxshilashda beqiyos o'ringa ega." },
    { "id": "bq60", "question": "Zaharlarni mutlaqo parchalay olmaydigan muhit qaysi?", "options": ["Tuproq", "Daryo suvi", "Plastiklar o'zi va radioaktiv moddalar", "Havo"], "answer_index": 2, "explanation": "To'g'ri! Ayniqsa radioaktiv qoldiqlar yuz minglab yillar davomida nurlanish tarqatib yotadi va hech narsaga parchalanmaydi." }
]
"@

$newPuzzlesStr = @"
[
    { "id": "bp41", "story": "Odam uyi yonidan oqib o'tadigan anhorni (ariqni) tozalayman deb, ichidagi barcha mayda o't-o'lan, toshlar va loyni betonlab tashladi.", "question": "Ariq suvi endi avvalgidek toza bo'ladimi?", "options": ["Ha, yanada toza bo'ladi", "Yo'q, chunki suvni tozalovchi tabiiy biofiltrlar (o'tlar, mikroorganizmlar) beton sababli yo'q qilindi", "Farqi yo'q"], "answer_index": 1, "explanation": "To'g'ri! Tabiiy o'zanlar (to'qaylar, suv tubi qatlami) suvdagi zaharli moddalarni yutib tozalab beruvchi \"filtr\" vazifasini bajaradi." },
    { "id": "bp42", "story": "Katta fermada chorva mollarining tez va ko'p go'sht berishi uchun ularga doimiy antibiotiklar berildi.", "question": "Ushbu go'shtni iste'mol qilishning insoniyatga ekologik zarari nimada?", "options": ["Go'sht shirin bo'ladi", "Insonda antibiotiklarga chidamli (davolab bo'lmaydigan) bakteriyalar (superbakteriyalar) shakllanishiga olib keladi", "Hech qanday"], "answer_index": 1, "explanation": "To'g'ri! Qishloq xo'jaligida antibiotiklarning ortiqcha qo'llanilishi ekotizimda mutatsiya qilingan daxshatli bakteriyalarni yaratadi." },
    { "id": "bp43", "story": "Fermer dala chetidagi katta daraxtni uya qurayotgan mayna va chumchuqlarga achchiqlanib kesib tashladi.", "question": "Ekinzor endi xavfsizmi?", "options": ["Ha, endi tinchlik", "Yo'q, qushlar bo'lmagani uchun dalani zararkunanda hasharotlar bosadi", "Hosil 2 barobar oshadi"], "answer_index": 1, "explanation": "To'g'ri! Hasharotxo'r qushlar qishloq xo'jaligini minglab tonna zararkunandalardan tozalab beradigan asosiy do'stlardir." },
    { "id": "bp44", "story": "Shahar meriyasi ko'chalardagi barglarni to'kib tashlagan katta yoshli chinorlarni \"xunuk\" deb, ularning o'rniga doim yashil archalarni ekdi.", "question": "Bu ekologik to'g'ri yechimmi?", "options": ["Ha, archalar qishda ham yashil", "Yo'q, keng bargli daraxtlar (chinor) yozda qalin soya beradi, changni yutadi, archa esa buni qilolmaydi", "Ikkisi bir xil"], "answer_index": 1, "explanation": "To'g'ri! Issiq iqlimli shaharlarda keng bargli daraxtlarning kesilishi shahar haroratini (issiqlik orollari) oshirib yuboradi." },
    { "id": "bp45", "story": "Dehqon yerni haydashda (shudgorlashda) tuproqning ustki va ostki qatlamlarini aralashtirib emas, faqat ustidan tekislab haydadi (no-till usuli).", "question": "Bu usul foydalimi?", "options": ["Zararli, o'simlik o'smaydi", "Juda foydali! Bu tuproq eroziyasini oldini oladi, namlikni saqlaydi va uglerodni yerda ushlab qoladi", "Faqat pul tejaydi"], "answer_index": 1, "explanation": "To'g'ri! Yerni kamroq haydash zamonaviy \"iqlimga do'stona\" qishloq xo'jaligi usulidir (Conservation agriculture)." },
    { "id": "bp46", "story": "Tadqiqotchilar Antarktida qorlari tarkibida mikroplastik (juda mayda plastik zarralari) topishdi.", "question": "Antarktidada odamlar yo'q bo'lsa, plastik u yerga qanday bordi?", "options": ["Sayyohlar tashlab ketgan", "Mikroplastik zarralari shamol, bulutlar va dengiz oqimlari orqali minglab kilometrlarga ko'chib boradi", "Bunday bo'lishi mumkin emas"], "answer_index": 1, "explanation": "To'g'ri! Atmosfera sirkulyatsiyasi orqali zaharli moddalar va mayda plastmassa butun Yer sayyorasiga, hatto kimsasiz joylarga ham tarqaladi." },
    { "id": "bp47", "story": "Zavod havoni tozalash uchun qimmat filtr o'rnatdi. Tutun yo'qoldi, ammo endi zavod chiqindi qattiq qoldiqlarni (filtrga tushgan zaharlarni) yerga ko'mib kelmoqda.", "question": "Muammo hal bo'ldimi?", "options": ["Ha, havo tozalandi", "Yo'q, ifloslanish havodan tuproqqa va yer osti suvlariga o'tdi (muammo joyini o'zgartirdi xolos)", "Ha, yer hammasini yutadi"], "answer_index": 1, "explanation": "To'g'ri! Ekologik muammoni shunchaki boshqa sferega o'tkazish bilan hal qilib bo'lmaydi, qoldiqlarni mutlaq zararsizlantirish kerak." },
    { "id": "bp48", "story": "Uy bekasi uyni tozalash uchun juda kuchli kimyoviy tozalash vositalaridan (xlor, kislotalar) ko'p foydalandi, so'ng ularni rakovinaga to'kib yubordi.", "question": "Bu zaharli suv qayerga boradi?", "options": ["O'z-o'zidan toza suvga aylanadi", "Kanalizatsiya orqali suv tozalash inshootlariga boradi, ammo u yerdagi foydali bakteriyalarni o'ldirib, oqova suvlarni tozalash tizimini buzadi", "Yer yutib yuboradi"], "answer_index": 1, "explanation": "To'g'ri! Maishiy kimyo vositalari kanalizatsiyadagi organik biologik filtrlarni o'ldiradi va daryolarga zahar bo'lib boradi." },
    { "id": "bp49", "story": "Davlat aholining go'shtga bo'lgan talabini qondirish uchun millionlab gektar tropik o'rmonlarni kesib, molxonalarga aylantirdi.", "question": "Bu globallashuv ekologiyasiga qanday xavf tug'diradi?", "options": ["Hech qanday", "O'rmonning kesilishi tufayli CO2 ko'payishi bilan birga, millionlab mollar ajratgan \"Metan\" (CH4) gazi iqlimni dahshatli isitadi", "Havo sovuq bo'lib ketadi"], "answer_index": 1, "explanation": "To'g'ri! Sanoatlashgan chorvachilik issiqxona gazlarining (ayniqsa metan) eng katta manbalaridan biridir." },
    { "id": "bp50", "story": "Odamlar ekinlarni yovvoyi to'ng'izlar yemasin deb ularni zaharlab o'ldirishdi. Ko'p o'tmay o'rmonda daraxtlar quriy boshladi.", "question": "To'ng'izning bunga qanday aloqasi bor?", "options": ["Aloqasi yo'q", "To'ng'izlar tuproqni kovlab yumshatib turgan, yong'oq va urug'larni ko'mib yangi daraxtlar o'sishiga sababchi bo'lgan", "Daraxtlar qarigan"], "answer_index": 1, "explanation": "To'g'ri! Tabiatda hayvonlarning ozuqa izlashi aslida o'rmon ekotizimi uchun tuproq yumshatuvchi va urug' tarqatuvchi vazifasini bajaradi." },
    { "id": "bp51", "story": "Boyish maqsadida yashirin jinoiy guruh karkidonlarni (nosorog) faqat shoxi uchun o'ldirib ketmoqda.", "question": "Bu qaysi turdagi jinoyatga kiradi?", "options": ["Kichik huquqbuzarlik", "Xalqaro brakonyerlik bo'lib, hayvon turining genofondiga halokatli zarba (qirilib ketishiga) olib keladi", "Oddiy ov"], "answer_index": 1, "explanation": "To'g'ri! Hayvonlarning muayyan a'zosi (shoxi, tishi) uchun ovlanishi turning butunlay yo'q qilinishiga sabab bo'ladi." },
    { "id": "bp52", "story": "Olimlar baliqlar tuxumida va baliq go'shtida dorilar (antibiotiklar, gormonlar) qoldig'ini topishdi. Bu dorilar zavoddan emas, odamlarning uyidan kelgan.", "question": "Dorilar qanday qilib suvga tushgan?", "options": ["Baliqchilar bergan", "Odamlar muddati o'tgan dorilarni hojatxonaga oqizgani uchun", "Osmondan tushgan"], "answer_index": 1, "explanation": "To'g'ri! Kanalizatsiya tizimlari kimyoviy dori vositalarini tozalashga moslashmagan. Dorilar suv havzalarini zaharlaydi." },
    { "id": "bp53", "story": "Cho'l mintaqasida qattiq shamollar qum va tuzni ko'tarib minglab kilometrga uchirib ketmoqda.", "question": "Bu bo'ronlarning kuchayishiga inson qanday hissa qo'shdi?", "options": ["Shamol parraklari o'rnatgani orqali", "Orol dengizi kabi ko'llarni quritish, cho'llardagi saksovullarni o'tin uchun qirib tashlash orqali", "Hissa qo'shmagan"], "answer_index": 1, "explanation": "To'g'ri! O'simlik qoplamisiz qolgan quruq va sho'rxok tuproq kuchli chang bo'ronlari manbaiga aylanadi." },
    { "id": "bp54", "story": "Qishloqda yerlar tekislanib faqat paxta va bug'doy ekildi. Ilgari uchraydigan ko'plab qush, baqa va hasharotlar yo'qolib qoldi.", "question": "Bu jarayon ekologiyada nima deyiladi?", "options": ["Gullab yashnash", "Monokultura (faqat bir xil ekin) tufayli bioxilma-xillikning qisqarishi", "Eroziya"], "answer_index": 1, "explanation": "To'g'ri! Monokultura (bir xil ekin turi) turli xil hayvonlar va o'simliklar yashashi uchun kerakli sharoitni buzadi." },
    { "id": "bp55", "story": "O'zbekistonning issiq iqlimiga qaramay, bino fasadlarida hamma yog'i qora va qoraytirilgan oyna bo'lgan binolar ko'p qurilmoqda. Ularning ichini sovutish uchun yuzlab konditsionerlar tinimsiz ishlamoqda.", "question": "Buning ekologik oqibati qanday?", "options": ["Havo tozalanadi", "Konditsionerlardan chiqqan issiqlik shahar ko'chalarini battar isitadi, energiya sarfi (va shunga mos ravishda issiqxona gazlari) keskin ortadi", "Faqat chiroyli ko'rinadi"], "answer_index": 1, "explanation": "To'g'ri! Issiq iqlimda oynavand qora binolar (issiqxona kabi qiziydi) energiyani isrof qiluvchi va atrofni isituvchi manbadir." },
    { "id": "bp56", "story": "Yengil avtomobil egasi pulni tejash uchun mashinasidan katalizatorni olib tashlab sotib yubordi.", "question": "U tabiatga nima zarar qildi?", "options": ["Katalizatorning foydasi yo'q", "Katalizator zaharli gazlarni (is gazi, azot oksidlari) zararsizlantiruvchi filtr edi. Endi mashina havoni bir necha barobar ko'p zaharlaydi", "Mashina tezroq yuradi"], "answer_index": 1, "explanation": "To'g'ri! Katalitik neytralizator avtomobil tutunidagi zaharni tozalaydi. Uni olib tashlash (garchi javobgarlik bo'lmasa-da) ekologik jinoyatdek gap." },
    { "id": "bp57", "story": "Sayyohlar dam olish zonasida olov yoqib gulxan atrofida o'tirishdi. Ketayotganda olov ustiga ozgina tuproq tortib ketishdi. Tunda shamol turib o'rmon yonib ketdi.", "question": "Olovni o'chirish qoidasi qanday edi?", "options": ["Olovni shunday tashlab ketish kerak", "Olovga mo'l ko'l suv quyib, hech qanday tutun va cho'g' qolmaganiga to'liq ishonch hosil qilish shart edi", "Tuproq tortish kifoya qiladi"], "answer_index": 1, "explanation": "To'g'ri! Yuzaki ko'milgan cho'g' shamolda osongina alangalanadi. 90% o'rmon yong'inlariga aynan inson ehtiyotsizligi sabab bo'ladi." },
    { "id": "bp58", "story": "Zavod chiqqan oqova suvlarini maxsus biologik hovuzga to'kdi. Bu hovuzda qamish va o'ziga xos suvo'tlar o'stirilgan edi. Keyin suv daryoga quyildi.", "question": "Bu o'simliklar nima vazifa bajardi?", "options": ["Faqat chiroyli turdi", "Fito-tozalash (Fitoremediatsiya). O'simliklar va ularning ildizidagi bakteriyalar suvdagi zaharli moddalarni o'ziga yutib suvni tozalab berdi", "Suvni bulg'atdi"], "answer_index": 1, "explanation": "To'g'ri! Qamish kabi o'simliklar zaharli chiqindilarni va og'ir metallarni parchalovchi eng zo'r biologik tozalash inshootlari hisoblanadi." },
    { "id": "bp59", "story": "Suv tanqis hududda dehqon ekinlarni an'anaviy ariqdan jo'yaklab emas, balki tomchilatib sug'orish tizimi orqali sug'ora boshladi.", "question": "Ekologik jihatdan bu usulning yutug'i nimada?", "options": ["Suv juda oz tejaladi", "Suv bug'lanishi keskin kamayadi, begona o'tlar o'smaydi, tuproq eroziyasi to'xtaydi va suv 50% gacha tejaladi", "Zararli usul"], "answer_index": 1, "explanation": "To'g'ri! Tomchilatib sug'orish qishloq xo'jaligida suvni oqilona sarflashning eng ilg'or usullaridan biridir." },
    { "id": "bp60", "story": "Tog'li hududda odamlar hamma butalarni o'tin qilishdi. Qishda kuchli qor yog'di va keyin havo isib erishni boshladi. To'satdan dahshatli qor ko'chkisi (yoki sel) qishloqni bosdi.", "question": "Butalarning kesilishi bunga qanday ta'sir qildi?", "options": ["Ta'siri yo'q", "Tog' yonbag'irlaridagi buta va daraxtlarning ildizlari tuproq va qorni ushlab turuvchi asosiy \"armatura\" edi. Ular kesilgach ko'chki osonlashdi", "Qor ko'proq yog'di"], "answer_index": 1, "explanation": "To'g'ri! Tog' o'simliklari yonbag'irlarni qulashdan saqlovchi tabiiy mustahkamlovchi qatlamdir." }
]
"@

$newTermsStr = @"
[
    { "id": "bt41", "question": "Bioxilma-xillik konvensiyasi (CBD) qachon qabul qilingan?", "options": ["1972 yil Stokgolm", "1992 yil Rio-de-Janeyro", "1997 yil Kioto"], "answer_index": 1, "explanation": "To'g'ri! Rio-de-Janeyrodagi sammitda qabul qilingan bo'lib, sayyoraning barcha jonzotlarini asrashga xizmat qiladi." },
    { "id": "bt42", "question": "Fitoremediatsiya nima?", "options": ["O'simliklar yordamida tuproq, suv yoki havoni zaharli kimyoviy moddalardan tozalash jarayoni", "Zararkunandalarga qarshi kimyoviy dori sepish", "Suvni filtrlash"], "answer_index": 0, "explanation": "To'g'ri! Fito (o'simlik), remediatsiya (tiklash, tozalash). Ba'zi o'simliklar og'ir metallarni va zaharlarni uziga shimib, yerni tozalaydi." },
    { "id": "bt43", "question": "Karbonat angidrid (Uglerod) yutqichlari nimalar?", "options": ["Zavod trubalari", "O'rmonlar va okeanlar (u yerdagi fitoplanktonlar)", "Cho'llar"], "answer_index": 1, "explanation": "To'g'ri! Ular CO2 gazini katta miqdorda o'zida saqlab qoladigan eng yirik tabiiy zaxiralardir." },
    { "id": "bt44", "question": "Dioksinlar nima?", "options": ["Foydali vitaminlar", "Plastik, rezina va maishiy chiqindilarni past haroratda ochiq yoqishdan hosil bo'luvchi eng o'ta zaharli va kanserogen (rak qiliuvchi) modda", "Atir guli ifori"], "answer_index": 1, "explanation": "To'g'ri! Dioksin tabiatda parchalanmaydi, inson immunitetini va genini yo'q qiluvchi kuchli zahardir." },
    { "id": "bt45", "question": "Ekoturizm (Ekologik turizm) nima?", "options": ["Shaharlarda dam olish", "Yovvoyi tabiatning buzilmagan joylariga tabiatga ziyon yetkazmasdan, mahalliy aholi va tabiatni asrashga hissa qo'shib sayohat qilish", "Mehmonxona qurish"], "answer_index": 1, "explanation": "To'g'ri! Ekoturizmning asosiy qoidasi: \"Tabiatda faqat izingni qoldir, undan faqat suratlar olib ket\"." },
    { "id": "bt46", "question": "Brakish suv nima?", "options": ["Toza ichimlik suvi", "Dengiz sho'r suvi", "Chuchuk suv bilan dengiz suvi aralashgan, biroz sho'rtob suv (masalan, daryolar dengizga quyiladigan joylarda)", "Zaharli suv"], "answer_index": 2, "explanation": "To'g'ri! Bu hududlarda o'ziga xos ekotizim va faqat shu yerga moslashgan hayvonlar yashaydi." },
    { "id": "bt47", "question": "Zararkunandalarga qarshi Integratsiyalashgan kurash (IPM) nima?", "options": ["Faqat eng kuchli zaharlarni ishlatish", "Biologik, mexanik va faqat o'ta zarur bo'lganda ozgina kimyoviy usullarni birgalikda qo'llab, hosilni saqlab qolish", "Hech narsa qilmaslik"], "answer_index": 1, "explanation": "To'g'ri! Zamonaviy agronomiyada zaharlardan faqat eng so'nggi chora sifatida va qat'iy me'yorda foydalaniladi." },
    { "id": "bt48", "question": "Permafrost (Mangu muzliklar) nima?", "options": ["Muzlatgichlar", "Yer yuzining shimoliy hududlarida minglab yillar davomida erimagan, doimiy muzlab yotuvchi tuproq (va muz) qatlami", "Qishki qor"], "answer_index": 1, "explanation": "To'g'ri! Global isish sababli mangu muzliklar erimoqda va u yerdan ulkan miqdordagi metan gazi havoga chiqib ketmoqda." },
    { "id": "bt49", "question": "Pelagik zona nima?", "options": ["Tog'ning uchi", "Okean yoki ko'lning qirg'oqdan yoki tubidan uzoqroq bo'lgan erkin va ochiq suv ustuni qismi", "Daryo quyi oqimi"], "answer_index": 1, "explanation": "To'g'ri! Bu yerda nekton va planktonlar (baliqlar, meduzalar) faol yashaydi." },
    { "id": "bt50", "question": "Bentik zona nima?", "options": ["Suv usti", "Okean yoki ko'lning eng tubidagi tuproqli va g'ovak qismi bo'lib, u yerda bentos (tub) organizmlari yashaydi", "Atmosfera buluti"], "answer_index": 1, "explanation": "To'g'ri! Qisqichbaqasimonlar, dengiz yulduzlari asosan bentik zonada yashaydi." },
    { "id": "bt51", "question": "Gidrologik qurg'oqchilik nima?", "options": ["Bir kun yomg'ir yog'masligi", "Ko'llar, daryolar va yer osti suv sathining keskin va uzoq muddatga pasayib ketishi", "Qum bo'roni"], "answer_index": 1, "explanation": "To'g'ri! Bu qurg'oqchilik ekotizim va iqtisodiyot uchun eng xavfli tur hisoblanadi." },
    { "id": "bt52", "question": "Xalqaro qoidalarga ko'ra Qizil kitobning vazifasi nima?", "options": ["Hayvonlarni otishga ruxsat berish", "Noyob va yo'qolib borayotgan turlarning saqlanib qolishi va ko'payishi uchun zarur choralarni ishlab chiqish hamda jamoatchilikni ogoh etish", "Faqat ro'yxatga olish"], "answer_index": 1, "explanation": "To'g'ri! Qizil kitob ogohlantiruvchi signal xususiyatiga ega hujjatdir." },
    { "id": "bt53", "question": "Klimatologiyada Albedo nima?", "options": ["Shamol tezligi", "Yer yuzasining quyosh nurlarini qaytarish qobiliyati (masalan, qor va muz yorug'likni 90% qaytaradi)", "Tog' cho'qqisi"], "answer_index": 1, "explanation": "To'g'ri! Muzliklarning erishi Yerning albedosini (qaytarish qobiliyatini) pasaytiradi va yer ko'proq issiqlikni yuta boshlaydi." },
    { "id": "bt54", "question": "Ekologik izchillik (Barqaror rivojlanish / Sustainable development) nima?", "options": ["Barcha resurslarni bir kunda sarflash", "Kelajak avlodlarning o'z ehtiyojlarini qondirish qobiliyatiga putur yetkazmagan holda, hozirgi zamon ehtiyojlarini qondirish", "Faqat sanoat qurish"], "answer_index": 1, "explanation": "To'g'ri! Bu insoniyatning yashab qolish va tabiat bilan hamohang rivojlanish falsafasidir." },
    { "id": "bt55", "question": "Kompostlash nima?", "options": ["Plastikni eritish", "O'simlik qoldiqlari, oziq-ovqat chiqindilari va go'ngni chirishiga (fermentatsiya) sharoit yaratib, tabiiy o'g'it (kompost) olish jarayoni", "Chiqindini yoqish"], "answer_index": 1, "explanation": "To'g'ri! Kompostlash organik chiqindilardan qutilishning ekologik toza va eng foydali usulidir." },
    { "id": "bt56", "question": "Iqlim muhojirlari (Climate refugees) kimlar?", "options": ["Dam olishga borayotganlar", "Iqlim o'zgarishi, qurg'oqchilik, suv toshqini kabi ekologik halokatlar sababli o'z yashash joyini tark etishga majbur bo'lgan odamlar", "Sayyohlar"], "answer_index": 1, "explanation": "To'g'ri! Orolbo'yi mintaqasida yashagan minglab insonlar shunga misol bo'la oladi." },
    { "id": "bt57", "question": "Freonlar atmosferada qanday ziyon keltiradi?", "options": ["Issiqlik tarqatadi", "Ulardagi xlor va brom atomlari ozon molekulalarini parchalab tashlaydi", "Bulutlarni yo'q qiladi"], "answer_index": 1, "explanation": "To'g'ri! Bitta xlor atomi 100 mingta ozon molekulasini yemirishga qodir." },
    { "id": "bt58", "question": "Urban ekologiyasi (Shahar ekologiyasi) nimani o'rganadi?", "options": ["Qishloq hayotini", "Shahar ekotizimidagi insonlar, tabiat va sun'iy muhit o'rtasidagi o'zaro murakkab munosabatlarni", "Faqat transport harakatini"], "answer_index": 1, "explanation": "To'g'ri! U shaharlarda qanday qilib daraxtlar, havo va odamlar uyg'unlikda yashashini o'rganadi." },
    { "id": "bt59", "question": "Antropotsentrizm nima?", "options": ["Tabiat hukmronligi", "Odamni tabiatning hukmdori va markazi deb biladigan, tabiat faqat inson ehtiyojlari uchun yaratilgan degan (noto'g'ri) qarash", "Barcha organizmlar tengligi"], "answer_index": 1, "explanation": "To'g'ri! Bunday xudbinona yondashuv zamonaviy ekologik halokatlarning asosiy falsafiy sababchisi bo'ldi." },
    { "id": "bt60", "question": "Ekosentrizm nima?", "options": ["Markaziy Osiyo ekologiyasi", "Butun tabiat, uning barcha tirik va jonsiz elementlari ichki qadr-qimmatga ega bo'lib, inson faqat uning bir bo'lagi ekanligini anglatuvchi dunyoqarash", "Faqat iqtisodiyot"], "answer_index": 1, "explanation": "To'g'ri! Ekosentrizm insonga tabiatga ehtiyotkor va hurmat bilan munosabatda bo'lishni o'rgatadi." }
]
"@

$newPenaltiesStr = @"
[
    { "id": "bpn41", "question": "Yerlardan noqonuniy qum yoki shag'al qazib olish qanday oqibatga olib keladi? (MJtK 70-1-modda)", "options": ["Foyda keltiradi", "Foydali qazilmalarni ruxsatsiz qazib olish ashyolarni musodara qilib, jarima solishga (yoki jinoiy ishga) sabab bo'ladi", "Faqat ogohlantirish"], "answer_index": 1, "explanation": "To'g'ri! Daryo va tog'lardan noqonuniy qum va tosh qazish daryo o'zanini buzadi va atrof muhitga katta ziyon keltiradi." },
    { "id": "bpn42", "question": "Qurilish materiallari (masalan sement) ishlab chiqaruvchi zavod havoni ifloslantirsa, uning javobgarligi o'zgaradimi?", "options": ["Yo'q, zavod yopilmaydi", "Qonunbuzarlik davom etsa uning faoliyati Ekologiya vazirligi va sud qarori bilan butunlay to'xtatib qo'yilishi mumkin", "Jarima to'lab yuraveradi"], "answer_index": 1, "explanation": "To'g'ri! Aholi sog'lig'iga va ekologiyaga xavf tug'dirgan har qanday zavod ishlashdan to'xtatib qo'yiladi." },
    { "id": "bpn43", "question": "Avtomobil oynasidan ko'chaga (yoki daryoga) pista po'chog'i yoxud baklajka uloqtirgan haydovchiga jarima bormi?", "options": ["Yo'q, u kichkina axlat", "Ha, \"Avtomobildan chiqindi tashlash\" ma'muriy huquqbuzarlik sanalib, jarima undiriladi", "Faqat piyodalarga mumkin"], "answer_index": 1, "explanation": "To'g'ri! Transportdan chiqindi tashlash ekologiya va yo'l qoidalariga ko'ra jazoga tortiladi." },
    { "id": "bpn44", "question": "Hayvonlarning bolalarini (masalan, kiyikchani yoki ayiqchani) yovvoyi tabiatdan o'g'irlab uyda boqish qonuniymi?", "options": ["Ha, agar yaxshi boqsa", "Mutlaqo noqonuniy, yovvoyi hayvonlarni davlat ruxsatisiz tutqunlikda saqlash (brakonyerlik) jarima va jinoiy javobgarlikka sabab bo'ladi", "Faqat yozda mumkin"], "answer_index": 1, "explanation": "To'g'ri! Yovvoyi jonzotlar davlat mulki va tabiatning ajralmas qismidir." },
    { "id": "bpn45", "question": "Baliq ovlash davrida (uvildiriq sochish vaqtida) suv omborlarida motorli qayiqlarda baland ovoz chiqarib suzish mumkinmi?", "options": ["Mumkin", "Ta'qiqlanadi! Shovqin baliqlarning ko'payishiga xalaqit beradi va bu harakat javobgarlikka tortiladi", "Faqat bayram kunlari"], "answer_index": 1, "explanation": "To'g'ri! Bahor mavsumida barcha suv havzalarida qat'iy sokinlik rejimi o'rnatiladi." },
    { "id": "bpn46", "question": "Zararli kimyoviy moddalarni (pestisid va o'g'itlarni) ochiq havoda, yomg'ir tagida saqlagan ombor mudiri nima uchun javobgar?", "options": ["Zarari yo'q", "Saqlash qoidalarini buzib, zaharning atrof muhitga oqib ketishiga sabab bo'lgani uchun javobgar bo'ladi", "Foydali modda-ku"], "answer_index": 1, "explanation": "To'g'ri! Kimyoviy moddalarni saqlash xavfsizligi bo'yicha maxsus qat'iy talablar mavjud." },
    { "id": "bpn47", "question": "Bir guruh odamlar milliy bog'ga dam olgani borib, daraxtlarga o'z ismlarini o'yib yozishdi. Bu uchun jazo bormi?", "options": ["Yo'q, bu san'at", "Ha, daraxtga qasddan shikast yetkazish deb baholanadi va jarima solinadi", "Faqat bolalarga mumkin"], "answer_index": 1, "explanation": "To'g'ri! Daraxt po'stlog'ini ko'chirish uni kasallantiradi, bu daraxtni shikastlash hisoblanadi." },
    { "id": "bpn48", "question": "Shaharsozlik va qurilish loyihalarida yashil hududlar (daraxtzorlar) maydoni saqlanmasdan, hammasi betonlab tashlansa kim javobgar?", "options": ["Hech kim", "Loyiha bo'yicha ekologik ekspertiza talabini buzgan arxitektor va mas'ul shaxslar ma'muriy javobgarlikka tortiladi", "Quruvchilar"], "answer_index": 1, "explanation": "To'g'ri! Qurilish me'yorlariga ko'ra har qanday ob'ekt atrofida ma'lum miqdorda ko'kalamzor hudud bo'lishi shart." },
    { "id": "bpn49", "question": "Radioaktiv chiqindilarni boshqa hududga qanday tartibda olib o'tish mumkin?", "options": ["Oddiy yuk mashinasida", "Faqat maxsus davlat nazorati ostida, yashirin holda tashish esa o'ta og'ir jinoiy javobgarlikka tortiladi", "Xohlagan vaqtda"], "answer_index": 1, "explanation": "To'g'ri! Xavfli qoldiqlarni harakati (transportirovkasi) hukumat ruxsati bilan qat'iy nazorat qilinadi." },
    { "id": "bpn50", "question": "Dehqon tuproqqa shunchalik ko'p zaharli dori sepib yubordiki, tuproqdagi qurt-qumursqa va chuvalchanglar qirilib, yer toshdek qotib qoldi. Bunga qonun bormi?", "options": ["Yer o'ziniki, xohlaganini qiladi", "Tuproqni kimyoviy moddalar bilan zaharlaganlik (yerning buzilishi) uchun jiddiy jarimaga tortiladi va uning yerga egalik huquqi bekor qilinishi mumkin", "Jazo yo'q"], "answer_index": 1, "explanation": "To'g'ri! Yer davlat himoyasidagi umummilliy boylik, yer egasi faqat undan oqilona foydalanishi shart." },
    { "id": "bpn51", "question": "Oqova suvlarni (kanalizatsiyani) tozalamasdan to'g'ridan-to'g'ri anhorga oqizayotgan kafe (choyxona) egasiga qanday chora ko'riladi?", "options": ["Faqat hayfsan", "Unga jarima solinadi, zarari hisoblanadi va quvurni darhol uzib qo'yish chorasi ko'riladi", "Arzon jarima"], "answer_index": 1, "explanation": "To'g'ri! Suv havzalariga tozalanmagan maishiy chiqindilarni tushirish kasalliklar tarqatish xavfi tufayli juda qattiq taqiqlanadi." },
    { "id": "bpn52", "question": "Zavod rahbari ekologik monitoring (tekshirish) apparatlarini o'chirib qo'ydi, toki havoga qancha zahar chiqayotgani bilinmasin. Ushbu xatti-harakat qanday jazolanadi?", "options": ["Bu uning ishi", "Tabiatni muhofaza qilish inshootlarini (filtr va nazorat uskunalarini) ataylab ishlatmaslik deb baholanib, javobgarlik (jarima) keskin ortadi", "Jarima bo'lmaydi"], "answer_index": 1, "explanation": "To'g'ri! Ekologik nazorat asboblarini yashirish yoki o'chirish qasddan qilingan huquqbuzarlik sanaladi." },
    { "id": "bpn53", "question": "Noyob gullar va dorivor o'simliklarni tonnalab (katta hajmda) ruxsatsiz terib olib, chetga sotgan tadbirkor jazolanadimi?", "options": ["Yo'q, ular dorivor", "Ha, o'simlik dunyosidan noqonuniy foydalanganlik va Qizil kitob turlarini yo'q qilganlik uchun juda ulkan miqdorda moddiy zarar undiriladi (yoki jinoyat ishi)", "Faqat mol-mulki olinadi"], "answer_index": 1, "explanation": "To'g'ri! Dorivor va yovvoyi o'simliklarni tijorat maqsadida yig'ish faqat kvota (ruxsatnoma) bilan pullik asosda bo'ladi." },
    { "id": "bpn54", "question": "Issiqxona (parnik) isitish uchun eski shinalar va kauchuklarni yoqish javobgarlik keltirib chiqaradimi?", "options": ["Ha, atmosfera havosini zaharli tutun bilan o'ta kuchli ifloslantirgani uchun tegishli javobgarlikka tortiladi", "Yo'q, qishda o'zini isitishi kerak", "Jazo yo'q"], "answer_index": 0, "explanation": "To'g'ri! Shina (rezina) yoqish atrofdagilar orasida rak kasalligini keltirib chiqaruvchi eng zaharli tutun chiqaradi." },
    { "id": "bpn55", "question": "Ovchilik guvohnomasisiz o'z iti yordamida dalada quyon ovlash brakonyerlikka kiradimi?", "options": ["Yo'q", "Ha, ov qilish usulidan (qurol, it, qopqon) qat'iy nazar ruxsatsiz tutilgan har qanday yovvoyi hayvon uchun javobgarlik belgilanadi", "Faqat miltiqda otsa brakonyer"], "answer_index": 1, "explanation": "To'g'ri! Yovvoyi jonivorlarni hatto tayoq bilan ushlasa ham, qonunsiz harakat sanaladi." },
    { "id": "bpn56", "question": "Quyosh va shamol elektr stansiyasi (QES) barpo etayotgan investor ham Ekologik ekspertizadan o'tishi kerakmi?", "options": ["Yo'q, u yashil energiya", "Ha, har qanday yirik inshoot qurilishi atrof muhitga (masalan, qushlarning uchishiga) ta'sirini baholash uchun Davlat ekologik ekspertizasidan o'tishi shart", "Ixtiyoriy"], "answer_index": 1, "explanation": "To'g'ri! Hatto ekologik toza stansiyalar qurilishi ham mahalliy bioxilma-xillikka (tuproq, qushlar) salbiy ta'sir ko'rsatmasligi kerak." },
    { "id": "bpn57", "question": "Ekologik jarimalardan tushgan mablag'lar qayerga yo'naltiriladi?", "options": ["Faqat byudjetga", "Asosan Ekologiya, atrof-muhitni muhofaza qilish va iqlim o'zgarishi jamg'armasiga, tabiatni tiklash dasturlari uchun", "Tashkilot xodimlariga"], "answer_index": 1, "explanation": "To'g'ri! Undirilgan zarar pullari yana qaytadan daraxt ekish, hayvonlarni asrash va tabiatni tiklashga ishlatiladi." },
    { "id": "bpn58", "question": "Tunda daryodan ekskavator bilan qum qaziyotganlar huquqni muhofaza qilish xodimlari tomonidan ushlandi. Uskunaga (ekskavatorga) nima bo'ladi?", "options": ["Egasiga qaytariladi", "Brakonyerlik vositasi sifatida huquqbuzarlik ob'ekti tariqasida qonuniy sud orqali davlat foydasiga musodara qilinadi", "Faqat jarima"], "answer_index": 1, "explanation": "To'g'ri! Noqonuniy harakatda ishlatilgan har qanday texnika davlat foydasiga musodara qilinishi mumkin." },
    { "id": "bpn59", "question": "Ekologiya vazirligining Davlat inspektorlari xizmat vazifasini bajarayotgan vaqtida o'qotar qurol ko'tarishga va uni qo'llashga haqlimi?", "options": ["Yo'q", "Ha, agar brakonyerlar tomonidan hayotiga xavf tug'ilsa (o'zini himoya qilish uchun) ularda xizmat qurolini ko'tarib yurish va qonuniy qo'llash huquqi bor", "Faqat rezina o'qlar"], "answer_index": 1, "explanation": "To'g'ri! Inspektorlarning hayoti tabiatni asrash vaqtida qurollangan brakonyerlar tomonidan ko'p xavf ostida qoladi." },
    { "id": "bpn60", "question": "Kimyoviy moddalar yoki pestitsidlardan foydalanish, tashish va saqlash qoidalarini buzganlik (MJtK 87-modda) fuqarolarga qanday jarima soladi?", "options": ["BHM 1 baravari", "BHMning 1 dan 3 baravarigacha, mansabdor shaxslarga esa 3 dan 5 baravarigacha", "Faqat hayfsan"], "answer_index": 1, "explanation": "To'g'ri! Pestisid va kimyoviy o'g'itlarni noto'g'ri saqlash juda xavfli bo'lib, zudlik bilan jarima solinadi." }
]
"@

$newTrueFalseStr = @"
[
    { "id": "btf41", "question": "Gidrosferaning deyarli barcha suvlari insoniyat ichishi uchun yaroqlidir.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Dunyo okeani 97% suvni tashkil qiladi va u sho'rdir. Faqat 3% chuchuk suv (uning ham ko'pi muzlikda) mavjud." },
    { "id": "btf42", "question": "Agar birorta hasharot tabiatdan butunlay qirilib ketsa, bu ekotizimga hech qanday zarar qilmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Tabiat - zanjirdek gap. Biror hasharot yo'qolsa, uni yeydigan qushlar och qoladi, qushlar yo'qolsa boshqa zararkunandalar ko'payadi." },
    { "id": "btf43", "question": "Yerdagi iqlim isishini (global isishni) bugun darhol to'xtatib qo'yish mumkin.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Hozirgacha to'plangan CO2 atmosferada yuzlab yillar saqlanib qoladi. Jarayon inersiya bilan baribir bir necha o'n yillar davom etadi." },
    { "id": "btf44", "question": "Shamoldan va quyoshdan energiya olish jarayonida umuman hech qanday kimyoviy qoldiq chiqmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Bu aynan shuning uchun eng 'yashil' va toza energiya manbai sanaladi." },
    { "id": "btf45", "question": "Daraxt barglari ustiga yig'ilgan changlar tuproqqa yomg'ir orqali tushganda, ular o'simliklar uchun o'g'it vazifasini ham bajarishi mumkin.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Shahar va tabiiy changlar tarkibida ko'plab mikroelementlar mavjud, daraxt yomg'ir yuvganidan so'ng yana havoni tozalaydi." },
    { "id": "btf46", "question": "Plastik idishlarni tashlamasdan ularni hovlida yoqib yuborish - axlatni kamaytirishning eng oson va ekologik toza yo'lidir.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Plastikni yoqish uning chirishidan ko'ra yuz marta xavfliroq, bu saratonga sabab bo'luvchi zaharni osmonga purkash bilan tengdir." },
    { "id": "btf47", "question": "Suv sathi tushib, qurib borayotgan barcha ko'llar Orol dengizi kabi halokatga uchrashi aniq.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Ba'zi ko'llarning qurishi va botqoqqa aylanishi (suksessiya) tabiiy va geologik me'yoriy jarayondir, faqat insonsiz bu jarayon minglab yillar davom etadi." },
    { "id": "btf48", "question": "Hayvonot bog'lari (Zooparklar) kamyob turlarni asrab qolish va ularni ko'paytirib tabiatga qaytarishda muhim rol o'ynaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Zamonaviy zooparklarning asosiy maqsadi shunchaki tomosha ko'rsatish emas, noyob turlarning genofondini saqlab qolishdir." },
    { "id": "btf49", "question": "Avtomobilning dvigatel hajmi qanchalik kichik bo'lsa (masalan kichik litrajli mashinalar) odatda atmosferaga chiqindi gazlari shunchalik kam chiqadi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Kichik hajmli motorlar kam yoqilg'i sarflaydi, demak tabiatga ham shunga yarasha kam ziyon yetkazadi." },
    { "id": "btf50", "question": "Suv tubidagi organizmlar (bentos) suvdagi chiqindilar bilan oziqlanib, suvning o'zini o'zi tozalashida qatnashmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Bental organizmlar (masalan suv shillig'i va chig'anoqlar) daryoning tirik filtrlaridir. Ular barcha organik chiqindilarni yeb tozalab beradi." },
    { "id": "btf51", "question": "Ko'mir yoqilg'isidan foydalanuvchi elektr stansiyalari atom (yadro) elektr stansiyalariga qaraganda havoni ko'proq ifloslantiradi va radioaktiv elementlar ajratadi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Garchi ajablanarli bo'lsa-da, ko'mir tutunida uran va toriy kabi radioaktiv qoldiqlar bo'ladi va ular havoga me'yoriy ishlaydigan AESdan ko'proq zahar sochadi." },
    { "id": "btf52", "question": "Insonlarning suvga munosabati oqibatida ko'pgina yirik daryolar okeanga yetib bormasdan qurib qolmoqda.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Amudaryo va Kolorado kabi ulkan daryolar ko'pincha daryo etagida mutlaqo qurib qolib okeanga (dengizga) yetib bormaydi." },
    { "id": "btf53", "question": "Hozirgi vaqtda yovvoyi tabiatning halokatiga asosiy sababchi yirtqich hayvonlarning ko'payib ketishi hisoblanadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Hayvonlar olamiga eng xavfli tahdid – bu insonlarning ularning yashash muhitini (o'rmon va cho'llarni) yo'q qilayotgani va iqlim o'zgarishidir." },
    { "id": "btf54", "question": "Elektron chiqindilar (eski telefon, kompyuter, televizor) oddiy axlat qutisiga tashlanishi kerak emas.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Elektronika tarkibida ko'p miqdorda zaharli qo'rg'oshin, simob, va kadmiy bor, ular faqat maxsus korxonalarda utilizatsiya qilinishi shart." },
    { "id": "btf55", "question": "Dunyodagi barcha cho'llar faqat havo juda issiq bo'lgan joylarda joylashgan.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Cho'l tushunchasi issiqlikka emas, balki yog'ingarchilik kamligiga bog'liq. Masalan, Antarktida ham quruq muzli cho'l hisoblanadi." },
    { "id": "btf56", "question": "Agar dunyo darajasida go'sht iste'moli kamaytirilsa, bu iqlim o'zgarishini sekinlashtirishga yordam beradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Sanoat mollari millionlab gektar o'rmonni emirilishiga va metan gazi chiqarilishiga olib kelgani uchun, go'shtning kam iste'mol qilinishi katta foydadir." },
    { "id": "btf57", "question": "O'zbekistonda yovvoyi holda o'sadigan va yo'qolib ketayotgan za'faron (krokus), lola va boychechak kabi gullarni har qancha terish mumkin.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Bu gullar qattiq muhofazada va ularni terish ma'muriy (yoki jinoiy) javobgarlikka olib keladi." },
    { "id": "btf58", "question": "Mikroplastik zarralari shunchalik maydaki, ular hozirda barcha insonlarning (va hatto chaqaloqlarning) qonidan va organlaridan topilmoqda.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Mikroplastiklar ozuqa va havo orqali butun oziq zanjirining, jumladan insonlarning ham tanasiga o'rnashib olgan." },
    { "id": "btf59", "question": "Xalqaro qoidalarga asosan atrof-muhit musaffoligiga erishish uchun iqtisodiy o'sish va zavodlar qurilishini butunlay to'xtatish yagona yo'l hisoblanadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Insoniyat izchil (barqaror) rivojlanish konvensiyasiga amal qiladi: bu yerda ham iqtisodiyot rivojlanadi, ham ekologik toza texnologiyalar qo'llaniladi." },
    { "id": "btf60", "question": "Daraxt va o'rmonlar nafaqat yomg'irni keltirib chiqaradi, balki bulutlarni o'ziga tortuvchi 'bio-nasos' vazifasini ham bajaradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Qalin o'rmonlar atmosfera havosini namlik bilan to'yintiradi va daryolarning shakllanishida kuchli ahamiyatga ega." }
]
"@

$newQ = ConvertFrom-Json -InputObject $newQuizzesStr
$newP = ConvertFrom-Json -InputObject $newPuzzlesStr
$newT = ConvertFrom-Json -InputObject $newTermsStr
$newPn = ConvertFrom-Json -InputObject $newPenaltiesStr
$newTf = ConvertFrom-Json -InputObject $newTrueFalseStr

$jsonObj.quizzes += $newQ
$jsonObj.puzzles += $newP
$jsonObj.terms += $newT
$jsonObj.penalties += $newPn
$jsonObj.truefalse += $newTf

$jsonObj | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonFile -Encoding UTF8
