$ErrorActionPreference = "Stop"

$jsonFile = "C:\Users\Akobir\.gemini\antigravity\scratch\eco_law_bot\data\quiz.json"
$jsonStr = Get-Content -Raw -Path $jsonFile -Encoding UTF8
$jsonObj = ConvertFrom-Json -InputObject $jsonStr

$newQuizzesStr = @"
[
    { "id": "bq81", "question": "Yashil o'simliklar havoni qanday tozalaydi?", "options": ["Soya berish orqali", "Barglaridagi teshikchalar (ustitsa) orqali SO2, is gazi kabi zaharlarni yutib va changni ushlab qolib", "Suv bug'lantirib", "Tozalamaydi"], "answer_index": 1, "explanation": "To'g'ri! Barglar millionlab mitti teshikchalar orqali havoni filtrlaydi va zaharli gazlarni o'ziga yutadi." },
    { "id": "bq82", "question": "Gidrosferaning eng ifloslangan qismi qaysi?", "options": ["Okean o'rtasi", "Qit'alarning qirg'oqbo'yi zonalari", "Muzliklar", "Yer osti suvlari"], "answer_index": 1, "explanation": "To'g'ri! Sanoat va maishiy chiqindilar asosan qirg'oqbo'yi zonalarga tashlangani uchun, ular okeanning eng iflos qismidir." },
    { "id": "bq83", "question": "Tuproq tarkibida organik qoldiqlar chirishi natijasida hosil bo'ladigan eng qimmatli modda nima?", "options": ["Tuz", "Gumus (Chirindi)", "Qum", "Loy"], "answer_index": 1, "explanation": "To'g'ri! Gumus qanchalik ko'p bo'lsa, tuproq shunchalik qoramtir va unumdor bo'ladi." },
    { "id": "bq84", "question": "Dunyoda har yili o'rtacha qancha miqdorda plastik chiqindi hosil bo'ladi?", "options": ["1 million tonna", "400 million tonna atrofida", "10 million tonna", "100 ming tonna"], "answer_index": 1, "explanation": "To'g'ri! Har yili yuzlab million tonna plastik ishlab chiqariladi va uning atigi 9-10% qismigina qayta ishlanadi." },
    { "id": "bq85", "question": "Eng yirik ekologik fojia (radiatsiya tarqalishi) yuz bergan Chernobil AES avariyasi qachon sodir bo'lgan?", "options": ["1970 yil", "1986 yil 26 aprel", "2000 yil", "1991 yil"], "answer_index": 1, "explanation": "To'g'ri! Chernobil fojiasi insoniyat tarixidagi eng yirik texnogen ekologik halokat hisoblanadi." },
    { "id": "bq86", "question": "Xalqaro Hayvonlarni Himoya qilish kuni qachon?", "options": ["1 yanvar", "4 oktyabr", "5 iyun", "22 mart"], "answer_index": 1, "explanation": "To'g'ri! Bu kun butun dunyoda uy va yovvoyi hayvonlarga shafqatsiz munosabatning oldini olishga qaratilgan." },
    { "id": "bq87", "question": "Yovvoyi tabiatning qanday turkumdagi hayvonlari eng ko'p yo'q bo'lib ketish xavfi ostida?", "options": ["Qushlar", "Amfibiyalar (suvda va quruqlikda yashovchilar, masalan baqalar)", "Hasharotlar", "Sut emizuvchilar"], "answer_index": 1, "explanation": "To'g'ri! Amfibiyalar toza suvga juda muhtoj bo'lgani uchun suv ifloslanishi tufayli butun dunyoda eng tez qirilayotgan turkumdir." },
    { "id": "bq88", "question": "Yer sathidan qancha balandlikka ko'tarilganda havo tarkibidagi kislorod miqdori keskin kamayadi?", "options": ["1 km", "3-4 km dan yuqorida (Tog' kasalligi boshlanadi)", "500 metr", "10 km"], "answer_index": 1, "explanation": "To'g'ri! Tog'larda 3000 metrdan yuqorida kislorod siyraklashgani bois nafas olish og'irlashadi." },
    { "id": "bq89", "question": "Biosfera ta'limoti asoschisi kim?", "options": ["Albert Eynshteyn", "Vladimir Ivanovich Vernadskiy", "Charlz Darvin", "Isaak Nyuton"], "answer_index": 1, "explanation": "To'g'ri! Rus olimi V.I. Vernadskiy Biosfera haqidagi yaxlit ta'limotni yaratgan va tirik moddaning ahamiyatini isbotlab bergan." },
    { "id": "bq90", "question": "O'zbekistonda yovvoyi holda o'sadigan dorivor o'simliklar orasida eng mashhuri qaysi?", "options": ["Eman", "Isiriq (Peganum harmala)", "Lola", "Kaktus"], "answer_index": 1, "explanation": "To'g'ri! Isiriq dorivor, havo tozalovchi va dezinfeksiyalovchi o'simlik sifatida ko'p asrlardan beri ishlatiladi." },
    { "id": "bq91", "question": "Tuproq tarkibini yaxshilovchi, azot to'plovchi qishloq xo'jaligi ekinlari nima deb ataladi?", "options": ["Begona o'tlar", "Dukkaklilar (beda, mosh, no'xat)", "Zaharli o'tlar", "Gullar"], "answer_index": 1, "explanation": "To'g'ri! Dukkakli ekinlar ildizidagi tugunak bakteriyalar havodagi azotni o'zlashtirib, yerni tabiiy yo'l bilan o'g'itlaydi." },
    { "id": "bq92", "question": "Suvni eng ko'p ifloslantiruvchi soha qaysi?", "options": ["Aholi (maishiy)", "Qishloq xo'jaligi (o'g'it va pestisidlar bilan) va Og'ir sanoat", "Qurilish", "Transport"], "answer_index": 1, "explanation": "To'g'ri! Dehqonchilik maydonlaridan yuvilib kelgan zaharli suvlar va zavod oqova suvlari asosiy ifloslantiruvchilar hisoblanadi." },
    { "id": "bq93", "question": "Chiqindilarni saralashda yashil va ko'k qutilar ko'pincha nima uchun mo'ljallanadi?", "options": ["Aralash axlat", "Yashil - shisha idishlar, Ko'k - qog'oz va karton uchun", "Qurilish chiqindisi", "Oziq-ovqat"], "answer_index": 1, "explanation": "To'g'ri! Chiqindilarni saralab tashlash madaniyati ularni qayta ishlashning birinchi va eng muhim bosqichidir." },
    { "id": "bq94", "question": "Qaysi turkumdagi gazlar 'Ozon kushandalari' deb nom olgan?", "options": ["Vodorod", "Xlorftoruglerodlar (CFC) yoki Freonlar", "Kislorod", "Metan"], "answer_index": 1, "explanation": "To'g'ri! Freonlar muzlatgich, konditsioner va sprey-aerozollarda ishlatilgan bo'lib, ular ozon qatlamini yemiruvchi eng ashaddiy dushmandir." },
    { "id": "bq95", "question": "Tirik organizmlarning o'zaro foydali yashashi (hamkorligi) biologiyada qanday ataladi?", "options": ["Parazitizm", "Simboiz (Mutalizm)", "Raqobat", "Yirtqichlik"], "answer_index": 1, "explanation": "To'g'ri! Simbioz - bu ikki organizmning bir-biriga foyda keltirib birga yashashidir (masalan, daraxt va qo'ziqorin)." },
    { "id": "bq96", "question": "Yerning 'issiqxona qobig'i' bo'lmaganda o'rtacha harorat qanday bo'lar edi?", "options": ["+15 gradus", "O'ta sovuq (taxminan -18 Selsiy ostida) va hayot bo'lmasdi", "+50 gradus", "Farqi yo'q"], "answer_index": 1, "explanation": "To'g'ri! Atmosferadagi gazlar sayyorani adyol kabi o'rab, isitib turadi. Faqat gazlarning haddan ortiq ko'payishi muammodir." },
    { "id": "bq97", "question": "Yovvoyi tabiat umuman inson ta'siriga uchramagan (tegilmagan) sof holatdagi tabiat qanday nomlanadi?", "options": ["Urban", "Yovvoyi tabiat (Wilderness / Pristine nature)", "Qishloq", "Biotop"], "answer_index": 1, "explanation": "To'g'ri! Hozirgi kunda bunday bokira tabiat hududlari Yer yuzining atigi 20 foiziga ham yetmaydi." },
    { "id": "bq98", "question": "O'zbekistonda chuchuk suv zahiralarining qancha qismi transchegaraviy (qo'shni davlatlardan keladigan) suvlardir?", "options": ["10%", "80-85% atrofida", "30%", "Umuman yo'q"], "answer_index": 1, "explanation": "To'g'ri! Bizning daryolar asosan qo'shni tog'li davlatlar (Tojikiston, Qirg'iziston) muzliklaridan shakllanadi." },
    { "id": "bq99", "question": "Sayyoradagi eng yirik issiq cho'l qaysi?", "options": ["Gobi", "Sahroi Kabir (Saxara)", "Qizilqum", "Kalahari"], "answer_index": 1, "explanation": "To'g'ri! Saxara cho'li Afrika qit'asida joylashgan va global iqlim o'zgarishi tufayli uning maydoni tobora kengayib bormoqda." },
    { "id": "bq100", "question": "Tabiatni asrash har bir insonning qanday burchidir?", "options": ["Ixtiyoriy", "Ham konstitutsiyaviy, ham insoniylik (axloqiy) burchidir", "Faqat hukumatning burchi", "Vazifa emas"], "answer_index": 1, "explanation": "To'g'ri! Tabiatni muhofaza qilish O'zbekiston Respublikasi Konstitutsiyasida fuqarolarning burchi sifatida qat'iy belgilangan." }
]
"@

$newPuzzlesStr = @"
[
    { "id": "bp81", "story": "Odamlar shaharda daraxt barglarini terishga erinib, ularni bitta joyga to'plab yoqa boshlashdi. Shahar ustini qalin zaharli tutun qopladi.", "question": "Barglarni yoqish nega xavfli?", "options": ["Faqat xunuk ko'rinadi", "Barglar yoz bo'yi havoni tozalab, zaharli moddalarni o'ziga yig'gan bo'ladi. Ular yoqilganda barcha zahar (dioksin va og'ir metallar) qaytadan havoga otiladi", "Yong'in chiqishi mumkin"], "answer_index": 1, "explanation": "To'g'ri! Xazon yoqish insonlarning nafas yo'llari va o'pkasi uchun eng zararli qilmishdir, ularni chirishga (kompost) tashlash kerak." },
    { "id": "bp82", "story": "Katta tog' daryosiga GES (Gidroelektr stansiyasi) qurildi. To'g'on daryoni butunlay to'sib qo'ydi.", "question": "Bu daryoda yashovchi ko'chmanchi baliqlar (masalan osyotr) populyatsiyasiga qanday ta'sir qiladi?", "options": ["Baliqlar to'g'on ostida yashayveradi", "Baliqlar uvildiriq sochish (ko'payish) uchun daryoning yuqori qismiga suzib o'ta olmaydi va populyatsiyasi qirilib ketadi", "Baliqlar daryoni tark etadi"], "answer_index": 1, "explanation": "To'g'ri! To'g'onlar ko'plab daryo hayvonlarining tabiiy migratsiya yo'llarini kesib qo'yadi va ekotizimni buzadi." },
    { "id": "bp83", "story": "Zavod hududidan qattiq maishiy va zaharli qoldiqlar chiqadi. Zavod direktori ularni daryo qirg'og'idagi bo'sh yerga tashlab ustini tuproq bilan ko'mib tashlashni buyurdi.", "question": "Bahorda nima sodir bo'ladi?", "options": ["Chiqindilar chirib yo'qoladi", "Bahorgi yog'ingarchilik va daryo toshqini natijasida zaharli qoldiqlar yuvilib to'g'ridan-to'g'ri daryo suviga aralashadi va suvni zaharlaydi", "Atrof ko'kalamzorlashadi"], "answer_index": 1, "explanation": "To'g'ri! Suv havzalarining qirg'oqlariga har qanday chiqindi ko'mish o'ta xavfli va qonunan taqiqlangan harakatdir." },
    { "id": "bp84", "story": "Fermer dala zararkunandalariga qarshi dori sepishda doimo faqat bitta turdagi (eng arzon) kimyoviy preparatdan o'n yillab foydalandi.", "question": "Keyingi yillari dori hasharotlarga ta'sir qilmay qo'ydi, nega?", "options": ["Dori eskirgan", "Hasharotlarda mutatsiya yuz berdi, ular bu doriga chidamli bo'lib qoldi (rezistentlik). Endi ularni butunlay yo'q qilib bo'lmaydi", "Hasharotlar ko'paygan"], "answer_index": 1, "explanation": "To'g'ri! Bir xil doridan noto'g'ri foydalanish qishloq xo'jaligida 'super-zararkunandalar' paydo bo'lishiga olib keladi." },
    { "id": "bp85", "story": "Mamlakatda qog'oz ishlab chiqarish keskin ortdi va buning uchun ko'plab maxsus o'rmonlar kesildi.", "question": "Ekologlar odamlardan nimani iltimos qilishadi?", "options": ["Qog'ozni ko'proq sotib olishni", "Har bir qog'ozning ikkala tomonidan foydalanishni, eski qog'ozlarni (makulatura) tashlab yubormay qayta ishlashga topshirishni", "Faqat plastik ishlatishni"], "answer_index": 1, "explanation": "To'g'ri! Bir tonna qog'ozni qayta ishlash 17 ta yirik daraxtni kesilishdan asrab qoladi." },
    { "id": "bp86", "story": "Shaharda qalin quyuq tuman (smog) tushdi, shamol yo'q. Hukumat barcha zavodlarni 3 kunga vaqtincha to'xtatib turishga qaror qildi.", "question": "Bu qanday rejim deb ataladi?", "options": ["Qishki ta'til", "Noqulay meteorologik sharoitlar rejimi. Shamolsiz vaqtda zaharli gazlar havoda cho'kib, tarqalmay qoladi. Shuning uchun zavodlar faoliyati cheklanadi", "Iqtisodiy inqiroz"], "answer_index": 1, "explanation": "To'g'ri! Smog paytida tutunlar osmonga ko'tarilmaydi (inversiya yuz beradi), shu sababli ifloslantirishni to'xtatib turish hayotiy zaruratdir." },
    { "id": "bp87", "story": "Bir hovlida ari oqova suvni yig'ish uchun chuqur qazib (shambo), uni sementlamasdan qoldirishdi. Ichiga barcha iflos suvlar, yuvinish kukunlari to'kildi.", "question": "Ertasi kuni hovlidagi quduq (ichimlik suvi kachalkasi) suvining ta'mi o'zgardi, sababi nima?", "options": ["Quduq buzilgan", "Sementlanmagan chuqurdagi zaharli va kimyoviy oqova suvlar yer osti (sizot) suvlariga o'tib, ichimlik suvi qudug'iga yetib kelgan", "Yomg'ir suvi aralashgan"], "answer_index": 1, "explanation": "To'g'ri! Oqova chuqurlari (septiklar) albatta izolatsiya (beton) qilinishi shart, aks holda ular eng yaqin ichimlik suvi manbalarini zaharlaydi." },
    { "id": "bp88", "story": "Bog'bon daraxtlar qurimasligi uchun butun bog'ini qalin plyonka bilan yopdi va yerni asfalt qilib tashladi.", "question": "Daraxtlarga nima bo'ladi?", "options": ["Ular toza turadi", "Daraxtlar quriydi, chunki ularning ildizi tuproq orqali havodan nafas ololmay qoladi va yomg'ir suvi ildizga yetib bormaydi", "Yana ham qalinlashadi"], "answer_index": 1, "explanation": "To'g'ri! Daraxt atrofini beton yoki asfalt qilish uni tiriklayin bo'g'ish bilan tengdir." },
    { "id": "bp89", "story": "Sayyohlar dam olayotgan ko'l qirg'og'ida o'lgan oqqushlar va chig'anoqlar paydo bo'ldi. Havo toza, atrofda axlat yo'q edi, lekin suvdagi yosh bolalar tinimsiz quyoshdan himoyalovchi (sunscreen) kremlar surtishardi.", "question": "Oqqushlar nimadan o'lgan?", "options": ["Shunchaki kasallik", "Ba'zi quyosh kremlari tarkibidagi oksibenzon va zaharli moddalar suvga tushib suv ekotizimini (planktonlarni) zaharlagan, bu oqqushlarga o'tgan", "Quyosh nuri kuchli bo'lgan"], "answer_index": 1, "explanation": "To'g'ri! Ba'zi quyoshdan asrovchi vositalar suv hayvonlari uchun o'ta zaharli hisoblanadi (shuning uchun Eko-kremlar ishlab chiqarilmoqda)." },
    { "id": "bp90", "story": "Savdogar odamlarga Qizil kitobga kiritilgan yovvoyi hayvonlar (masalan kiyik) shoxlarini \"dori\" deb aldab qimmat narxda sota boshladi.", "question": "Bunday tibbiyot ekologiyaga qanday ta'sir qiladi?", "options": ["Tibbiyot rivojlanadi", "Soxta xalq tabobati yovvoyi hayvonlar qotilligini (brakonyerlikni) million marta tezlashtirib yuboradi va butun boshli turlarni yer yuzidan yo'q qiladi", "Ta'siri yo'q"], "answer_index": 1, "explanation": "To'g'ri! Ilmiy asoslanmagan \"shifobaxsh\" e'tiqodlar (masalan nosorog shoxi, yo'lbars suyagi) hayvonlar uchun eng katta fojiadir." },
    { "id": "bp91", "story": "Bir uy egasi barcha eskirgan dori-darmonlarni yig'ib hojatxonaga oqizib yubordi.", "question": "Nima uchun bu ish ekologik jinoyat?", "options": ["Quvurni tiqib qo'yadi", "Kanalizatsiya tozalash inshootlari dorilarni (antibiotiklarni) tozalay olmaydi. Dorilar daryoga borib u yerdagi baliqlarni xandaq qilib tashlaydi", "Faqat pul isrofi"], "answer_index": 1, "explanation": "To'g'ri! Dori-darmonlar faqat maxsus dorixonalarga yo'q qilish uchun topshirilishi yoki maxsus yondirilishi shart." },
    { "id": "bp92", "story": "Odamlar ekinlarni qushlar yemasligi uchun daladagi barcha qushlarni uymalashib o'ldirishdi (masalan, Xitoydagi chumchuqlar kampaniyasi).", "question": "Keyingi yili dalada nima bo'ldi?", "options": ["Hosil rekord darajada ko'paydi", "Ekinlarni hasharotlar (chigirtkalar, qurtlar) butunlay yeb bitirdi va mamlakatda dahshatli ocharchilik boshlandi", "Hech narsa bo'lmadi"], "answer_index": 1, "explanation": "To'g'ri! Tabiat zanjirida \"keraksiz\" halqa yo'q. Chumchuqlar ekinni yeganidan ko'ra minglab marta ko'proq hasharotlarni yer edi." },
    { "id": "bp93", "story": "Sanoat markazidan yuzlab kilometr uzoqda, baland tog'li ko'lda yashovchi baliqlarda og'ir metall (simob) topildi.", "question": "Simob u yerga qanday yetib keldi?", "options": ["Tog'da zavod bor", "Zavodlardan havoga ko'tarilgan simob bug'lari bulutlarga qo'shilib tog'largacha yetib borgan va kislotali yomg'ir / qor orqali ko'lga tushgan", "Baliqchilar olib kelgan"], "answer_index": 1, "explanation": "To'g'ri! Havo ifloslanishi chegara bilmaydi. Atmosfera oqimlari zaharlarni butun qit'alar bo'ylab tashiydi." },
    { "id": "bp94", "story": "Chaqaloqlar tagligi (Pampers) axlatxonaga tashlangach 500 yildan ortiq chiramay yotadi.", "question": "Ota-onalar tabiatni asrash uchun nima qilishi mumkin?", "options": ["Axlatni yoqish", "Qayta foydalanish mumkin bo'lgan, yuviladigan eko-tagliklardan (mato tagliklaridan) yoki tez chiriydigan bioplastik pamperslardan foydalanish", "Yerga ko'mish"], "answer_index": 1, "explanation": "To'g'ri! Zamonaviy bir martalik mahsulotlar (tagliklar, salfetkalar) sayyoramizni axlatga to'ldirmoqda, yechim - ko'p martalik muqobillarga o'tish." },
    { "id": "bp95", "story": "Shahar bog'idagi barcha xazonlar olib ketildi va o'tlar tap-taqir qilib o'rib olindi. Qish qattiq kelgach bahorda ko'plab qushlar o'lgani ma'lum bo'ldi.", "question": "Qushlar nega o'ldi?", "options": ["Ular issiqni yoqtiradi", "Xazonlar va maysalar ostida qushlar qishda yeydigan hasharotlar, urug'lar berkingan edi. Yer yalang'ochlanib qushlar ozuqasiz qoldi", "Kasal bo'lgan"], "answer_index": 1, "explanation": "To'g'ri! Bog'lardagi haddan ortiq \"tozalik\" tabiiy zanjirni buzadi, o'tlar ostidagi hasharotlar yovvoyi qushlar uchun yagona qishki ozuqadir." },
    { "id": "bp96", "story": "Korxona arzon paxta matosi (jinsi) ishlab chiqarish uchun juda katta miqdorda zaharli bo'yoqlar ishlatdi. Fabrika ishchilari esa saraton kasaliga chalindi.", "question": "Iste'molchi ekologiya uchun qanday yechim qilishi kerak?", "options": ["Kiyim kiymaslik", "Ekologik toza (organik paxtadan va tabiiy bo'yoqdan qilingan) kiyimlarni sotib olish (Eko-moda) va kamroq kiyim almashtirish (Slow fashion)", "Jinsi kiymaslik"], "answer_index": 1, "explanation": "To'g'ri! Fast fashion (tezkor moda) sayyoradagi eng katta ifloslantiruvchi sohalardan biri bo'lib, zaharli suv va qullar mehnatini talab qiladi." },
    { "id": "bp97", "story": "Bolalar qiziqish uchun qushlarning uyasini (tuxumlarini) ushlab, yana joyiga qo'yishdi.", "question": "Shu ish to'g'rimi?", "options": ["Ha, ular shunchaki ko'rishdi", "Yo'q, qushlar inson hidini (yoki uyasi buzilganini) sezib, o'z uyasiga qaytib kelmaydi va tuxumlar nobud bo'ladi", "Qushlar buni sezmaydi"], "answer_index": 1, "explanation": "To'g'ri! Yovvoyi hayvonlar bolasiga va uyasiga teginish ularni yetim qoldirish bilan tengdir." },
    { "id": "bp98", "story": "Katta ko'lda sayyohlar ko'paygach motorli qayiqlar tinimsiz u yoqdan bu yoqqa qatnay boshladi. Ko'l suvi tiniq bo'lsa-da, baliqlar ommaviy o'la boshladi.", "question": "Sababini aniqlang.", "options": ["Suv isib ketdi", "Motorli qayiqlardan chiqqan benzin, moylar (neft plyonkasi) suv yuzini qoplab oldi, natijada suvga kislorod o'tmay qoldi (Kislorod ochligi)", "Baliqlar cho'chidi"], "answer_index": 1, "explanation": "To'g'ri! Kichik miqdordagi neft plyonkasi ham suv yuzasida kislorod almashinuvini butunlay to'xtatib qo'yadi va suv jonivorlari bo'g'iladi." },
    { "id": "bp99", "story": "Shahardagi odamlar ishga har bir mashinada bittadan odam (faqat haydovchi) bo'lib qatnay boshlashdi.", "question": "Bu holatning zarari nimada va yechimi nima?", "options": ["Zarari yo'q", "Tirbandlik va havo ifloslanishi vahshiy darajaga chiqadi. Yechim: Jamoat transporti (avtobus, metro) yoki velosipeddan foydalanish, yoxud Carpooling (birga yurish) usuli", "Mashinani sekin haydash"], "answer_index": 1, "explanation": "To'g'ri! Bitta avtobus 40-50 ta yengil mashinaning o'rnini bosib, atmosferani yuzlab marta kamroq ifloslantiradi." },
    { "id": "bp100", "story": "O'quvchi \"Mening bitta plastik idishni axlatga tashlashimdan nima o'zgarardi, baribir hamma tashlayapti-ku\" deb o'yladi.", "question": "Ushbu fikrga ekologlarning javobi qanday?", "options": ["To'g'ri fikr", "\"Millionlab odamlar 'mening bitta o'zimdan nima o'zgarardi' deyishadi. Aksincha, global o'zgarishlar bitta insonning to'g'ri odati va o'zgarishidan boshlanadi. Sen boshla, atrofing o'zgaradi!\"", "Faqat jarima yechim"], "answer_index": 1, "explanation": "To'g'ri! Ekologik madaniyat shaxsiy mas'uliyatdan boshlanadi. Dengiz ham tomchilardan yig'iladi." }
]
"@

$newTermsStr = @"
[
    { "id": "bt81", "question": "Organik qishloq xo'jaligi nima?", "options": ["Traktordan foydalanmaslik", "Kimyoviy o'g'itlar, pestisidlar va GMO (geni o'zgartirilgan organizmlar) dan umuman foydalanmasdan tabiiy usulda oziq-ovqat yetishtirish", "Faqat meva ekish"], "answer_index": 1, "explanation": "To'g'ri! Organik mahsulotlar inson salomatligi va tuproq uchun eng xavfsiz oziq-ovqat hisoblanadi." },
    { "id": "bt82", "question": "E-waste (Elektron chiqindilar) tarkibidagi eng xavfli moddalar qaysilar?", "options": ["Temir va mis", "Qo'rg'oshin, simob, kadmiy, bariy", "Alyuminiy va rux"], "answer_index": 1, "explanation": "To'g'ri! Ushbu og'ir metallar asab tizimi, miya va buyraklar ishdan chiqishiga (saratonga) sabab bo'ladi." },
    { "id": "bt83", "question": "Karbonat neytralligi (Carbon neutral) maqsad qilingan yil qaysi?", "options": ["2030 yil", "2050 yil", "2100 yil"], "answer_index": 1, "explanation": "To'g'ri! BMT davlatlarni 2050 yilga kelib atmosferaga chiqarilayotgan karbonat hajmini tabiat yuta oladigan hajmga (Nolga) tushirishga chaqirgan." },
    { "id": "bt84", "question": "Gidroponika nima?", "options": ["Suv ostida suzish", "O'simliklarni tuproqsiz, faqat ozuqali suv eritmalari yordamida (issiqxonalarda) yetishtirish usuli", "Suv tozalash usuli"], "answer_index": 1, "explanation": "To'g'ri! Gidroponika suvni va yerni juda kuchli tejovchi zamonaviy ekologik dehqonchilik turidir." },
    { "id": "bt85", "question": "Iqlim skeptiklari (Climate deniers) kimlar?", "options": ["Ekologlar", "Global isish va iqlim o'zgarishi inson aybi bilan yuz berayotganini rad etuvchi (bunga ishonmaydigan) odamlar va korporatsiyalar", "Suv muhojirlari"], "answer_index": 1, "explanation": "To'g'ri! Ko'pincha qazilma yoqilg'i kompaniyalari ataylab shunday yolg'on tashviqotlar olib borishadi." },
    { "id": "bt86", "question": "Bioxilma-xillik indeksi nimani anglatadi?", "options": ["Hayvonlar narxini", "Ma'lum bir hududdagi turlarning soni va ularning miqdoriy tengligini ko'rsatuvchi matematik (ekologik) o'lchov", "Daraxtlar balandligini"], "answer_index": 1, "explanation": "To'g'ri! Indeks qancha yuqori bo'lsa, ekotizim shuncha barqaror va boy sanaladi." },
    { "id": "bt87", "question": "Brakish suv zonalarining (Estuariylarning) ekologik ahamiyati nimada?", "options": ["Hech qanday ahamiyati yo'q", "Chuchuk va sho'r suv aralashgan bu hududlar dunyodagi eng mahsuldor ekotizimlar bo'lib, ko'plab baliqlarning 'chaqaloqxonasi' hisoblanadi", "Tuz qazib olish joyi"], "answer_index": 1, "explanation": "To'g'ri! Daryo dengizga quyiladigan joylar bioxilma-xillik uchun nihoyatda qimmatli hududlardir." },
    { "id": "bt88", "question": "Mikroplastiklarning o'lchami qancha bo'ladi?", "options": ["10 sm", "5 millimetrdan kichik bo'lgan barcha plastik zarralari (ko'zga ko'rinmaydigan darajagacha)", "1 metr"], "answer_index": 1, "explanation": "To'g'ri! Ular suv va tuproq orqali oziq-ovqatga osongina kirib oladi." },
    { "id": "bt89", "question": "Agro-o'rmonchilik (Agroforestry) nima?", "options": ["O'rmonni buzib dala qilish", "Bitta yerning o'zida ham daraxtlar o'stirish, ham qishloq xo'jaligi ekinlari ekish (masalan, mevali bog' ostida bug'doy ekish) tizimi", "Faqat meva terish"], "answer_index": 1, "explanation": "To'g'ri! Bu usul yer unumdorligini oshiradi va tuproqni himoya qiladi." },
    { "id": "bt90", "question": "Permakultura (Permaculture) nima?", "options": ["Yerni haydash turi", "Tabiiy ekotizimlardan nusxa ko'chirgan holda, inson va tabiat o'zaro uyg'unlikda yashaydigan (o'zini-o'zi tiklaydigan) bog'lar, uylar va fermalar yaratish san'ati", "Bino qurish"], "answer_index": 1, "explanation": "To'g'ri! Permakultura - \"Doimiy qishloq xo'jaligi va madaniyat\" so'zlaridan yasalgan bo'lib, tabiat qonunlariga asoslanadi." },
    { "id": "bt91", "question": "Metan qayerdan ko'p ajraladi?", "options": ["Zavodlardan", "Asosan chorvachilik, guruch maydonlari, neft qazib olish va axlatxonalardagi organik chiqindilarning chirishidan", "Daraxtlardan"], "answer_index": 1, "explanation": "To'g'ri! Metan (CH4) global isishni kuchaytiruvchi 2-raqamli, lekin karbonatdan ancha kuchliroq issiqxona gazidir." },
    { "id": "bt92", "question": "Ekosistemik xizmatlar (Ecosystem services) nima?", "options": ["Ekologlarning ishi", "Tabiat tomonidan insoniyatga bepul beriladigan bebaho ne'matlar (havoni tozalash, suvni filtrlash, ekinlarni changlantirish, iqlimni yumshatish)", "Zavod xizmati"], "answer_index": 1, "explanation": "To'g'ri! Odamlar ushbu xizmatlarning iqtisodiy qadrini tushunib yetishgandagina tabiatni asray boshlashadi." },
    { "id": "bt93", "question": "Inversiya hodisasi (havoda) qanday xavf tug'diradi?", "options": ["Yomg'ir yog'diradi", "Issiq havo qatlami sovuq havoni pastda bosib qolishi natijasida zavod tutunlari osmonga ko'tarila olmaydi, shahar zaharli tutunga (smog) g'arq bo'ladi", "Shamollar paydo qiladi"], "answer_index": 1, "explanation": "To'g'ri! Qish oylaridagi shamolsiz kunlarda shaharlarni bosib turadigan tuman va tutun (smog) aynan inversiya sabablidir." },
    { "id": "bt94", "question": "Fossil fuels (Qazilma yoqilg'ilar) ga nimalar kiradi?", "options": ["O'tin, tappi", "Ko'mir, neft va tabiiy gaz", "Uran va quyosh"], "answer_index": 1, "explanation": "To'g'ri! Millionlab yillar oldin ko'milgan qoldiqlardan hosil bo'lgan bu yoqilg'ilar atmosferaga ulkan miqdorda zahar (uglerod) chiqaradi." },
    { "id": "bt95", "question": "Dengiz sathi ko'tarilishining asosiy 2 ta sababi qaysi?", "options": ["Baliqlar ko'payishi va shamol", "Muzliklarning erishi hamda isish oqibatida suv hajmining kengayishi (Termal kengayish)", "Yomg'ir va qor"], "answer_index": 1, "explanation": "To'g'ri! Dengiz sathi har yili bir necha millimetrga o'sib, orollarni suv ostida qoldirmoqda." },
    { "id": "bt96", "question": "Ozon teshigi muammosi hozirgi kunda qanday holatda?", "options": ["Dahshatli kattalashmoqda", "Monreal bayonnomasi tufayli (freonlar taqiqlangani sababli) asta-sekin kichrayib tiklanmoqda", "Umuman yo'qolgan"], "answer_index": 1, "explanation": "To'g'ri! Ozon muammosi xalqaro kelishuvlarning eng muvaffaqiyatli namunasi hisoblanadi: insoniyat xatoni to'g'rilashni boshlagan." },
    { "id": "bt97", "question": "Upcycling (Ap-saykling - Yuqori qayta ishlash) nima?", "options": ["Axlatni ko'mish", "Eski va keraksiz chiqindidan uning dastlabki qiymatidan ham qimmatroq va foydaliroq yangi narsa yaratish san'ati (masalan, eski shinalardan mebel yasash)", "Qog'oz qayta ishlash"], "answer_index": 1, "explanation": "To'g'ri! Upcycling resurslarni isrof qilishni to'xtatuvchi ijodiy va ekologik yondashuvdir." },
    { "id": "bt98", "question": "Ekologik monitoringning eng ilg'or usuli qaysi?", "options": ["Havo ishlash", "Sun'iy yo'ldoshlar (Kosmik monitoring) va dronlar yordamida har kuni masofadan turib Yer yuzini va o'rmonlarni kuzatish", "Piyoda aylanib chiqish"], "answer_index": 1, "explanation": "To'g'ri! Geofazoviy texnologiyalar butun Yer sharidagi ekologik holatni real vaqtda ko'rsatib turadi." },
    { "id": "bt99", "question": "Veganizmning (go'sht va chorva mahsulotlaridan to'liq voz kechishning) ekologik argumenti nima?", "options": ["Hayvonlar achinarli ekani", "Go'sht va sut sanoati global isish, o'rmonlar qisqarishi va suv tanqisligining bosh sababchisidir, shuning uchun o'simlik dietasi sayyorani asraydi", "Faqat salomatlik"], "answer_index": 1, "explanation": "To'g'ri! Hisob-kitoblarga ko'ra, insoniyat o'simlik ozuqasiga o'tsa, qishloq xo'jaligi maydonlarining 75% i o'rmonlarga qaytarilishi mumkin." },
    { "id": "bt100", "question": "Suksessiya (Ekologik o'rin almashish) nima?", "options": ["Yil fasllari o'zgarishi", "Bir ekotizimning (masalan ko'lning) vaqt o'tishi bilan tabiiy ravishda o'zgarib, mutlaqo boshqa ekotizimga (masalan botqoqqa, so'ngra o'rmonga) aylanishi", "Odamlarning ko'chishi"], "answer_index": 1, "explanation": "To'g'ri! Suksessiya tabiatdagi o'z-o'zini qayta qurish va tiklanishning uzoq muddatli qonuniyatidir." }
]
"@

$newPenaltiesStr = @"
[
    { "id": "bpn81", "question": "Suv omborlarining suvini bulg'atgan korxonaga qanday talab qo'yiladi?", "options": ["Jarima to'lash kifoya", "Yetkazilgan zarar to'liq undiriladi hamda suv ob'yektining holatini o'z hisobidan tiklashi shart qilib qo'yiladi", "Faqat yopiladi"], "answer_index": 1, "explanation": "To'g'ri! Qonunchilikka ko'ra tabiatni ifloslantirgan korxona oqibatlarni to'liq bartaraf etishga majbur." },
    { "id": "bpn82", "question": "Davlat qo'riqxonasi (Zakaznik, Qo'riqxona) hududida sayyohlarning chodir tikib tunab qolishi, olov yoqishi mumkinmi?", "options": ["Mumkin", "Qat'iyan man etiladi va ekologik rejimni buzganlik uchun jarima solinadi", "Ruxsatnoma olib qilsa bo'ladi"], "answer_index": 1, "explanation": "To'g'ri! Qo'riqxonalar odam dam oladigan joy emas, ular faqatgina yovvoyi tabiatning daxlsizligi uchun ajratilgan." },
    { "id": "bpn83", "question": "Qurilish kompaniyasi qurilish qumini qazib olish uchun tog' yonbag'rini o'pirib (buzib) tashlasa qanday jazo ko'zda tutilgan?", "options": ["Arzon jarima", "Yerni buzish (Eroziyaga sabab bo'lish) va nodir tabiat manzarasiga zarar yetkazganlik uchun jinoiy javobgarlik belgilanadi", "Jazo yo'q"], "answer_index": 1, "explanation": "To'g'ri! Tog' va daryolar o'zanini buzish hudud ekologiyasiga, jumladan qishloqlarga xavf tug'diradi." },
    { "id": "bpn84", "question": "Ko'chada, mahallada, umumiy ovqatlanish joylarida axlat qutilari bo'la turib atrofga, yerga sigaret qoldig'i (bichok), qog'oz tashlaganlik uchun O'zbekistonda chora bormi?", "options": ["Yo'q, hamma tashlaydi", "Ha, Jamoat joylarida chiqindi tashlash qat'iyan man etiladi va BHMning yarim baravaridan 3 baravarigacha jarima solinadi", "Faqat yosh bolalarga jarima bor"], "answer_index": 1, "explanation": "To'g'ri! Sigaret qoldiqlari tabiatda chirimaydi, ularni ko'chaga tashlash madaniyatsizlik va ma'muriy huquqbuzarlikdir." },
    { "id": "bpn85", "question": "Noyob yirtqich qushlarni (masalan Itelg'i, Lochin) cho'ldan tutib, Arab davlatlariga sotishga uringan qabih shaxslar...?", "options": ["Faqat qushlar olinadi", "Jinoiy guruh sifatida baholanadi (kontrabanda) va hayvonot dunyosiga nihoyatda o'ta yirik miqdorda (milliardlab so'm) zarar yetkazilgan deb topilib uzoq yillarga qamaladi", "Soliq to'laydi"], "answer_index": 1, "explanation": "To'g'ri! Yirtqich qushlar O'zbekiston Qizil kitobiga kirgan o'ta nodir genofond bo'lib, ularni o'g'irlash tabiat oldidagi qotillikdir." },
    { "id": "bpn86", "question": "Sanoat korxonasi chiqindilarni qayta ishlash texnologiyasiga pul sarflamay, barcha zaharli suyuqliklarni tunda hech kim ko'rmaganda anhorga to'kib kelganligi isbotlansa nima bo'ladi?", "options": ["Hech kim ko'rmagan", "Atrof muhitga qasddan ziyon yetkazganligi va aholi sog'ligiga tajovuz qilganligi isbotlanib, korxona xatlovga olinadi, rahbarlari qamaladi", "Rahbar ishdan olinadi"], "answer_index": 1, "explanation": "To'g'ri! Yashirin ekologik jinoyatlar eng og'ir turdagi huquqbuzarliklardan hisoblanadi." },
    { "id": "bpn87", "question": "Ko'chadagi, uyi yonidagi ko'p yillik chinor va tut daraxtlariga qurilish mollarini, beton plitalarini suyab yoki mixlab qo'yish (daraxtga zarar) jazolanadimi?", "options": ["Yo'q, u o'zining ko'chasi", "Ha, O'simliklar olamiga shikast yetkazganligi (MJtK 79-modda) uchun ma'muriy jarimaga tortiladi", "Faqat ko'chada turibdi"], "answer_index": 1, "explanation": "To'g'ri! Daraxtga har qanday mexanik shikast yetkazish, u ko'chada yoki idora oldida bo'lishidan qat'iy nazar jazolanadi." },
    { "id": "bpn88", "question": "Avtomobil yuvish shoxobchasi (moyka) davlat ichimlik suvi tarmog'iga yashirincha (o'zboshimchalik bilan, hisoblagichsiz) ulanib, ichimlik suvi bilan moshina yuvsa qanday chora ko'riladi?", "options": ["Faqat hisoblagich qo'yiladi", "Ichimlik suvidan isrofgarona va ruxsatsiz foydalanganlik, resurslarni talon-taroj qilganlik aybi bilan tarmoqdan uziladi va katta jarima tortiladi", "Soliq to'laydi"], "answer_index": 1, "explanation": "To'g'ri! Chuchuk va ichimlik suvi taqchil resurs bo'lib, undan avtomobil yuvishda foydalanish jinoyat sanaladi (Texnik suvdan foydalanish shart)." },
    { "id": "bpn89", "question": "Tuproq unumdorligini buzganlik va qishloq xo'jaligi yerlaridan noto'g'ri foydalanib yerning sho'rlanishi va degradatsiyasiga sabab bo'lgan fermer xo'jaligi...", "options": ["O'zining yeri-ku", "Yer qonunchiligini buzganligi uchun jarimaga tortiladi va yer (ijara shartnomasi) undan olib qo'yilishi mumkin", "Jazo yo'q"], "answer_index": 1, "explanation": "To'g'ri! Yer milliy mulk, unga nisbatan e'tiborsizlik qilish iqtisodiy va ekologik sabotajdek gap." },
    { "id": "bpn90", "question": "Uy yoki restoran yonidagi shovqin normasi belgilangan bo'lib (masalan tungi vaqtda), undan oshgan ovoz balandligini ekologlar nima orqali o'lchaydilar?", "options": ["Quloq bilan", "Shumo-mer (Shovqin o'lchovchi maxsus datchiklar) yordamida desibellarda o'lchaydilar. Norma oshsa qat'iy choralar ko'riladi", "O'lchash imkonsiz"], "answer_index": 1, "explanation": "To'g'ri! Zamonaviy ekologiya nazoratida akustik ifloslanish apparatlar yordamida aniq ko'rsatib beriladi." },
    { "id": "bpn91", "question": "Zavod gaz tozalash filtrlari buzilgan holatda ishlab chiqarayotgan tutun miqdori Ekologik me'yordan oshib ketsa, nega qattiq jazo ko'riladi?", "options": ["Odamlarga kasallik yuqadi", "Normadan ortiq (PDK) havoga tashlangan zaharli moddalar soniga qarab (tonnasiga) tabiatga yetkazilgan millionlab (yoki milliardlab) moddiy zarar jarimadan tashqari undirib olinadi", "Faqat jarima solinadi"], "answer_index": 1, "explanation": "To'g'ri! Jarima faqat qonunni buzganning jazosi, Zarar (kompensatsiya) esa u havoga chiqargan gaz uchun davlatga to'lanadigan to'lovdir." },
    { "id": "bpn92", "question": "Noyob hayvonlarni ko'paytirish (pitomniklar) fermasi egasi pitomnikdagi qafasdan yirtqich hayvon (ayiq) larning qochib ketishiga beparvolik qilsa va ular aholiga xavf tug'dirsa kim javobgar bo'ladi?", "options": ["Ayiq javobgar", "Ferma egasi yovvoyi hayvonlarni saqlash xavfsizligi qoidalarini buzganlik va ehtiyotsizlik uchun Jinoyat kodeksi bo'yicha javobgarlikka tortiladi", "Javobgarlik yo'q"], "answer_index": 1, "explanation": "To'g'ri! Xavfli yovvoyi hayvonlarni saqlovchilar doimiy nazorat va o'ta qat'iy xavfsizlik ta'minlashga majburdirlar." },
    { "id": "bpn93", "question": "Davlat o'rmon fondiga kiruvchi to'qayzorlarda ruxsatsiz daraxtlarni kesib, u yerni shudgor qilib ekin ekkan shaxslar...?", "options": ["Hosilni olib ketadi", "Jinoiy javobgarlikka tortiladi, bino-inshootlari buziladi va O'rmon xo'jaligiga yetkazilgan millionlab moddiy ziyon undiriladi", "Yerni o'zlashtiradi"], "answer_index": 1, "explanation": "To'g'ri! O'rmon yerlari faqat davlat mulki bo'lib qoladi, u yerda yer o'zlashtirish o'g'rilikdir." },
    { "id": "bpn94", "question": "Kasbi ovchi (Litsenziyali) bo'lgan shaxs Qizil kitobga kirgan Arxarni (tog' qo'yini) ruxsatsiz otib qo'ysa nima bo'ladi?", "options": ["Kechiriladi, u ovchi", "Kasbidan qat'iy nazar Qizil kitob turlarini ruxsatsiz (kvotasiz) otish Jinoiy Kodeks moddasi sanaladi, uning miltig'i musodara qilinadi va u qamoq jazosiga hukm qilinishi mumkin", "Faqat litsenziyasi olinadi"], "answer_index": 1, "explanation": "To'g'ri! Qizil kitob turlariga nisbatan har qanday noqonuniy ov qat'iyan man etiladi, ularning maqomi ovchilar tomonidan yaxshi bilinishi shart." },
    { "id": "bpn95", "question": "Suv tubidagi zaharli balchiq yoki loyni olib, uni shunchaki qo'shni ekin maydoniga tashlagan meliorator-quruvchi javobgarlikka tortiladimi?", "options": ["Yo'q, u ishni bajardi", "Ha, zaharli balchiq (masalan, og'ir metallar to'plangan loy) tuproqni kuchli zaharlagani uchun u Ekologik xavfsizlik qoidalarini buzishda ayblanadi", "Loy ekinlarga foyda"], "answer_index": 1, "explanation": "To'g'ri! Chiqindi balchiqlar ko'pincha zaharli qoldiqlar (pestisidlar) ni o'zida saqlaydi, ularni ko'r-ko'rona yerga yoyish xavflidir." },
    { "id": "bpn96", "question": "Agar biror korxona havoga tasodifan yirik miqdorda xavfli zahar (masalan ammiak yoki xlor) chiqarib yuborsa va ekologiya qo'mitasidan bu haqda yashirsa (xabar bermasa) nima bo'ladi?", "options": ["Tekshirmasa bilishmaydi", "Avariya (halokat) holati haqida hukumat va aholiga axborot bermaslik, favqulodda vaziyatni yashirish eng og'ir jinoyatlardan hisoblanadi (Jk 196)", "Korxona sir saqlashga haqli"], "answer_index": 1, "explanation": "To'g'ri! Har qanday ekologik favqulodda vaziyatni yashirish aholi hayotiga qasddan qilingan xavf sifatida baholanadi." },
    { "id": "bpn97", "question": "Sanoat oqova suvlari tarkibidagi og'ir metallar miqdorini doimiy oshirib yuboradigan to'qimachilik (kraska) sexlariga davlat qanday ta'sir chorasi qo'llaydi?", "options": ["Faqat ogohlantiradi", "Sexning faoliyati yopiladi. Zararli moddalarni filtrlaydigan maxsus biologik va kimyoviy (Lokal) tozalash inshootlarini to'liq ishga tushirmagunicha faoliyatiga ruxsat berilmaydi", "Boshqa joyga ko'chiriladi"], "answer_index": 1, "explanation": "To'g'ri! Bo'yoq (to'qimachilik) sexlari suvni eng ko'p zaharlovchilardir, ularga nisbatan nazorat juda qat'iy." },
    { "id": "bpn98", "question": "O'zbekistonda yovvoyi lola (Qizil kitobdagi turlar) ni ildizi bilan yulib bolalariga o'ynagani bergan fuqaro \"bilmasdan\" qilgani uchun jazodan qutuladimi?", "options": ["Ha, bilmagan", "Qonunni bilmaslik javobgarlikdan ozod qilmaydi. Yo'q qilingan lola soniga qarab zarar hisoblanadi va u ma'muriy javobgarlikka (katta jarimaga) tortiladi", "Bolasi yulsa qutuladi"], "answer_index": 1, "explanation": "To'g'ri! Tabiat qonunchiligi qat'iydir, har bir noqonuniy yulish jinoyatga sheriklikdir." },
    { "id": "bpn99", "question": "Shaharsozlikda ekologik qoidaga asosan, agar qurilish firmasi ko'chada daraxt ekadigan bo'lsa (kompensatsiya tarzida) kim uni parvarish qiladi?", "options": ["Hech kim, tabiat o'stiradi", "Qurilish kompaniyasi u ko'chatlarni ekishi, sug'orish tizimini (masalan tomchilatib) o'rnatishi va kamida 3 yil kafolatli parvarish qilib berishi qonun bilan mustahkamlangan", "Hokimiyat"], "answer_index": 1, "explanation": "To'g'ri! Shunchaki ekib tashlab ketish emas, uni ko'kartirish hozirgi kunning qat'iy davlat talabidir." },
    { "id": "bpn100", "question": "Qonun bo'yicha Ekologik qoidabuzarliklarni fotovideofiksatsiya orqali (Eko-nazorat botiga yoki portalga) yuborgan oddiy fuqarolar qanday taqdirlanadi?", "options": ["Rahmat aytiladi", "Huquqbuzardan undirilgan jarima miqdorining 15-20% i miqdorida (pul ko'rinishida) xabar bergan shaxs (jamoatchi ekonazoratchi) hisobiga mukofot tariqasida o'tkazib beriladi", "Hech narsa berilmaydi"], "answer_index": 1, "explanation": "To'g'ri! Bu davlat tomonidan tabiat muhofazasiga jamoatchilikni (fuqarolarni) faol jalb qilishning zamonaviy va samarali tizimidir!" }
]
"@

$newTrueFalseStr = @"
[
    { "id": "btf81", "question": "Plastik idishlarni tashlab yubormaslik uchun ularni ochiq ko'chada yoki uyda olovda yoqish, eng xavfsiz va ekologik toza yo'ldir.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Plastikni ochiq yoqish zaharli 'Dioksin' kabi havoni ifloslantiruvchi moddalarni ishlab chiqaradi. Eng toza usul bu uni qayta ishlashga (Recycling) topshirishdir." },
    { "id": "btf82", "question": "Eski dori-darmonlarni, kimyoviy yuvish vositalarini kanalizatsiya tizimiga yoki oddiy axlatxonaga tashlash suv ekotizimini zaharlashda katta xavf tug'dirmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Suv tozalash inshootlari kimyoviy dori va zaharlarni filtrlashga moslashmagan. Ular oqova suv orqali daryolarga tushib butun ekotizimni izdan chiqaradi." },
    { "id": "btf83", "question": "Uy elektr asboblari o'chirilgan, lekin rozetkaga tiqilgan (Standby) holatida turganda ham yashirincha ko'p miqdorda elektr energiyasini (Vampir energiya) sarflaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Kompyuter, televizor va zaryadlovchilar o'chirilgan bo'lsa-da energiya yeyishda davom etadi. Bu butun dunyo bo'ylab har yili yuzlab AESlarning bekorga ishlashiga olib kelmoqda." },
    { "id": "btf84", "question": "Faqat birgina insonning energiya, suv va qog'ozni tejashi sayyoradagi global isish jarayoniga umuman ijobiy ta'sir ko'rsata olmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Aynan har bir individning shaxsiy tanlovi va ongli harakatlari jamiyatda eko-madaniyatni shakllantiradi. Millionlab to'g'ri 'bir kishi'lar iqlim o'zgarishini to'xtatuvchi asosiy kuchdir." },
    { "id": "btf85", "question": "Mikroplastiklar hozirda okeandagi deyarli barcha baliqlarning va ularni iste'mol qiluvchi odamlarning oshqozon-ichak trakti, hatto qoniga ham yetib borgan.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Mikroplastik va nanoplastik zarralari shu qadar kichikki, ular suv aylanish zanjiri orqali ozuqa zanjirining eng yuqori pog'onasidagi inson tanasida o'rnashib olmoqda." },
    { "id": "btf86", "question": "Bioxilmaxillik faqat o'rmonlar uchun muhim, insoniyatning qishloq xo'jaligi uchun uning mutlaqo ahamiyati yo'q.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Agar tabiatdagi yovvoyi changlatuvchilar (asalarilar, qushlar, hasharotlar) hamda tuproq mikroorganizmlari qirilib ketsa, insoniyat ekinlardan hosil ololmay qoladi va ochlik boshlanadi." },
    { "id": "btf87", "question": "Issiqxona effekti (Greenhouse effect) asli tabiat uchun zararli emas, u sayyorani muzlab qolishdan saqlab turuvchi me'yoriy mexanizmdir, xavf uning haddan ortiq kuchayib ketishidadir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Atmosferada bir oz CO2 va issiqxona gazlari bo'lmaganda edi, Yerning harorati -18 Selsiyni tashkil etib, sayyora o'lik muz qatlamiga aylangan bo'lar edi. Insoniyat bu gazlarni keragidan yuz marta ko'paytirib yubormoqda xolos." },
    { "id": "btf88", "question": "Shaharlarda keng yaproqli daraxtlarni emas, balki ignabargli archalarni ko'p ekish yozning issiq (dim) kunlarida haroratni kuchli mo'tadillashtiradi va havoni ko'proq tozalaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Keng yaproqli daraxtlar (chinor, tut) o'zining katta barg maydoni hisobiga qalin soya tashlaydi va yozda konditsioner kabi namlik tarqatib shaharni sovutadi. Archalar bunday xususiyatga ega emas." },
    { "id": "btf89", "question": "Qizil kitobga kiritilgan o'simlikni emas, faqat uning bargini yoki urug'ini terish qonuniy huquqbuzarlik sanalmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Noyob o'simlik turlarining urug'i, guli, qismi yoki ildizini yig'ib olish turning tabiiy ko'payishiga qasddan qilingan xavf sifatida baholanib, jarima va zarar undirilishiga asos bo'ladi." },
    { "id": "btf90", "question": "Yovvoyi tabiat qo'yniga (tog'lar, o'rmonlarga) dam olishga borganda pleyer yoxud baland ovozda musiqa yoqish hayvonlarning ko'payish davrini izdan chiqaradigan \"shovqin (akustik) ifloslanish\" sanaladi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Baland sun'iy shovqinlar yovvoyi qushlarni va sut emizuvchilarni qo'rqitadi, ularning inlari (tuxumlari) ni tashlab qochishiga yoki ozuqa topa olmasligiga (aloqa uzilishiga) sabab bo'ladi." },
    { "id": "btf91", "question": "Qishloq xo'jaligida tomchilatib sug'orish tizimi faqatgina suvni tejash uchungina ishlatiladi, uning hosildorlikka va tuproqqa aloqasi yo'q.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Tomchilatib sug'orish suvni 50-70% tejash bilan birga, tuproq eroziyasi va sho'rlanishini to'xtatadi. Shuningdek o'g'it to'g'ri ildizga yetib borgani uchun hosildorlikni 2-3 barobarga oshiradi." },
    { "id": "btf92", "question": "Okeanlardagi marjon qoyalari (Riflar) dunyo okeani bioxilma-xilligining eng ko'p (qariyb 25%) qismini o'zida saqlab turuvchi suv osti \"tropik o'rmonlari\" hisoblanadi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Garchi marjon qoyalari okean tubining juda kichik maydonini egallasa-da, ularsiz butun dengiz ekotizimi va millionlab baliq turlari qirilib ketadi. Hozirda kislotali suv tufayli ular oqarib o'lmoqda." },
    { "id": "btf93", "question": "Agar birorta kompaniya yoki korxona o'z faoliyatida tabiatni asrash choralarini (Green Technologies) ishlatsa, u faqat xarajatga tushadi va hecham daromad ko'rmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Ekologik toza (Yashil) iqtisodiyot uzoq muddatda energiya va xom-ashyoni (chiqindini qayta ishlash hisobiga) juda katta miqdorda tejaydi, jarimalardan qutqaradi va zamonaviy bozorda xaridorlar ishonchini qozonadi." },
    { "id": "btf94", "question": "Daraxt ekish tabiatni qutqarishdagi eng yaxshi amaldir, ammo iqlim va tuproq sharoitiga mos kelmaydigan begona (invaziv) turdagi daraxtlarni ekish foydadan ko'ra ko'proq ziyon keltiradi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Mahalliy ekotizimga moslashmagan, ko'p suv ichadigan (masalan pavloniya) yoxud mahalliy florani siqib chiqaradigan (invaziv) daraxtlarni ommaviy ekish ekologik fojia (monokultura) ga aylanishi mumkin." },
    { "id": "btf95", "question": "Qayta tiklanuvchi energiya (Shamol, quyosh, geotermal) manbalari sayyorada zaharli issiqxona gazlarini (CO2) ishlab chiqarmaydigan (nol darajali) haqiqiy yashil energetikadir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Shamol va quyosh panellari o'z ish jarayonida havoga zahar purkamaydi (garchi ularning panellari ishlab chiqarilishida qisman zahar chiqsa ham). Ular ko'mir va gaz stansiyalariga nisbatan yuz barobar toza usuldir." },
    { "id": "btf96", "question": "Insoniyat o'z tarixi davomida tabiatdagi hayvon turlarining genofondiga va ularning populyatsiyasiga hech qanday yirik ta'sir o'tkazmagan.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Inson faoliyati (Antropogen omil) tufayli so'nggi 50 yilda Yerdagi yovvoyi hayvonlar va qushlarning umumi populyatsiyasi qariyb 60-70% ga yo'q bo'lib ketganligi (Oltinchi ommaviy qirilish) Ilmiy jihatdan tasdiqlangan." },
    { "id": "btf97", "question": "Cho'l mintaqasida o'rmon yaratishning iloji yo'q, chunki daraxtlar faqat sernam va yomg'irli joylardagina yirik o'rmon hosil qila oladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Cho'lning o'ziga xos (Saksovul, qandim kabi daraxt va butalardan tashkil topgan) betakror o'rmonlari bo'ladi. Ular quruq iqlimga moslashgan bo'lib cho'llanish va qum ko'chishini tutib qoluvchi kuchli 'Cho'l o'rmonlari'dir." },
    { "id": "btf98", "question": "O'zbekistonda yovvoyi hayvonlar ovlanadigan qonuniy ruxsatnomalar (kvotalar) faqat davlat byudjetini to'ldirish maqsadida qo'llaniladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Ov kvotalari eng birinchi navbatda tabiatda qaysidir jonivorning haddan ortiq ko'payib (nazoratsiz populyatsiya) o'rmonga ziyon keltirmasligini nazorat qilish va bio-muvozanatni ushlab turish uchun (Ilmiy xulosalar asosida) beriladi." },
    { "id": "btf99", "question": "Avtomobil oynasidan ko'chaga mayda sigaret qoldig'i (Bichok) ni tashlash kichik huquqbuzarlik bo'lishi bilan birga, sayyoradagi eng ko'p tarqalgan zaharli plastik qoldiqlar (mikroplastik va nikotin filtri) ifloslanishining bosh sababchisidir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Sigaret filtrlari qog'oz emas, ularda zaharli kimyoviy elementlar bilan to'yingan plastik tolalari mavjud. Ular chirishi uchun o'nlab yillar kerak bo'ladi va ular suvlarni kuchli zaharlaydi." },
    { "id": "btf100", "question": "Men yashab turgan uydagi toza ichimlik suvi (vodoprovod) doimo va hech qachon tugamaydigan mo'l-ko'l manbadan kelib turadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Chuchuk ichimlik suvi Yer yuzidagi eng taqchil (hamma suvning bor-yo'g'i 1% i ichishga yaroqli) resurs bo'lib, iqlim isishi va muzliklar erishi hisobiga hozirgi kunda butun dunyoda, ayniqsa bizning mintaqada uning zaxiralari shiddat bilan tugab bormoqda." }
]
"@

$newQ = ConvertFrom-Json -InputObject $newQuizzesStr
$newP = ConvertFrom-Json -InputObject $newPuzzlesStr
$newT = ConvertFrom-Json -InputObject $newTermsStr
$newPn = ConvertFrom-Json -InputObject $newPenaltiesStr
$newTf = ConvertFrom-Json -InputObject $newTrueFalseStr

$jsonObj.quizzes += $newQ
$jsonObj.puzzles += $newP
$jsonObj.terms += $newT
$jsonObj.penalties += $newPn
$jsonObj.truefalse += $newTf

$jsonObj | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonFile -Encoding UTF8
