$ErrorActionPreference = "Stop"

$jsonFile = "C:\Users\Akobir\.gemini\antigravity\scratch\eco_law_bot\data\quiz.json"
$jsonStr = Get-Content -Raw -Path $jsonFile -Encoding UTF8
$jsonObj = ConvertFrom-Json -InputObject $jsonStr

$newQuizzesStr = @"
[
    { "id": "bq21", "question": "Yerdagi chuchuk suv zaxirasining katta qismi qayerda joylashgan?", "options": ["Daryolarda", "Ko'llarda", "Muzliklarda", "Yer ostida"], "answer_index": 2, "explanation": "To'g'ri! Yerdagi chuchuk suvning qariyb 70% dan ortig'i Antarktida va Grenlandiya muzliklarida joylashgan." },
    { "id": "bq22", "question": "Tabiatda moddalar aylanishini harakatga keltiruvchi asosiy energiya manbai nima?", "options": ["Shamol", "Quyosh energiyasi", "Yerning ichki issiqligi", "Okean oqimlari"], "answer_index": 1, "explanation": "To'g'ri! Biosferadagi barcha biologik va kimyoviy aylanishlar Quyosh nuri energiyasi hisobiga yuz beradi." },
    { "id": "bq23", "question": "Qaysi xalqaro bitim issiqxona gazlarini kamaytirishga qaratilgan?", "options": ["Monreal bayonnomasi", "Kioto bayonnomasi", "SITES konvensiyasi", "Bazel konvensiyasi"], "answer_index": 1, "explanation": "To'g'ri! Kioto bayonnomasi (1997) atmosfera havosiga issiqxona gazlarini chiqarishni cheklash bo'yicha xalqaro shartnomadir." },
    { "id": "bq24", "question": "O'zbekistonda eng katta maydonni qaysi tabiat zonasi egallaydi?", "options": ["Cho'l va chala cho'llar", "Tog' o'rmonlari", "To'qayzorlar", "Yaylovlar"], "answer_index": 0, "explanation": "To'g'ri! O'zbekiston hududining qariyb 70-80 foizi cho'l, chala cho'l va dashtlardan iborat." },
    { "id": "bq25", "question": "Ozon tuynugi birinchi marta qayerda kuzatilgan?", "options": ["Avstraliya ustida", "Afrika ustida", "Antarktida ustida", "Shimoliy qutb ustida"], "answer_index": 2, "explanation": "To'g'ri! 1980-yillarda ingliz olimlari Antarktida ustida ozon qatlami keskin yupqalashganini kashf etishgan." },
    { "id": "bq26", "question": "Xalqaro Qizil kitob sahifalari qanday ranglardan iborat?", "options": ["Faqat qizil", "Qizil, yashil, oq, sariq, kulrang", "Qizil va qora", "Oq va yashil"], "answer_index": 1, "explanation": "To'g'ri! Xavf darajasiga qarab sahifalar turli ranglarga (yo'qolganlar qora, tiklanayotganlar yashil) ajratilgan." },
    { "id": "bq27", "question": "Atmosfera havosidagi kislorodning (O2) taxminiy miqdori qancha?", "options": ["78 %", "1 %", "21 %", "50 %"], "answer_index": 2, "explanation": "To'g'ri! Atmosfera havosining taxminan 21 foizini kislorod, 78 foizini azot tashkil qiladi." },
    { "id": "bq28", "question": "Tirik organizmlarning yashash muhiti turiga qarab nechta asosiy muhit farqlanadi?", "options": ["2 ta", "4 ta", "10 ta", "6 ta"], "answer_index": 1, "explanation": "To'g'ri! Bular: suv muhiti, yer-havo muhiti, tuproq muhiti va tirik organizmning o'zi muhit sifatida." },
    { "id": "bq29", "question": "O'zbekiston Respublikasining \"Ekologik nazorat to'g'risida\"gi qonuni qachon qabul qilingan?", "options": ["1992-yil", "2013-yil 27-dekabr", "2005-yil", "2020-yil"], "answer_index": 1, "explanation": "To'g'ri! Ushbu qonun tabiatni muhofaza qilish sohasida jamoatchilik va davlat nazoratini tartibga soladi." },
    { "id": "bq30", "question": "Xalqaro Yer kuni (Earth Day) qachon nishonlanadi?", "options": ["22-aprel", "5-iyun", "22-mart", "1-may"], "answer_index": 0, "explanation": "To'g'ri! 22-aprel butunjahon Yer kuni sifatida ekologik muammolarga e'tibor qaratish uchun nishonlanadi." },
    { "id": "bq31", "question": "Qaysi faoliyat turi tuproqning ikkilamchi sho'rlanishiga eng ko'p sabab bo'ladi?", "options": ["O'rmon yong'inlari", "Ortiqcha va noto'g'ri sug'orish", "Shamol", "Quyosh radiatsiyasi"], "answer_index": 1, "explanation": "To'g'ri! Suvni ortiqcha quyish yer osti sizot suvlarini ko'tarib, tuproq yuzasiga tuzlarni olib chiqadi." },
    { "id": "bq32", "question": "YUNESKOning \"Inson va Biosfera\" (MAB) dasturi qachon qabul qilingan?", "options": ["1950-yil", "1971-yil", "1992-yil", "2000-yil"], "answer_index": 1, "explanation": "To'g'ri! MAB dasturi butun dunyoda biosfera rezervatlarini tashkil etishni maqsad qilgan." },
    { "id": "bq33", "question": "O'zbekistonda ekologiya sohasidagi eng oliy qonun qaysi hujjatda o'z aksini topgan?", "options": ["Vazirlar Mahkamasi qarorida", "O'zbekiston Respublikasi Konstitutsiyasida", "O'rmon kodeksida", "Xalqaro shartnomada"], "answer_index": 1, "explanation": "To'g'ri! O'zbekiston Konstitutsiyasida fuqarolarning atrof-muhitga ehtiyotkorona munosabatda bo'lishi belgilangan." },
    { "id": "bq34", "question": "Suvning tabiatdagi aylanishi nima deb ataladi?", "options": ["Suksessiya", "Gidrologik sikl", "Evtrofikatsiya", "Melioratsiya"], "answer_index": 1, "explanation": "To'g'ri! Gidrologik sikl orqali suv bug'lanadi, bulutga aylanadi, yog'in bo'lib qaytadi va daryolarni to'ldiradi." },
    { "id": "bq35", "question": "Tabiatda zaharli moddalarning oziq zanjiri orqali tobora yig'ilib (konsentratsiyasi oshib) borishi nima deyiladi?", "options": ["Biologik yig'ilish (Biomagnifikatsiya)", "Evtrofikatsiya", "Metabolizm", "Fotosintez"], "answer_index": 0, "explanation": "To'g'ri! Biomagnifikatsiya tufayli zaharli moddalar (masalan, DDT) eng yuqori yirtqichlarda minglab marta ko'payadi." },
    { "id": "bq36", "question": "Dunyodagi eng ko'p kislorod ishlab chiqaruvchi \"Sayyora o'pkasi\" deb qaysi hududlar ataladi?", "options": ["Cho'llar", "Ignabargli tayga o'rmonlari", "Amazonka tropik o'rmonlari", "Tog'lar"], "answer_index": 2, "explanation": "To'g'ri! Amazonka yomg'ir o'rmonlari sayyoradagi eng katta fotosintez markazlaridan biridir." },
    { "id": "bq37", "question": "Qizilqum cho'lida yashovchi o'ziga xos va noyob hayvon (endemik) turini belgilang.", "options": ["Qutb ayig'i", "Xoldor kiyik", "Qizilqum arxari", "Panda"], "answer_index": 2, "explanation": "To'g'ri! Qizilqum arxari (Seversov qo'yi) faqat O'zbekistonning cho'l-tog' tizmalarida yashovchi noyob tur." },
    { "id": "bq38", "question": "Qattiq maishiy chiqindilarni (QMQ) zararsizlantirishning eng ekologik toza usuli qaysi?", "options": ["Ochiq havoda yoqish", "Yerga ko'mish", "Saralash va qayta ishlash (Recycling)", "Daryoga tashlash"], "answer_index": 2, "explanation": "To'g'ri! Chiqindilarni saralab qayta ishlash xom-ashyoni tejaydi va tabiatni ifloslanishdan asraydi." },
    { "id": "bq39", "question": "Xalqaro Suv kuni qachon nishonlanadi?", "options": ["22-mart", "1-sentyabr", "10-dekabr", "5-iyun"], "answer_index": 0, "explanation": "To'g'ri! 22-mart Jahon Suv resurslari kuni bo'lib, chuchuk suv muammosiga bag'ishlangan." },
    { "id": "bq40", "question": "Chiqindilarga berilgan \"ikkinchi hayot\" qanday ataladi?", "options": ["Degradatsiya", "Utilizatsiya (qayta ishlash)", "Kompostlash", "Konservatsiya"], "answer_index": 1, "explanation": "To'g'ri! Utilizatsiya - bu chiqindilardan foydali mahsulot yoki xom-ashyo olish jarayonidir." }
]
"@

$newPuzzlesStr = @"
[
    { "id": "bp21", "story": "Odamlar dengiz qirg'og'idagi barcha qalin mangrov o'rmonlarini kesib o'tin qilishdi. Bir necha yildan keyin kuchli to'lqinlar (sunami) qirg'oqdagi uylarni yuvib ketdi.", "question": "Mangrov o'rmonlarining ekologik vazifasi nima edi?", "options": ["Faqat chiroyli manzara", "Dengiz to'lqinlari zarbasini qaytaruvchi va qirg'oqni yemirilishdan saqlovchi tabiiy qalqon edi", "Odamlarni quyoshdan asrash"], "answer_index": 1, "explanation": "To'g'ri! Mangrovlar qirg'oqbo'yi ekotizimlarini kuchli to'lqinlardan va eroziyadan himoya qiladi." },
    { "id": "bp22", "story": "Dehqon hosiliga tushgan qurtlarni yo'qotish uchun dorini shunchalik ko'p sepdiki, nafaqat qurtlar, balki barcha asalarilar ham qirilib ketdi.", "question": "Buning qishloq xo'jaligiga ta'siri qanday bo'ladi?", "options": ["Hosil keskin oshadi", "Gullar changlanmaydi va hosil umuman bo'lmaydi yoki keskin kamayadi", "Hech qanday o'zgarish bo'lmaydi"], "answer_index": 1, "explanation": "To'g'ri! Asalarilar qishloq xo'jaligi ekinlarini changlantiruvchi eng muhim hasharotlar bo'lib, ularsiz hosil bo'lmaydi." },
    { "id": "bp23", "story": "Shaharda daraxtlarni shafqatsizlarcha (faqat tanasini qoldirib) butashdi. Yoz faslida shahar ichida nafas olish og'irlashdi.", "question": "Daraxt barglarining qanday xususiyati yo'qotildi?", "options": ["Changni tutib qolish va kislorod ishlab chiqarish xususiyati", "Shamolni to'xtatish xususiyati", "Manzarali ko'rinishi"], "answer_index": 0, "explanation": "To'g'ri! Barglar havoni tozalovchi \"o'pka\"dir, ularni asossiz kesish shaharni dim va chang qilib yuboradi." },
    { "id": "bp24", "story": "Bir hovuzda juda ko'p baliq boqilardi. Bahorda hovuz suviga qishloq xo'jaligi dalasidan o'g'itli suv kelib tushdi. Suvo'tlar shu qadar ko'paydiki, hovuz yashil rangga kirdi.", "question": "Hovuzdagi baliqlarga nima xavf soladi?", "options": ["Zaharli o'tlar", "Kechasi suvo'tlar kislorodni yutishi sababli baliqlar bo'g'ilib o'ladi (Evtrofikatsiya)", "Baliqlar suvo'tni yeb juda kattalashib ketadi"], "answer_index": 1, "explanation": "To'g'ri! Garchi o'simliklar kunduzi kislorod chiqarsa-da, juda ko'p miqdordagi suvo'tlar chiriganda va tunda suvda kislorod qolmaydi." },
    { "id": "bp25", "story": "Zavod yaqinidagi qishloq aholisi doimiy ravishda tish emalining yemirilishi va suyaklar mo'rtlashishidan (flyuoroz) shikoyat qila boshladi.", "question": "Zavod havoga asosan qaysi moddani chiqarmoqda?", "options": ["Azot", "Ftor birikmalari", "Metan"], "answer_index": 1, "explanation": "To'g'ri! Ftorning havo va suvda ko'payishi inson suyaklari va tishlarida og'ir kasalliklarni (flyuoroz) keltirib chiqaradi." },
    { "id": "bp26", "story": "Arktikada (Shimoliy qutb) havo harorati ko'tarilib muzliklar eriy boshladi.", "question": "Buning butun dunyoga ta'siri qanday bo'ladi?", "options": ["Faqat Arktikada havo isitadi", "Dunyo okeani sathi ko'tarilib, ko'plab orollar va qirg'oq shaharlari suv ostida qoladi", "Ekotizim o'zgarmaydi"], "answer_index": 1, "explanation": "To'g'ri! Global isish oqibatida muzliklarning erishi butun insoniyat uchun jiddiy ofatdir." },
    { "id": "bp27", "story": "Bir orolda ilonlarni yo'q qilishdi. Keyin kalamushlar shu qadar ko'paydiki, ular barcha qush uyalaridagi tuxumlarni yeb bitirdi.", "question": "Bu vaziyat nimani isbotlaydi?", "options": ["Ilonlar qushlarni qutqaruvchi bo'lgan", "Tabiatdagi oziq zanjirining bir halqasini uzib tashlash butun ekotizim halokatiga olib keladi", "Qushlar yashirinishni bilmaydi"], "answer_index": 1, "explanation": "To'g'ri! Tabiatda \"ortiqcha\" yoki \"keraksiz\" jonzot yo'q, barchasi muvozanatni saqlab turadi." },
    { "id": "bp28", "story": "Plastik idishlarni tashlab yubormasdan, ularni isitib, presslab, yangi qurilish materiallari ishlab chiqarila boshlandi.", "question": "Bu qanday usul hisoblanadi?", "options": ["Reutilizatsiya (Qayta ishlash)", "Konservatsiya", "Tabiatni ifloslantirish"], "answer_index": 0, "explanation": "To'g'ri! Plastikdan yangi materiallar (masalan, ekocherepitsa yoki trubalar) yasash eng toza qayta ishlash usulidir." },
    { "id": "bp29", "story": "O'rmon yong'inidan so'ng u yerdagi kul va qora kuygan daraxtlar o'rnida birinchi bo'lib mayda o'tlar va moxlar o'sib chiqdi. 10 yildan so'ng butalar, 50 yildan so'ng yana o'rmon tiklandi.", "question": "Ushbu ketma-ketlik biologiyada qanday nomlanadi?", "options": ["Ikkilamchi suksessiya", "Eroziya", "Degradatsiya"], "answer_index": 0, "explanation": "To'g'ri! Buzilgan ekotizimning (yong'in yoki kesishdan keyin) asta-sekin, bosqichma-bosqich o'zini o'zi tiklashi ikkilamchi suksessiya deyiladi." },
    { "id": "bp30", "story": "Tog'li hududda o'sadigan noyob lolani odamlar tomorqasiga ekish uchun piyozchasi (tomiri) bilan yulib kela boshlashdi.", "question": "Lola populyatsiyasiga qanday ta'sir ko'rsatiladi?", "options": ["U boshqa joyda ko'payadi", "Piyozchasi bilan yulingan noyob o'simlik tabiatda boshqa o'smaydi va butunlay qirilib ketadi", "Havo tozalanadi"], "answer_index": 1, "explanation": "To'g'ri! Nodir o'simliklarni (ayniqsa piyozchali turlarni) tabiatdan yulib olish qat'iyan man etiladi, chunki ular faqat o'zining tabiiy biotopida yashay oladi." },
    { "id": "bp31", "story": "Odamlar shaharda chiroyli ko'rinishi uchun chet eldan keltirilgan, tez o'sadigan begona daraxt turini ommaviy ekishdi. Bu daraxt mahalliy qurt-qumursqalarni yo'q qilib, boshqa daraxtlarni siqib chiqardi.", "question": "Bu begona daraxt ekologiyada qanday nomlanadi?", "options": ["Noyob tur", "Invaziv (bosqinchi) tur", "Endemik tur"], "answer_index": 1, "explanation": "To'g'ri! Boshqa hududdan keltirilgan va mahalliy ekotizimga tajovuz qilib muvozanatni buzuvchi turlar invaziv turlar deyiladi." },
    { "id": "bp32", "story": "Fermer dala chetlariga daraxtlardan iborat ihota (to'siq) o'rmon mintaqasini ekdi.", "question": "Buning dalaga foydasi bormi?", "options": ["Foydasi yo'q, joyni egallaydi", "Ha, u ekinlarni kuchli shamoldan, tuproqni eroziyadan asraydi va namlikni saqlaydi", "Faqat qushlarga foyda"], "answer_index": 1, "explanation": "To'g'ri! Ihota o'rmonlari mikroklimatni yaxshilaydi, tuproqni uchib ketishdan saqlab qoladi." },
    { "id": "bp33", "story": "Zavod ishlab chiqarish jarayonida hosil bo'lgan chiqindi gazlarni atmosferaga chiqarish o'rniga, undan issiqlik energiyasi oldi.", "question": "Bu qanday texnologiya?", "options": ["Eski usul", "Chiqindisiz (yoki kam chiqindili) energiya tejamkor texnologiya", "Ifloslantiruvchi texnologiya"], "answer_index": 1, "explanation": "To'g'ri! Resurslarni maksimal tejaydigan bunday texnologiyalar ekologiyaning zamonaviy talabidir." },
    { "id": "bp34", "story": "Qishloqda yer osti ichimlik suvi quduqlari sho'rlanib, ta'mi ayniydi.", "question": "Bunga nima sabab bo'lishi mumkin?", "options": ["Quduqning eski ekani", "Yaqin atrofdagi maishiy chiqindi poligonlaridan yomg'ir suvi orqali zaharli moddalarning yer osti suviga sızib tushishi", "Quyosh nuri"], "answer_index": 1, "explanation": "To'g'ri! Noto'g'ri qurilgan axlatxonalar va o'g'it omborlaridan sizib chiqqan zahar yer osti suvlarini (sizot suvlarini) ifloslantiradi." },
    { "id": "bp35", "story": "Tadbirkor o'z hovlisidagi chuqurga barcha plastik va rezina chiqindilarni to'plab, yoqib yubordi. U axlatxona pulini tejab qoldim deb o'yladi.", "question": "Uning hatti-harakati qanday oqibatga olib keladi?", "options": ["Atrof muhit tozalanadi", "Yonish jarayonida ajralgan zaharli dioksin va furanlar o'zi va qo'shnilarining sog'lig'iga halokatli ta'sir qiladi", "Hech qanday oqibati yo'q"], "answer_index": 1, "explanation": "To'g'ri! Rezina va plastikni ochiq yoqish saratonga sabab bo'luvchi eng o'ta zaharli moddalarni (dioksin) havoga tarqatadi." },
    { "id": "bp36", "story": "Okeanlarda ohaktosh va marjon qoyalari (riflari) oqarib, nobud bo'lmoqda.", "question": "Buning asosiy sababi nima deb hisoblanadi?", "options": ["Baliqlar yeb qo'ymoqda", "Okean suvining isishi va uning kislotaliligi (CO2 hisobiga) ortishi", "Kemalar harakati"], "answer_index": 1, "explanation": "To'g'ri! Karbonat angidrid suvda erib kislota hosil qiladi, bu esa nozik marjonlarni nobud qiladi." },
    { "id": "bp37", "story": "Ko'chada eskirgan batareyka (tok manbai) yotibdi, bir bola uni tuproqqa ko'mib tashladi.", "question": "Kichkina batareyka tabiatga zarar qiladimi?", "options": ["Yo'q, u juda kichkina", "Ha, bitta kichik batareyka tuproqdagi og'ir metallar (qo'rg'oshin, simob, kadmiy) tufayli 20 kvadrat metr yerni va yuzlab litr suvni zaharli qiladi", "U chirib o'g'it bo'ladi"], "answer_index": 1, "explanation": "To'g'ri! Batareykalar oddiy axlat emas, ular o'ta xavfli qoldiq hisoblanadi va maxsus joylarga topshirilishi shart." },
    { "id": "bp38", "story": "Cho'pon o'zining yuzlab qo'ylarini har yili bahorda aynan bitta hududda boqaverdi.", "question": "Yillar o'tib bu hudud qanday holatga tushadi?", "options": ["O'tlar ko'payadi", "Yerdagi o'simliklar o'sishga ulgurmaydi, tuproq tepkilanib eroziyaga uchraydi va joy cho'lga aylanadi (Degradatsiya)", "O'rmon paydo bo'ladi"], "answer_index": 1, "explanation": "To'g'ri! Yaylovlardan nazoratsiz va tizimsiz foydalanish ularning degradatsiyasiga olib keladi." },
    { "id": "bp39", "story": "Ovchi davlat tomonidan ruxsat etilgan vaqtda (kuzda) va qoidaga muvofiq bitta yovvoyi o'rdakni ovladi.", "question": "U qonunni buzdimi?", "options": ["Ha, ov mutlaqo taqiqlangan", "Yo'q, agar u tegishli ruxsatnoma olgan bo'lsa va otish normasi doirasida bo'lsa, bu qonuniy (havaskor) ov hisoblanadi", "Ha, faqat qishda mumkin"], "answer_index": 1, "explanation": "To'g'ri! Qonun hujjatlari asosida, ma'lum davrlarda ruxsatnoma (putyovka) bilan ov qilish mumkin." },
    { "id": "bp40", "story": "Mamlakatda \"Yashil makon\" dasturi asosida har yili millionlab daraxtlar ekilmoqda.", "question": "Buning asosiy maqsadi nima?", "options": ["O'tin zaxirasini ko'paytirish", "Iqlim mo'tadilligini ta'minlash, kislorod manbaini ko'paytirish va chang bo'ronlarining oldini olish", "Shahar maydonlarini to'ldirish"], "answer_index": 1, "explanation": "To'g'ri! Ommaviy ko'kalamzorlashtirish ekologik muammolarni hal etishning eng samarali va amaliy usulidir." }
]
"@

$newTermsStr = @"
[
    { "id": "bt21", "question": "Global isish nima?", "options": ["Qishning sovuq kelishi", "Sayyoramizdagi o'rtacha yillik haroratning asta-sekin ko'tarilib borishi", "Faqat yoz faslining isishi"], "answer_index": 1, "explanation": "To'g'ri! Issiqxona gazlari tufayli Yer haroratining yillar davomida ortishi Global isish deyiladi." },
    { "id": "bt22", "question": "Ozon qatlami nima?", "options": ["Havodagi kislorodning bir ko'rinishi bo'lib, Yerni halokatli ultrabinafsha nurlardan asrovchi parda", "Zaharli gaz buluti", "Kosmik kema himoyasi"], "answer_index": 0, "explanation": "To'g'ri! Ozon qatlami (O3) stratosferada joylashgan va butun hayotni himoya qiladi." },
    { "id": "bt23", "question": "Bioindikator nima?", "options": ["Tabiatni asrovchi asbob", "Atrof-muhit holati va ifloslanish darajasini o'zida yaqqol ko'rsatib beruvchi sezgir tirik organizmlar", "Zaharli o'simlik"], "answer_index": 1, "explanation": "To'g'ri! Masalan, daraxtlardagi lishayniklar faqat toza havoda o'sadi, ularni kuzatib havoning tozaligini (bioindikatsiya) bilish mumkin." },
    { "id": "bt24", "question": "Endemik turlar qanday turlar?", "options": ["Hamma qit'ada uchraydigan", "Sayyoraning faqatgina qat'iy chegaralangan ma'lum bir kichik hududida yashovchi noyob turlar", "Odam qo'lida yaratilgan turlar"], "answer_index": 1, "explanation": "To'g'ri! Masalan, Avstraliyadagi kenguru yoki O'zbekistondagi Mengkuq lolasi – endemik turlardir." },
    { "id": "bt25", "question": "Invaziv turlar nima?", "options": ["Qirilib ketgan turlar", "Boshqa davlatdan kelib qolib, mahalliy turlarga xavf tug'diruvchi va tez ko'payuvchi yot turlar", "Qizil kitobga kiritilganlar"], "answer_index": 1, "explanation": "To'g'ri! Kolorado qo'ng'izi yoki afg'on maynasi O'zbekiston uchun invaziv (bosqinchi) turlar hisoblanadi." },
    { "id": "bt26", "question": "Gidrosfera nima?", "options": ["Yer qobig'i", "Sayyoramizning barcha suv zaxiralari (okean, dengiz, daryo, muzliklar) yig'indisi", "Bulutlar majmuasi"], "answer_index": 1, "explanation": "To'g'ri! Gidrosfera Yerning suv qobig'idir." },
    { "id": "bt27", "question": "Noosfera (Aql sferasi) tushunchasini kim ilmiy muomalaga kiritgan?", "options": ["Aristotel", "V.I. Vernadskiy va Ye. Lerua", "Ch. Darvin"], "answer_index": 1, "explanation": "To'g'ri! Noosfera – inson aqliy faoliyati hal qiluvchi omilga aylangan biosferaning yangi bosqichi." },
    { "id": "bt28", "question": "Smog nima?", "options": ["Toza havo shabadasi", "Sanoat korxonalari va transportlardan chiqqan zaharli gazlarning tutun va tuman bilan aralashmasi", "Yomg'ir buluti"], "answer_index": 1, "explanation": "To'g'ri! Smog (inglizcha smoke - tutun, fog - tuman) yirik shaharlarda inson salomatligiga katta zarar yetkazadi." },
    { "id": "bt29", "question": "Bioxilma-xillik (Biorang-baranglik) nima?", "options": ["Faqat hayvonlar soni", "Yerdagi barcha tirik organizmlarning, o'simlik va hayvon turlarining boyligi va turlicha ekani", "O'simliklar gullashi"], "answer_index": 1, "explanation": "To'g'ri! Bioxilma-xillik qanchalik boy bo'lsa, ekotizim shunchalik barqaror bo'ladi." },
    { "id": "bt30", "question": "Urbanizatsiya ekologiyada qanday ma'no beradi?", "options": ["Qishloqlarning ko'payishi", "Shaharlarning kengayishi va sanoatlashishi natijasida tabiiy hududlarning qisqarib borishi", "O'rmonlarni yong'indan asrash"], "answer_index": 1, "explanation": "To'g'ri! Urbanizatsiya (shaharlashuv) tabiatga kuchli antropogen bosim hisoblanadi." },
    { "id": "bt31", "question": "Demekologiya (Populyatsiyalar ekologiyasi) nimani o'rganadi?", "options": ["Bitta organizmni", "Bir turga mansub bo'lgan, ma'lum hududda yashovchi individlar guruhining (populyatsiyaning) hayotini", "Olamning paydo bo'lishini"], "answer_index": 1, "explanation": "To'g'ri! Demekologiya populyatsiyalarning soni, o'sishi va tarkibini o'rganadi." },
    { "id": "bt32", "question": "Ekologik monitoring nima?", "options": ["Tabiatga ruxsatsiz kirish", "Atrof-muhit holatini va undagi o'zgarishlarni doimiy ravishda kuzatib, baholab va bashorat qilib borish tizimi", "Faqat jarima yozish"], "answer_index": 1, "explanation": "To'g'ri! Monitoring orqali zaharli moddalar miqdori nazorat qilinadi va fojialarning oldi olinadi." },
    { "id": "bt33", "question": "Eutrofikatsiya (Evtrofikatsiya) nima?", "options": ["O'rmonlarning kesilishi", "Suv havzalarida ozuqa moddalari (azot, fosfor) ko'payib ketishi oqibatida suvo'tlarning mudhish tezlikda ko'payib, kislorodni yutishi", "Suvning tozalanishi"], "answer_index": 1, "explanation": "To'g'ri! Suv havzalarining bunday \"gullashi\" u yerdagi baliqlarning ommaviy qirilishiga olib keladi." },
    { "id": "bt34", "question": "Xromosoma nima?", "options": ["Ekologiya bo'limi", "Hujayrada irsiy ma'lumotlarni saqlovchi va tashuvchi tuzilma", "Bakteriya turi"], "answer_index": 1, "explanation": "To'g'ri! Ekologik ifloslanishlar aynan xromosomadagi DNK ga ta'sir qilib, mutatsiyalarni keltirib chiqaradi." },
    { "id": "bt35", "question": "Mutatsiya nima?", "options": ["Mavsumiy migratsiya", "Organizm irsiy belgilarining (DNKning) zaharli moddalar yoki radiatsiya ta'sirida to'satdan va barqaror o'zgarishi", "Barglarning sarg'ayishi"], "answer_index": 1, "explanation": "To'g'ri! Radiatsiya va kimyoviy moddalar kuchli mutatsiya keltirib chiqaradi (masalan, turli nuqsonli tug'ilishlar)." },
    { "id": "bt36", "question": "Kislotali yomg'ir tarkibida qaysi kislotalar bo'ladi?", "options": ["Sirka kislotasi", "Oltingugurt va nitrat kislotalar", "Tuz kislotasi"], "answer_index": 1, "explanation": "To'g'ri! Zavodlar chiqargan SO2 va NO2 gazlari suv bilan birikib shu kislotalarni hosil qiladi." },
    { "id": "bt37", "question": "Gidrofil organizmlar qanday sharoitni yaxshi ko'radi?", "options": ["Quruq cho'lni", "Suv va yuqori namlikni", "Muzliklarni"], "answer_index": 1, "explanation": "To'g'ri! Gidro (suv) va fil (sevaman) – namlikni sevuvchi organizmlar." },
    { "id": "bt38", "question": "Kserofil o'simliklarga misol keltiring.", "options": ["Yantoq, saksovul, tuyaqorin", "Tol, terak, qamish", "Suv nilufari"], "answer_index": 0, "explanation": "To'g'ri! Bu o'simliklar issiq va quruq cho'l iqlimiga moslashgan (kserofitlar)." },
    { "id": "bt39", "question": "Relikt (qoldiq) turlar nima?", "options": ["Yangi paydo bo'lgan turlar", "Qadimgi geologik davrlardan hozirgi kungacha yashab qolgan, yo'qolib borayotgan qadimiy turlar (masalan, ginkgo daraxti)", "Kelajak turlari"], "answer_index": 1, "explanation": "To'g'ri! Relikt turlar tabiatning \"tirik qazilmalari\" hisoblanadi." },
    { "id": "bt40", "question": "Iqlim (Klimat) bilan Ob-havo (Pogoda) ning farqi nimada?", "options": ["Farqi yo'q", "Ob-havo bu ma'lum vaqtdagi qisqa muddatli holat, Iqlim esa ma'lum hududga xos bo'lgan ko'p yillik barqaror rejim", "Iqlim faqat qishda bo'ladi"], "answer_index": 1, "explanation": "To'g'ri! Bugungi yomg'ir ob-havo, cho'ldagi doimiy qurg'oqchilik esa iqlim hisoblanadi." }
]
"@

$newPenaltiesStr = @"
[
    { "id": "bpn21", "question": "Xalqaro qoidalarga asosan atrof-muhitga zarar yetkazganlik uchun jinoiy javobgarlik (Ekokiminalitet) mavjudmi?", "options": ["Yo'q, faqat ma'muriy jarima", "Ha, tabiatni qasddan buzish (Ekotsid) xalqaro jinoyat hisoblanadi", "Faqat tashkilotlar uchun"], "answer_index": 1, "explanation": "To'g'ri! Ekotsid (tabiatni ommaviy qirish) insoniyatga qarshi og'ir jinoyatlar qatoriga kiradi." },
    { "id": "bpn22", "question": "O'zbekistonda \"Ekologik audit to'g'risida\"gi qonun qachon qabul qilingan?", "options": ["2021-yil", "1991-yil", "2005-yil"], "answer_index": 0, "explanation": "To'g'ri! 2021-yilda qabul qilingan bo'lib, korxonalarning ekologik qoidalarga rioya etishini mustaqil tekshirishni joriy etdi." },
    { "id": "bpn23", "question": "Zaharli va radioaktiv chiqindilarni mamlakat hududiga chetdan olib kirish qanday jazolanadi?", "options": ["Bojxona to'lovi olinadi", "Qat'iyan taqiqlangan, Jinoiy Kodeksga asosan og'ir jazo tayinlanadi", "Ruxsatnoma orqali mumkin"], "answer_index": 1, "explanation": "To'g'ri! O'zbekiston hududiga chetdan radioaktiv yoki zaharli qoldiqlarni yashirish uchun olib kirish o'ta og'ir jinoyatdir." },
    { "id": "bpn24", "question": "Noyob va yo'qolib borayotgan hasharotlarni (masalan, O'zbekiston Qizil kitobiga kirgan kapalaklarni) tutib kolleksiya qilish mumkinmi?", "options": ["Ha, ular hasharot-ku", "Yo'q, Qizil kitobga kiritilgan barcha turlar (hatto hasharotlar ham) davlat himoyasida va buning uchun jarima to'lanadi", "Faqat maktab o'quvchilariga mumkin"], "answer_index": 1, "explanation": "To'g'ri! Qizil kitob barcha tirik mavjudotlarni himoya qiladi." },
    { "id": "bpn25", "question": "Ekin dalalariga ataylab o't qo'ygan fuqaro yong'in tarqalib o'rmonga o'tsa nima bo'ladi?", "options": ["O't o'chiruvchilar o'chiradi", "Katta miqdordagi zararni qoplaydi va jinoiy javobgarlikka tortiladi", "Jarima to'lamaydi"], "answer_index": 1, "explanation": "To'g'ri! Ehtiyotsizlik yoki qasddan o'rmonga ziyon yetkazish Jinoyat kodeksi bo'yicha baholanadi." },
    { "id": "bpn26", "question": "Avtotransport vositasini belgilangan toksiklik (zaharlilik) normasidan ortiqcha tutun bilan haydash (tutunlatib yurish) jarimasi qancha? (MJtK 73-modda)", "options": ["BHMning 1 baravarigacha", "BHMning 10 baravari", "Faqat ogohlantirish"], "answer_index": 0, "explanation": "To'g'ri! Havoni ortiqcha tutun bilan ifloslantirgan haydovchilarga ma'muriy jarima solinadi." },
    { "id": "bpn27", "question": "Tabiatni muhofaza qilish to'g'risidagi qonunlarni buzganlik to'g'risida noto'g'ri (yolg'on) ma'lumot tarqatish (masalan, yolg'on ekologik ofat haqida vahima qilish) javobgarlikka sabab bo'ladimi?", "options": ["Yo'q, bu so'z erkinligi", "Ha, jamoat tartibini buzgani uchun javobgarlikka tortiladi", "Faqat jurnalistlar jazolanadi"], "answer_index": 1, "explanation": "To'g'ri! Asossiz vahima tarqatish jamiyatda xavfsizlikka salbiy ta'sir qilgani uchun qonun doirasida jazolanadi." },
    { "id": "bpn28", "question": "Ekologiya organlarining qonuniy faoliyatiga to'sqinlik qilish (masalan, inspektorni zavodga kiritmaslik) qanday jazolanadi? (MJtK 197-6-modda)", "options": ["Jarima solinmaydi", "Mansabdor shaxslarga yirik miqdorda jarima solinadi (BHMning 5-10 baravari)", "Tushuntirish ishlari olib boriladi"], "answer_index": 1, "explanation": "To'g'ri! Ekologiya nazoratchilarining ishiga to'sqinlik qilish qat'iy javobgarlikka sabab bo'ladi." },
    { "id": "bpn29", "question": "O'zbekistonda polietilen paketlarni (qalinligi 40 mikrondan yupqa) bepul berish va sotishga qachondan boshlab cheklov o'rnatildi?", "options": ["2010-yil", "2019-yil", "Kuni kecha"], "answer_index": 1, "explanation": "To'g'ri! 2019-yildan ekologiyani asrash maqsadida yupqa paketlarni bepul tarqatish taqiqlangan." },
    { "id": "bpn30", "question": "O'rmon fondi yerlarida ruxsatsiz pichan o'rish yoki chorva mollarini o'tlatish mumkinmi? (MJtK 80-modda)", "options": ["Ha, o't baribir o'sadi", "Yo'q, bu o'rmonga ziyon keltirgani uchun BHMning 1 dan 3 baravarigacha jarima solinadi", "Faqat qishloq odamlariga mumkin"], "answer_index": 1, "explanation": "To'g'ri! Davlat o'rmonlarida har qanday xo'jalik faoliyati qonun bilan tartibga olinadi." },
    { "id": "bpn31", "question": "O'simliklar karantini qoidalarini buzish (karantin zonasidan kasallangan o'simlik olib chiqish) javobgarlikka sabab bo'ladimi?", "options": ["Yo'q", "Ha, qishloq xo'jaligi ekologiyasiga zarar yetkazgani uchun (MJtK 108-modda) jarima olinadi", "Faqat xorijliklar uchun"], "answer_index": 1, "explanation": "To'g'ri! Kasallik va zararkunandalar (masalan, nematoda) tarqalishining oldini olish o'ta muhim ekologik xavfsizlikdir." },
    { "id": "bpn32", "question": "Er osti suvlaridan quduq qazib (burg'ulab) o'zboshimchalik bilan foydalanish tartibi qanday jazolanadi?", "options": ["Hech narsa qilinmaydi", "Suv qonunchiligini buzish hisoblanib, uskunalar musodara qilinishi va jarima olinishi mumkin", "Jarima bor, lekin uskunasi o'zida qoladi"], "answer_index": 1, "explanation": "To'g'ri! Yer osti boyliklari davlat mulki bo'lib, litsenziyasiz quduq qazish qat'iy taqiqlanadi." },
    { "id": "bpn33", "question": "Dengizlarni va transchegaraviy daryolarni ifloslantirgan davlatlar ustidan qayerga arz qilinadi?", "options": ["Shahar sudiga", "Xalqaro Sud va BMTning ekologiya komissiyalariga", "E'tibor berilmaydi"], "answer_index": 1, "explanation": "To'g'ri! Ekologik xavfsizlik chegaraga qaramaydi, transchegaraviy zararlar xalqaro huquq bilan tartibga solinadi." },
    { "id": "bpn34", "question": "Suv ob'ektlari qirg'oqlarida (muhofaza zonasida) bino va inshootlar qurish mumkinmi?", "options": ["Ha", "Yo'q, qat'iyan man etiladi (MJtK 82-modda) bino buzib tashlanadi va jarima solinadi", "Faqat choyxona qurish mumkin"], "answer_index": 1, "explanation": "To'g'ri! Qirg'oq mintaqasi tabiatning suv tozalovchi o'pkasi hisoblanadi, u yerga qurilish qilish suv ifloslanishiga olib keladi." },
    { "id": "bpn35", "question": "Xususiy korxona davlat qo'riqxonasi hududida oltin qazib olishi mumkinmi?", "options": ["Agar ko'p soliq to'lasa mumkin", "Mutlaqo taqiqlangan, bu Jinoiy javobgarlikka olib keladi", "Ruxsat olib qazishi mumkin"], "answer_index": 1, "explanation": "To'g'ri! Qo'riqxonalarda yer osti va yer usti boyliklaridan foydalanish hamda har qanday xo'jalik faoliyati abadiy taqiqlangan." },
    { "id": "bpn36", "question": "Itlarni, mushuklarni yoki boshqa uy hayvonlarini qiynab o'ldirgan fuqarolarga qanday jazo ko'zda tutilgan?", "options": ["Faqat jarima (MJtK 111-modda)", "Agar qilmish og'irlashtiruvchi holatlarda qilinsa, Jinoiy kodeks (202-1 modda) bo'yicha qamoq jazosigacha boradi", "Buning uchun qonun yo'q"], "answer_index": 1, "explanation": "To'g'ri! Hozirda O'zbekistonda hayvonlarga shafqatsiz munosabatda bo'lish bo'yicha qonunlar qat'iylashtirilib, jinoiy jazo kiritilgan." },
    { "id": "bpn37", "question": "Daraxt va buta ko'chatlarini nobud qilish (mol boqib yoki poyabzal bilan eglash) jazolanadimi?", "options": ["Yo'q", "Ha, yangi ekilgan ko'chatlarni nobud qilish (MJtK 79-modda) ham jarimaga sabab bo'ladi", "Faqat katta daraxt uchungina jarima bor"], "answer_index": 1, "explanation": "To'g'ri! Yosh ko'chatlarni toptash va nobud qilish ularni kesish kabi tabiatga ziyon hisoblanadi." },
    { "id": "bpn38", "question": "Avtomobil signalini asossiz ravishda baland chalib yurish (shovqin ifloslanishi) javobgarlik keltirib chiqaradimi?", "options": ["Yo'q", "Ha, qat'iy taqiqlangan", "Ha, Ma'muriy javobgarlik (Yo'l harakati qoidalarini buzish) bo'yicha jarimaga tortiladi"], "answer_index": 2, "explanation": "To'g'ri! Shovqin ham ifloslanish turi hisoblanib, asossiz signal chalish qonunan taqiqlangan." },
    { "id": "bpn39", "question": "Tuproqqa zaharli kimyoviy moddalarni ruxsatsiz ko'mib yuborganlik uchun jazo qanday?", "options": ["Arzimagan jarima", "Tuproqning ifloslanishi darajasiga qarab juda yirik jarima va hatto korxona faoliyati to'xtatilishi", "Hech qanday"], "answer_index": 1, "explanation": "To'g'ri! Tuproqni toksik qoldiqlar bilan zaharlash yer resurslariga qilingan og'ir jinoyatdir." },
    { "id": "bpn40", "question": "Ovchi yo'lida uchragan burgutni yoki oqqushni (\"havaskorlik\" qilib) otib tashlasa nima bo'ladi?", "options": ["Maqtov oladi", "Qizil kitobga kirgan turlarni otish og'ir jinoyat sanalib, ulkan miqdorda (millionlab) zarar undiriladi va qamoqqa olinadi", "Faqat miltig'i olib qo'yiladi"], "answer_index": 1, "explanation": "To'g'ri! Yirtqich qushlar (burgut, lochin) va oqqush kabi noyob parrandalar davlat himoyasidagi o'ta noyob turlardir." }
]
"@

$newTrueFalseStr = @"
[
    { "id": "btf21", "question": "Yerdagi barcha kislorod faqatgina o'rmonlardagi daraxtlardan ajralib chiqadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Yerdagi kislorodning katta qismini (deyarli yarmini) Dunyo okeanidagi fitoplanktonlar (suvo'tlar) ishlab chiqaradi." },
    { "id": "btf22", "question": "Biologik xilma-xillik qanchalik kambag'al (kam) bo'lsa, o'sha hudud shunchalik ekologik sog'lom bo'ladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Aksincha, bioxilma-xillik qanchalik boy bo'lsa (turlar ko'p bo'lsa), ekotizim tashqi ta'sirlarga shunchalik chidamli bo'ladi." },
    { "id": "btf23", "question": "Ozon tuynugining paydo bo'lishiga asosan freon gazlari (muzlatkich va aerozollarda ishlatiladigan) sababchi hisoblanadi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Xlorftoruglerodlar (freonlar) ozon molekulalarini juda tez parchalaydigan sun'iy gazlardir." },
    { "id": "btf24", "question": "Cho'l mintaqalarida tabiat juda qashshoq bo'lgani uchun u yerni muhofaza qilish shart emas.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Cho'llar ham o'ziga xos juda nozik va noyob (endemik) turlarga boy ekotizim hisoblanadi. Ular ayniqsa inson ta'siridan tez buziladi." },
    { "id": "bt25", "question": "Tunda daraxtlar kislorod ishlab chiqarishni to'xtatib, o'zlari ham kislorod yuta boshlaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Fotosintez (kislorod chiqarish) faqat yorug'likda yuz beradi. Tunda esa o'simliklar oddiy nafas oladi (kislorod yutib, karbonat angidrid chiqaradi)." },
    { "id": "btf26", "question": "Tabiatda plastik butilkalar 1-2 yilda butunlay chirib, tuproqqa aylanib ketadi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Plastik va PET idishlar tabiatda 400 yildan ortiq saqlanib, mikroplastiklarga aylanadi." },
    { "id": "btf27", "question": "Zavod va avtomobillar chiqaradigan oltingugurt dioksidi (SO2) kislotali yomg'irning asosiy sababchisidir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! SO2 gazlari bulutlardagi namlik bilan birikib, sulfat kislotasini hosil qiladi." },
    { "id": "btf28", "question": "O'zbekistonda ovlash butun yil davomida barcha hayvonlarga ruxsat etilgan.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Hayvonlarning ko'payish davrida (bahor va yozda) hamda Qizil kitobga kiritilgan turlarga ov qilish mutlaqo taqiqlangan." },
    { "id": "btf29", "question": "Shahar ko'chalarida daraxtlarni oqlash, aslida ularning hasharotlardan himoyasidan ko'ra ko'proq dekorativ (chiroyli) maqsadga ega.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Zamonaviy ekologiyada daraxtlarni oxak bilan oqlash unchalik zarur amaliyot hisoblanmaydi, ayniqsa o'rmonlarda bu umuman qilinmaydi." },
    { "id": "btf30", "question": "Yer osti suvlari butunlay tugamaydigan cheksiz boylikdir, uni istalgancha ishlatish mumkin.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Yer osti suvlari tiklanishi minglab yillarni talab qiladi. Hozirda ular xavfli darajada tez tugab bormoqda." },
    { "id": "btf31", "question": "O'rgimchaklar hasharotlar sinfiga (6 oyoqlilarga) kirmaydi, ular alohida o'rgimchaksimonlar (8 oyoqlilar) sinfi vakilidir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! O'rgimchaklar anatomik jihatdan hasharotlardan farq qiladi va zararkunandalarni yeb katta foyda keltiradi." },
    { "id": "btf32", "question": "Ekologiyada \"Qora kitob\" tushunchasi mavjud emas.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! \"Qora kitob\" yoki \"Qora ro'yxat\" Yer yuzidan butunlay qirilib va yo'qolib ketgan hayvon va o'simliklar ro'yxatini anglatadi (masalan, Turon yo'lbarsi)." },
    { "id": "btf33", "question": "Eski batareykalarni oddiy axlat qutisiga tashlash katta ekologik zarardir.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Ularning tarkibidagi og'ir metallar tuproq va yer osti suvlarini qattiq zaharlaydi." },
    { "id": "btf34", "question": "O'zbekistonda har qanday daraxtni, hatto qurib qolganini kesish uchun ham davlat Ekologiya ruxsatnomasi olinishi shart.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Qonunchilikka ko'ra, davlat fondiga yoki jamoat joyiga tegishli har qanday daraxt ruxsatsiz kesilishi mumkin emas." },
    { "id": "btf35", "question": "Agar dengiz suvi isib ketsa, bu baliqlar uchun faqat foydali, chunki ular sovuq qotmaydi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Suv isiganda undagi kislorod miqdori keskin kamayadi va ko'plab baliqlar bo'g'ilib o'ladi." },
    { "id": "btf36", "question": "Global isish faqatgina atmosferadagi karbonat angidrid (CO2) miqdoriga bog'liq.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Global isishga metan (CH4), azot oksidlari, freonlar va hatto suv bug'lari ham katta ta'sir ko'rsatadi." },
    { "id": "btf37", "question": "Qushlarning bahorda janubdan shimolga ko'chib o'tishi mavsumiy migratsiya deyiladi.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Bu ularning yashash va ozuqa izlab yil fasllariga moslashish usulidir." },
    { "id": "btf38", "question": "Antropogen ta'sir deganda kosmosdan keladigan meteoritlar zarari tushuniladi.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Antropos (odam) degani. Antropogen ta'sir insoniyatning tabiatga qilayotgan bevosita o'zgarishlaridir." },
    { "id": "btf39", "question": "O'zbekistonda Amudaryo va Sirdaryo sirkulasiyasi Orol dengizining holatiga bevosita bog'liq.", "options": ["Rost", "Yolg'on"], "answer_index": 0, "explanation": "Rost! Orol dengizi asosan aynan shu ikkita buyuk daryo suvi hisobiga to'yinar edi." },
    { "id": "btf40", "question": "Barcha yovvoyi tabiat qonunlari faqatgina insonlarga xalaqit berish uchun o'ylab topilgan.", "options": ["Rost", "Yolg'on"], "answer_index": 1, "explanation": "Yolg'on! Tabiat qonunlari insoniyatning o'zini va uning kelajak avlodini yashab qolishini ta'minlash uchun xizmat qiladi." }
]
"@

$newQ = ConvertFrom-Json -InputObject $newQuizzesStr
$newP = ConvertFrom-Json -InputObject $newPuzzlesStr
$newT = ConvertFrom-Json -InputObject $newTermsStr
$newPn = ConvertFrom-Json -InputObject $newPenaltiesStr
$newTf = ConvertFrom-Json -InputObject $newTrueFalseStr

$jsonObj.quizzes += $newQ
$jsonObj.puzzles += $newP
$jsonObj.terms += $newT
$jsonObj.penalties += $newPn
$jsonObj.truefalse += $newTf

$jsonObj | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonFile -Encoding UTF8
