const fs = require('fs');

const quizData = JSON.parse(fs.readFileSync('./data/quiz.json', 'utf8'));

const newQuizzes = [
    { id: 'bq11', question: 'Yer yuzining tirik organizmlar yashaydigan qobig\\'i qanday ataladi?', options: ['Litosfera', 'Gidrosfera', 'Biosfera', 'Atmosfera'], answer_index: 2, explanation: 'To\\'g\\'ri! Biosfera (hayot qobig\\'i) Yerning barcha tirik organizmlar yashaydigan qismini o\\'z ichiga oladi.' },
    { id: 'bq12', question: 'Tabiatdagi barcha oziq zanjirlari nima bilan boshlanadi?', options: ['Yirtqichlar', 'O\\'txo\\'r hayvonlar', 'Redutsentlar', 'Produtsentlar (O\\'simliklar)'], answer_index: 3, explanation: 'To\\'g\\'ri! Barcha oziq zanjirlari quyosh energiyasini o\\'zlashtiruvchi yashil o\\'simliklardan boshlanadi.' },
    { id: 'bq13', question: 'Muhitning jonsiz omillari (harorat, yorug\\'lik, namlik) ilmiy tilda nima deyiladi?', options: ['Abiotik omillar', 'Biotik omillar', 'Antropogen omillar', 'Texnogen omillar'], answer_index: 0, explanation: 'To\\'g\\'ri! Abiotik omillar - jonsiz tabiat elementlarining organizmga ta\\'siridir.' },
    { id: 'bq14', question: 'O\\'lik organik moddalarni parchalab, ularni mineral moddalarga aylantiruvchi organizmlar (bakteriyalar, zamburug\\'lar) nima deyiladi?', options: ['Konsumentlar', 'Produtsentlar', 'Redutsentlar', 'Avtotroflar'], answer_index: 2, explanation: 'To\\'g\\'ri! Redutsentlar (parchalovchilar) tabiatda moddalar aylanishini yakunlab beradi.' },
    { id: 'bq15', question: 'Atrof-muhitni muhofaza qilish butunjahon kuni qachon nishonlanadi?', options: ['22-aprel', '5-iyun', '1-dekabr', '21-mart'], answer_index: 1, explanation: 'To\\'g\\'ri! BMT tomonidan 1972-yilda 5-iyun Atrof-muhitni muhofaza qilish kuni deb e\\'lon qilingan.' },
    { id: 'bq16', question: 'Dunyodagi eng katta ko\\'l (maydoni jihatidan) qaysi?', options: ['Baykal', 'Viktoriya', 'Kaspiy dengizi', 'Orol dengizi'], answer_index: 2, explanation: 'To\\'g\\'ri! Kaspiy dengizi aslida dunyodagi eng yirik oqmas ko\\'l hisoblanadi.' },
    { id: 'bq17', question: 'Sanoat korxonalaridan havoga ko\\'tarilgan oltingugurt va azot oksidlari qanday ekologik muammoni keltirib chiqaradi?', "options": ["Ozon tuynugi", "Kislotali yomg'irlar", "O'rmon yong'inlari", "Tuproq eroziyasi"], answer_index: 1, explanation: 'To\\'g\\'ri! Ular havodagi suv bug\\'lari bilan birikib kislotali yomg\\'irlarni hosil qiladi.' },
    { id: 'bq18', question: 'Qaysi gaz atmosferada «issiqxona effekti» (global isish) ni keltirib chiqaruvchi asosiy omil hisoblanadi?', options: ['Kislorod (O2)', 'Azot (N2)', 'Karbonat angidrid (CO2)', 'Argon (Ar)'], answer_index: 2, explanation: 'To\\'g\\'ri! CO2 Yer yuzasidan qaytayotgan issiqlikni ushlab qolib, sayyorani isitadi.' },
    { id: 'bq19', question: 'Tuproqning unumdor qatlami shamol yoki suv ta\\'sirida yuvilib (uchib) ketishi nima deyiladi?', options: ['Eroziya', 'Evtrofikatsiya', 'Melioratsiya', 'Suksessiya'], answer_index: 0, explanation: 'To\\'g\\'ri! Tuproq eroziyasi uning unumdorligini pasaytiruvchi eng xavfli jarayonlardan biridir.' },
    { id: 'bq20', question: 'O\\'zbekistonning qaysi viloyatida Ustyurt platosi joylashgan?', options: ['Buxoro', 'Navoiy', 'Xorazm', 'Qoraqalpog\\'iston Respublikasi'], answer_index: 3, explanation: 'To\\'g\\'ri! Ustyurt platosi Qoraqalpog\\'iston hududida joylashgan bo\\'lib, o\\'ziga xos ekotizimga ega.' }
];

const newPuzzles = [
    { id: 'bp11', story: 'Daryo yuqorisida joylashgan zavod suvga issiq oqova suvlarni to\\'kmoqda. Suv tarkibida zaharli moddalar yo\\'q, u faqat issiq.', question: 'Buning ekologik oqibati qanday bo\\'ladi?', options: ['Hech qanday zarar bo\\'lmaydi', 'Suvda kislorod kamayadi va baliqlar o\\'ladi', 'Baliqlar tezroq o\\'sadi'], answer_index: 1, explanation: 'To\\'g\\'ri! Issiq suvda kislorod kam eriydi (Termal ifloslanish), natijada suv hayvonlari kislorod yetishmasligidan nobud bo\\'ladi.' },
    { id: 'bp12', story: 'Fermer hosilni oshirish uchun dalaga belgilangan me\\'yordan 3 barobar ko\\'p azotli o\\'g\\'it soldi. Kuchli yomg\\'ir yog\\'ib, daladagi suvlar yaqindagi ko\\'lga tushdi.', question: 'Ko\\'lda nima yuz beradi?', options: ['Ko\\'l suvi tozalanadi', 'Suv o\\'tlari keskin ko\\'payib, evtrofikatsiya yuz beradi', 'Suv sathi pasayadi'], answer_index: 1, explanation: 'To\\'g\\'ri! Azotli o\\'g\\'itlar ko\\'lga tushganda suv o\\'tlari tez ko\\'payib ketadi va kislorodni yutib, boshqa jonivorlarni o\\'ldiradi.' },
    { id: 'bp13', story: 'O\\'rmonda qadimgi va quruq daraxtlar ko\\'payib ketdi. O\\'rmonchilar barcha eski daraxtlarni kesib, tozalab tashlashdi.', question: 'Buning salbiy oqibati nima bo\\'lishi mumkin?', options: ['O\\'rmon go\\'zallashadi', 'Quruq daraxtlar kovagida yashovchi foydali qushlar va hasharotlar yashash joyisiz qoladi', 'Yangi daraxtlar o\\'smay qoladi'], answer_index: 1, explanation: 'To\\'g\\'ri! Quruq daraxtlar (o\\'lik yog\\'och) ko\\'plab o\\'rmon jonivorlari uchun muhim yashash makoni hisoblanadi.' },
    { id: 'bp14', story: 'Bir guruh yoshlar tog\\'li hududda dam olishdi va musiqa apparaturasini eng baland ovozda qo\\'yib xursandchilik qilishdi.', question: 'Bu tabiatga qanday zarar yetkazadi?', options: ['Faqat odamlarga xalaqit beradi', 'Kuchli shovqin hayvonlarni cho\\'chitib, qushlarning uya qurishi va ko\\'payishiga to\\'sqinlik qiladi', 'Daraxtlar bargi to\\'kiladi'], answer_index: 1, explanation: 'To\\'g\\'ri! Akustik (shovqin) ifloslanishi hayvonlarning tabiiy ritmini buzadi va ularni o\\'z makonlaridan qochishiga sabab bo\\'ladi.' },
    { id: 'bp15', story: 'Dehqon sug\\'orishda doimiy ravishda ortiqcha suv sarflamoqda (dalani ko\\'llatib sug\\'ormoqda). Tuproqda hech qanday o\\'g\\'it yo\\'q.', question: 'Bu usul tuproqqa qanday ta\\'sir qiladi?', options: ['Tuproqning sho\\'rlanishiga yoki botqoqlanishiga olib keladi', 'Tuproq unumdorligi oshadi', 'Suv tejab qolinadi'], answer_index: 0, explanation: 'To\\'g\\'ri! Ortiqcha sug\\'orish yer osti sizot suvlarini ko\\'tarib, tuproqni sho\\'rlatadi va yaroqsiz holga keltiradi.' },
    { id: 'bp16', story: 'Shaharda eski avtomobillar o\\'rniga asosan elektromobillar harakatlana boshladi. Shahardagi ba\\'zi elektr stansiyalari esa ko\\'mirda ishlaydi.', question: 'Ekologik vaziyat to\\'liq yechildimi?', options: ['Ha, elektromobil umuman zarar qilmaydi', 'Yo\\'q, chunki elektromobillar uchun kerakli elektr energiyasi ko\\'mir yoqish orqali olinmoqda (zarar boshqa joyga ko\\'chdi)', 'Ha, chunki ko\\'mir arzon'], answer_index: 1, explanation: 'To\\'g\\'ri! Elektromobilning tozaligi u iste\\'mol qilayotgan energiya qanday usulda olinganiga bog\\'liq.' },
    { id: 'bp17', story: 'Ovchilar cho\\'l hududida yirtqich yilonlarni va kaltakesaklarni yoppasiga ovlay boshlashdi.', question: 'Qanday oqibat kelib chiqadi?', options: ['Cho\\'lda o\'simliklar ko\\'payadi', 'Kemiruvchilar (sichqonlar, yumronqoziqlar) soni keskin oshib, ekinlarga va yaylovlarga zarar yetkazadi', 'Cho\\'lda suv ko\\'payadi'], answer_index: 1, explanation: 'To\\'g\\'ri! Ilonlar va kaltakesaklar kemiruvchilarning tabiiy kushandalari hisoblanadi.' },
    { id: 'bp18', story: 'Shahar markazidagi katta bog\\' (park) o\\'rniga savdo markazi qurildi. Odamlar faqat savdo markaziga kelib-keta boshladi.', question: 'Shaharning mikroiqlimida qanday o\\'zgarish bo\\'ladi?', options: ['Havo tozalanadi', 'Yozda havo harorati ko\\'tariladi, chang miqdori oshadi, kislorod kamayadi', 'Hech qanday o\\'zgarish bo\\'lmaydi'], answer_index: 1, explanation: 'To\\'g\\'ri! Daraxtlar shahar mikroiqlimini mo\\'tadillashtiruvchi, changni tutib qoluvchi asosiy \"filtr\" hisoblanadi.' },
    { id: 'bp19', story: 'Baliqchilar daryodan baliq tutish uchun to\'r emas, balki portlovchi modda (dinamit) ishlatishdi.', question: 'Bu usulning ekologik xavfi nimada?', options: ['Faqat katta baliqlar tutib olinadi', 'Barcha tirik organizmlar, jumladan mayda baliqlar va suv tubi ekotizimi butunlay yo\\'q qilinadi', 'Suv isib ketadi'], answer_index: 1, explanation: 'To\\'g\\'ri! Portlatish orqali baliq ovlash (brakonyerlik) butun ekotizimni nobud qiluvchi eng vahshiy usuldir.' },
    { id: 'bp20', story: 'Fermer zararkunandalarga qarshi kimyoviy dorilardan umuman voz kechib, ularni yeydigan foydali hasharotlar (masalan, xonqizi) ni dalaga qo\\'yib yubordi.', question: 'Bu qanday kurash usuli deyiladi?', options: ['Mexanik kurash', 'Biologik kurash usuli', 'Kimyoviy kurash'], answer_index: 1, explanation: 'To\\'g\\'ri! Zararkunandalarga qarshi ularning tabiiy dushmanlaridan foydalanish ekologik toza va samarali biologik usuldir.' }
];

const newTerms = [
    { id: 'bt11', question: 'Biotsenoz nima?', options: ['Faqat bir turdagi hayvonlar to\\'dasi', 'Muayyan hududda yashovchi barcha tirik organizmlar (o\\'simlik, hayvon, mikroorganizm) majmuasi', 'Jonsiz tabiat elementlari'], answer_index: 1, explanation: 'To\\'g\\'ri! Biotsenoz - ma\\'lum hududdagi barcha tirik organizmlarning o\\'zaro bog\\'langan majmuasidir.' },
    { id: 'bt12', question: 'Biotop nima?', options: ['Hayvonlarning ozuqasi', 'Biotsenoz yashaydigan jonsiz muhit (hudud, iqlim, tuproq)', 'O\\'simliklar bargi'], answer_index: 1, explanation: 'To\\'g\\'ri! Biotop - tirik organizmlar yashashi uchun kerak bo\\'lgan abiotik (jonsiz) sharoitlar yig\\'indisidir.' },
    { id: 'bt13', question: 'Biogeotsenoz nima?', options: ['Biotsenoz + Biotop', 'Faqat suv ekotizimi', 'Faqat tuproqdagi hayot'], answer_index: 0, explanation: 'To\\'g\\'ri! Biogeotsenoz - tirik organizmlar va ular yashaydigan muhitning o\\'zaro ta\\'siri orqali shakllangan yaxlit tizim (ekotizim).' },
    { id: 'bt14', question: 'Gidrobiontlar nima?', options: ['Havoda uchuvchi hayvonlar', 'Quruqlikda yashovchi hayvonlar', 'Suv muhitiga moslashib yashovchi organizmlar'], answer_index: 2, explanation: 'To\\'g\\'ri! Baliqlar, qisqichbaqalar, suv o\\'tlari kabi barcha suv organizmlari gidrobiontlar deyiladi.' },
    { id: 'bt15', question: 'Ksenobiotiklar nima?', options: ['Foydali bakteriyalar', 'Tabiiy muhit uchun yot bo\\'lgan, inson tomonidan yaratilgan sun\\'iy va zaharli moddalar', 'Noyob o\\'simliklar'], answer_index: 1, explanation: 'To\\'g\\'ri! Plastiklar, ayrim pestisidlar va sintetik moddalar tabiat uchun begona (ksenobiotik) bo\\'lib, asrlar davomida parchalanmaydi.' },
    { id: 'bt16', question: 'Melioratsiya nima?', options: ['Yerning unumdorligini oshirishga qaratilgan chora-tadbirlar tizimi (sug\\'orish, sho\\'rini yuvish va h.k.)', 'O\\'rmonlarni kesish', 'Sanoat korxonalari qurish'], answer_index: 0, explanation: 'To\\'g\\'ri! Melioratsiya tuproqning holatini yaxshilash va qishloq xo\\'jaligi hosildorligini oshirish tadbirlari hisoblanadi.' },
    { id: 'bt17', question: 'Aerozol nima?', options: ['Suyuq o\\'g\\'it', 'Gazsimon muhitdagi muallaq qattiq yoki suyuq zarralar (tuman, chang, tutun)', 'Ozon qatlami'], answer_index: 1, explanation: 'To\\'g\\'ri! Havoning sanoat gazlari va tutunlar bilan ifloslanishi ko\\'pincha aerozollar shaklida namoyon bo\\'ladi.' },
    { id: 'bt18', question: 'Flora va Fauna o\\'rtasidagi farq nima?', "options": ["Flora - hayvonlar, Fauna - o'simliklar", "Flora - o'simliklar olami, Fauna - hayvonot olami", "Ularning farqi yo'q"], answer_index: 1, explanation: 'To\\'g\\'ri! Flora lotincha gul mabudasi nomidan olingan bo\\'lib o\\'simliklarni, Fauna esa hayvonot olamini bildiradi.' },
    { id: 'bt19', question: 'Rekultivatsiya nima?', options: ['Foydali qazilmalar qazib olingan buzilgan yerlarni qayta tiklash va yaroqli holga keltirish', 'Yangi konlar ochish', 'Yovvoyi hayvonlarni ovlash'], answer_index: 0, explanation: 'To\\'g\\'ri! Kon qazilgan kar\\'yerlarni tuproq bilan to\\'ldirib, o\\'rmon yoki ekinzor barpo etish rekultivatsiya deyiladi.' },
    { id: 'bt20', question: 'Brakonyerlik bu...', options: ['Daraxtlarni parvarishlash', 'Belgilangan qoidalarni buzgan holda (ruxsatsiz, taqiqlangan vaqtda yoki usulda) yovvoyi hayvonlarni ovlash', 'Chiqindilarni saralash'], answer_index: 1, explanation: 'To\\'g\\'ri! Brakonyerlik tabiatga va bioxilma-xillikka katta xavf tug\\'diruvchi jinoiy faoliyatdir.' }
];

const newPenalties = [
    { id: 'bpn11', question: 'Shahar ichida (aholi punktlarida) chiqindilarni yoqish (masalan, xazonlarni yoqish) MJtKning qaysi moddasi bilan jazolanadi?', options: ['MJtK 60-modda', 'MJtK 88-3-moddasi', 'MJtK 111-modda'], answer_index: 1, explanation: 'To\\'g\\'ri! Aholi punktlarida xazon va shox-shabbalarni yoqish havoni zaharli tutun bilan ifloslantirgani uchun jarimaga sabab bo\\'ladi.' },
    { id: 'bpn12', question: 'Suvni muhofaza qilish zonalarida avtomobillarni yuvish mumkinmi?', options: ['Ha, agar toza suv bilan yuvsa', 'Yo\\'q, qat\\'iyan taqiqlangan, MJtK 72-moddasiga asosan jarima solinadi', 'Ruxsat etilgan'], answer_index: 1, explanation: 'To\\'g\\'ri! Suv ob\\'ektlarini moy va yonilg\\'i bilan ifloslantirish suv ekotizimiga jiddiy zarar yetkazadi.' },
    { id: 'bpn13', question: 'Daraxtni kesish emas, balki uni o\\'sishdan to\\'xtaydigan darajada qasddan shikastlantirish (masalan, ildiziga zahar quyish) jazolanadimi?', options: ['Yo\\'q, daraxt joyida turibdi-ku', 'Ha, xuddi daraxtni kesgan kabi javobgarlikka tortiladi (MJtK 79-modda)', 'Faqat yozma ogohlantiriladi'], answer_index: 1, explanation: 'To\\'g\\'ri! Daraxtni qasddan quritish yoki unga o\\'nglanmas darajada shikast yetkazish daraxt kesishga tenglashtiriladi.' },
    { id: 'bpn14', question: 'Zavodlar havo ifloslantirish miqdorini doimiy hisobga olib borishi (ekologik pasport) shartmi?', options: ['Ixtiyoriy', 'Ha, shart. Buni bajarmaslik javobgarlikka sabab bo\\'ladi', 'Faqat davlat korxonalari uchun shart'], answer_index: 1, explanation: 'To\\'g\\'ri! Har bir yirik korxona o\\'zining atrof-muhitga ta\\'siri haqida rasmiy ekologik hujjatlarga ega bo\\'lishi shart.' },
    { id: 'bpn15', question: 'Muhofaza etiladigan tabiiy hududlarda (masalan, Milliy bog\\'da) noqonuniy ov qilishning jazosi oddiy hududdagidan farq qiladimi?', options: ['Farqi yo\\'q, jazo bir xil', 'Ha, muhofaza etiladigan hududlarda jinoyat yanada og\\'irroq hisoblanib, jazo va jarima miqdori ancha yuqori bo\\'ladi', 'Jarima arzonroq'], answer_index: 1, explanation: 'To\\'g\\'ri! Qo\\'riqxonalar va milliy bog\\'lar tabiatning o\\'ta muhim qismi bo\\'lgani uchun u yerdagi har qanday ziyon og\\'ir jazolanadi.' },
    { id: 'bpn16', question: 'Noqonuniy ov paytida hayvonga yetkazilgan zarar qanday hisoblanadi?', options: ['Faqat go\\'shtining bozor narxida', 'Maxsus tasdiqlangan taksalar (tariflar) asosida, bu bozor narxidan o\\'nlab marta qimmat bo\\'lishi mumkin', 'Zarar to\\'lanmaydi, faqat jarima'], answer_index: 1, explanation: 'To\\'g\\'ri! Tabiatga yetkazilgan zararni hisoblashda noyoblik darajasi hisobga olinadi va maxsus tariflar qo\\'llaniladi.' },
    { id: 'bpn17', question: 'Elektr qarmoq yordamida baliq ovlash qonuniymi?', options: ['Qonuniy, u tez ovlaydi', 'Mutlaqo taqiqlangan va shafqatsiz usul (brakonyerlik) hisoblanib, jinoiy javobgarlikka tortiladi', 'Faqat qishda mumkin'], answer_index: 1, explanation: 'To\\'g\\'ri! Elektr toki suvdagi barcha tirik jonzotlarni (hatto mayda chavachoqlarni ham) yoppasiga o\\'ldiradi. Bu butun ekotizimni yo\\'q qiladi.' },
    { id: 'bpn18', question: 'Ekinzorlarda pestisidlarni (zaharlarni) me\\'yordan ortiq qo\\'llab, tuproqni yaroqsiz holga keltirish kimning javobgarligi?', options: ['Zaharni sotgan do\\'konning', 'Foydalangan yer egasi (fermer) ning', 'Hech kimning'], answer_index: 1, explanation: 'To\\'g\\'ri! Yerdan oqilona foydalanish va ekologik xavfsizlikni ta\\'minlash yer egasi yoki ijarachisining to\\'g\\'ridan-to\\'g\\'ri majburiyatidir.' },
    { id: 'bpn19', question: 'Qurilish chiqindilarini (shifer, g\\'isht parchalari) shahar chetidagi bo\\'sh yerlarga to\\'kish...', options: ['Mumkin, chunki ular chimaydigan narsalar', 'Qat\\'iyan taqiqlangan va yirik jarimaga sabab bo\\'ladi', 'Faqat tunda ruxsat etiladi'], answer_index: 1, explanation: 'To\\'g\\'ri! Barcha turdagi chiqindilar faqat maxsus ajratilgan poligonlarga (axlatxonalarga) tashlanishi shart.' },
    { id: 'bpn20', question: 'Daraxtni kesishga qonuniy ruxsatnoma bo\\'lsa ham, daraxt kesilgandan so\\'ng nima qilish majburiy hisoblanadi?', options: ['Joyini tozalab qo\\'yish', '1 ta kesilgan daraxt o\\'rniga 100 ta qimmatbaho daraxt ko\\'chatini ekish va 3 yil parvarish qilish', 'O\\'tinni davlatga topshirish'], answer_index: 1, explanation: 'To\\'g\\'ri! O\\'zbekiston qonunchiligiga ko\\'ra, zarurat tufayli daraxt kesilganda uning o\\'rnini qoplash majburiyati yuklanadi (Kompensatsiya ekish).' }
];

const newTrueFalse = [
    { id: 'btf11', question: 'Zavodning ekologik zararini kamaytirish uchun trubani juda baland qilib qurish muammoni to\\'liq hal qiladi.', options: ['Rost', 'Yolg\\'on'], answer_index: 1, explanation: 'Yolg\\'on! Trubani baland qilish faqatgina zaharli gazlarni shamol orqali uzoqroq hududlarga yoyib yuboradi xolos, gaz baribir atmosferada qoladi.' },
    { id: 'btf12', question: 'Chiqindisiz texnologiya bu umuman hech qanday qoldiq chiqarmaydigan mukammal zavod.', options: ['Rost', 'Yolg\\'on'], answer_index: 1, explanation: 'Yolg\\'on! Termodinamika qonunlariga ko\\'ra mutlaq chiqindisiz tizim bo\\'lishi mumkin emas. \"Chiqindisiz\" degani qoldiqlarni maksimal darajada qayta ishlashni anglatadi.' },
    { id: 'btf13', question: 'Avtomobillardan ajralib chiqadigan tutun tarkibida is gazi (CO), qo\\'rg\\'oshin va zaharli uglevodorodlar mavjud.', options: ['Rost', 'Yolg\\'on'], answer_index: 0, explanation: 'Rost! Avtotransport havo ifloslanishining asosiy qismini tashkil qiladi.' },
    { id: 'btf14', question: 'Orol dengizining qurishi asosan tabiiy iqlim o\\'zgarishi tufayli yuz berdi.', options: ['Rost', 'Yolg\\'on'], answer_index: 1, explanation: 'Yolg\\'on! Orol dengizi asosan insonning xo\\'jalik faoliyati (Sirdaryo va Amudaryo suvini paxta dalalariga haddan ortiq burib yuborish) oqibatida quridi.' },
    { id: 'btf15', question: 'Plastik va polietilen idishlar qayta ishlashga (Recycling) yaroqli materiallar hisoblanadi.', options: ['Rost', 'Yolg\\'on'], answer_index: 0, explanation: 'Rost! Ular saralanib qayta eritilsa, yangi mahsulotlar ishlab chiqarish mumkin.' },
    { id: 'btf16', question: 'Ozon qatlami yupqalashishi Yer yuzasida haroratning pasayishiga (sovuqqa) olib keladi.', options: ['Rost', 'Yolg\\'on'], answer_index: 1, explanation: 'Yolg\\'on! Ozon qatlamining yemirilishi Yer yuzasiga yetib keladigan issiqlik va zararli ultrabinafsha nurlar miqdorini oshiradi.' },
    { id: 'bt17', question: 'Qayta tiklanadigan tabiiy resurslarga (o\\'simlik va hayvonot olami, tuproq) ehtiyotsizlik bilan munosabatda bo\\'linsa, ular ham butunlay yo\\'qolib ketishi mumkin.', options: ['Rost', 'Yolg\\'on'], answer_index: 0, explanation: 'Rost! Tiklanish imkoniyati bor bo\\'lsa-da, ularni tiklanish tezligidan ko\\'ra tezroq sarflash ularning yo\\'qolishiga olib keladi.' },
    { id: 'bt18', question: 'Bir turdagi yirtqich hayvonni (masalan, bo\\'rini) o\\'rmondan butunlay yo\\'q qilib tashlash, o\\'rmon ekotizimi uchun doim foydalidir.', options: ['Rost', 'Yolg\\'on'], answer_index: 1, explanation: 'Yolg\\'on! Yirtqichlarning yo\\'qolishi o\\'txo\\'r hayvonlarning nazoratsiz ko\\'payishiga va o\\'rmonning payhon bo\\'lishiga olib keladi.' },
    { id: 'bt19', question: 'Elektromobillar atmosferaga bevosita tutun chiqarmaydi, shuning uchun ular ekologik toza transport hisoblanadi.', options: ['Rost', 'Yolg\\'on'], answer_index: 0, explanation: 'Rost! Ammo ularni quvvatlantiradigan elektr energiyasi qanday olinayotgani ham ekologiya uchun juda muhimdir.' },
    { id: 'bt20', question: 'Barcha bakteriyalar faqat kasallik tarqatuvchi zararli organizmlar bo\\'lib, ularni butunlay yo\\'q qilish kerak.', options: ['Rost', 'Yolg\\'on'], answer_index: 1, explanation: 'Yolg\\'on! Bakteriyalarning juda katta qismi (saprofitlar) o\\'lik a\\'zolarni parchalab, tabiatda moddalar aylanishini ta\\'minlaydi va ular hayot uchun o\\'ta muhimdir.' }
];


quizData.quizzes.push(...newQuizzes);
quizData.puzzles.push(...newPuzzles);
quizData.terms.push(...newTerms);
quizData.penalties.push(...newPenalties);
quizData.truefalse.push(...newTrueFalse);

fs.writeFileSync('./data/quiz.json', JSON.stringify(quizData, null, 4));
console.log('Done!');
