$prompts = @(
    "Cinematic 3D illustration dark premium aesthetic, businessman cutting 10 old trees in his territory without permission, construction background", # p1
    "Cinematic 3D illustration dark premium aesthetic, a large chemical factory emitting toxic smoke into the night air without filters, city in the background", # p2
    "Cinematic 3D illustration dark premium aesthetic, tourists leaving plastic bottles and food waste in a beautiful river, pollution", # p3
    "Cinematic 3D illustration dark premium aesthetic, a citizen illegally hunting a wild boar in a state forest without permission", # p4
    "Cinematic 3D illustration dark premium aesthetic, a farmer burning wheat stubble in his field, fire spreading to nearby trees", # p5
    "Cinematic 3D illustration dark premium aesthetic, a factory throwing toxic chemical waste into ordinary trash cans instead of a special polygon", # p6
    "Cinematic 3D illustration dark premium aesthetic, a construction company building a new multi-story house without ecological expertise, cranes in background", # p7
    "Cinematic 3D illustration dark premium aesthetic, a man driving his car to the river and washing it directly in the water, polluting it", # p8
    "Cinematic 3D illustration dark premium aesthetic, school children in a nature reserve picking rare beautiful flowers", # p9
    "Cinematic 3D illustration dark premium aesthetic, unknown people poaching a rare Bukhara deer at night, intending to sell the meat", # p10
    
    "Cinematic 3D illustration dark premium aesthetic, tree leaves turning yellow and drying near a factory due to acid rain", # bp1
    "Cinematic 3D illustration dark premium aesthetic, a farmer spraying strong pesticide to kill locusts, dead locusts, field swarming with mice", # bp2
    "Cinematic 3D illustration dark premium aesthetic, an industrial plant dumping hot wastewater into a lake, green algae multiplying rapidly, dead fish", # bp3
    "Cinematic 3D illustration dark premium aesthetic, people picking many rare red tulips (Butkov tulips) from the mountains", # bp4
    "Cinematic 3D illustration dark premium aesthetic, a city with many cars trapped in a thick toxic smog on a hot windless day", # bp5
    "Cinematic 3D illustration dark premium aesthetic, a penguin in the freezing Antarctic, toxic chemicals inside its body from far away", # bp6
    "Cinematic 3D illustration dark premium aesthetic, hunters killing all wolves in the forest, large sick deer population, disease spreading", # bp7
    "Cinematic 3D illustration dark premium aesthetic, a farmer plowing the soil at the same depth and planting only cotton every year, degraded soil", # bp8
    "Cinematic 3D illustration dark premium aesthetic, a rare Snow Leopard being hunted for its beautiful fur, endangered", # bp9
    "Cinematic 3D illustration dark premium aesthetic, dense tugai forests cut down along a river, the river drying up quickly in summer", # bp10
    
    "Cinematic 3D illustration dark premium aesthetic, a factory upstream pouring hot wastewater into the river", # bp11
    "Cinematic 3D illustration dark premium aesthetic, a farmer applying 3 times too much nitrogen fertilizer, rain washing it into the lake", # bp12
    "Cinematic 3D illustration dark premium aesthetic, foresters cutting down and clearing all old and dry trees in the woods", # bp13
    "Cinematic 3D illustration dark premium aesthetic, people resting in the mountains playing extremely loud music from speakers", # bp14
    "Cinematic 3D illustration dark premium aesthetic, a farmer constantly wasting water, over-irrigating and flooding his field", # bp15
    "Cinematic 3D illustration dark premium aesthetic, city full of electric cars, but electricity is generated by a polluting coal power plant in the background", # bp16
    "Cinematic 3D illustration dark premium aesthetic, hunters catching carnivorous snakes and lizards in the desert en masse", # bp17
    "Cinematic 3D illustration dark premium aesthetic, a large park in the center of the city replaced by a new concrete shopping mall", # bp18
    "Cinematic 3D illustration dark premium aesthetic, fishermen using illegal dynamite explosives to catch fish in a river", # bp19
    "Cinematic 3D illustration dark premium aesthetic, a farmer releasing ladybugs into the field to eat pests instead of using chemicals", # bp20
    
    "Cinematic 3D illustration dark premium aesthetic, dense mangrove forests cut for firewood, later a huge tsunami wave destroying coastal houses", # bp21
    "Cinematic 3D illustration dark premium aesthetic, a farmer spraying so much pesticide that both pests and honey bees are dead", # bp22
    "Cinematic 3D illustration dark premium aesthetic, city trees cruelly pruned leaving only the trunks, people struggling to breathe in summer", # bp23
    "Cinematic 3D illustration dark premium aesthetic, a pond full of fish turns completely green with algae after fertilizer runoff from a farm", # bp24
    "Cinematic 3D illustration dark premium aesthetic, villagers living near a factory suffering from dental fluorosis and brittle bones", # bp25
    "Cinematic 3D illustration dark premium aesthetic, rising temperatures in the Arctic, icebergs melting into the ocean", # bp26
    "Cinematic 3D illustration dark premium aesthetic, an island where snakes were eradicated, now swarming with rats eating bird eggs", # bp27
    "Cinematic 3D illustration dark premium aesthetic, plastic bottles being melted and pressed into new building materials", # bp28
    "Cinematic 3D illustration dark premium aesthetic, a burnt forest with ash, small grass and moss growing first, symbolizing nature's recovery", # bp29
    "Cinematic 3D illustration dark premium aesthetic, people tearing out rare mountain tulips with their roots to plant in their gardens" # bp30
)

$ErrorActionPreference = "Continue"

if (-not (Test-Path -Path "./data/images")) {
    New-Item -ItemType Directory -Force -Path "./data/images" | Out-Null
}

$jsonText = [System.IO.File]::ReadAllText('./data/quiz.json')
$data = ConvertFrom-Json $jsonText
$puzzles = $data.puzzles

for ($i = 0; $i -lt $prompts.Length; $i++) {
    $puzzleId = $puzzles[$i].id
    $imgName = "$puzzleId.jpg"
    $imgPath = "./data/images/$imgName"
    
    $encodedPrompt = [System.Uri]::EscapeDataString($prompts[$i])
    $url = "https://image.pollinations.ai/prompt/$encodedPrompt?width=800&height=600&nologo=true&seed=$i"
    
    try {
        Invoke-WebRequest -Uri $url -OutFile $imgPath -UseBasicParsing
        Write-Host "Yuklandi: $imgName"
    } catch {
        Write-Host "Xato: $imgName -> $_"
    }
    
    if (-not $puzzles[$i].psobject.properties.Match('image').Count) {
        $puzzles[$i] | Add-Member -MemberType NoteProperty -Name "image" -Value $imgPath -Force
    } else {
        $puzzles[$i].image = $imgPath
    }
    
    Start-Sleep -Seconds 1
}

# The remaining puzzles (from index 40 onwards) will use the default image (data/puzzle_bg.jpg)
for ($j = $prompts.Length; $j -lt $puzzles.Length; $j++) {
    $imgPath = "./data/puzzle_bg.jpg"
    if (-not $puzzles[$j].psobject.properties.Match('image').Count) {
        $puzzles[$j] | Add-Member -MemberType NoteProperty -Name "image" -Value $imgPath -Force
    } else {
        $puzzles[$j].image = $imgPath
    }
}

$jsonOutput = ConvertTo-Json -InputObject $data -Depth 10 -Compress
[System.IO.File]::WriteAllText('./data/quiz.json', $jsonOutput, [System.Text.Encoding]::UTF8)

# Clean up any other files in images except the 40 we just made
$validFiles = $puzzles[0..39] | ForEach-Object { "$($_.id).jpg" }
Get-ChildItem -Path './data/images' -Filter '*.jpg' | ForEach-Object {
    if ($_.Name -notin $validFiles) {
        Remove-Item -Path $_.FullName -Force
    }
}

Write-Host "40 ta aniq rasm muvaffaqiyatli chizildi va biriktirildi!"
